"""
This type stub file was generated by pyright.
"""

def default_inference_function(params=...): # -> Callable[..., dict[str, list[dict[str, list[str]]]]]:
    """
    Default function used in RAGPattern when no ``inference_function`` is provided.

    Input schema:
    payload = {
        client.deployments.ScoringMetaNames.INPUT_DATA: [
            {
                "values": ["question 1", "question 2"],
                "access_token": "<bearer_token>"
            }
        ]
    }

    Output schema:
    result = {
        'predictions': [
            {
                'fields': ['answer', 'reference_documents'],
                'values': [
                    ['answer 1', [ {'page_content': 'page content 1',
                                    'metadata':     'metadata 1'} ]],
                    ['answer 2', [ {'page_content': 'page content 2',
                                    'metadata':     'metadata 2'} ]]
                ]
            }
        ]
    }
    """
    ...

