"""
This type stub file was generated by pyright.
"""

def inference_service(context, vector_store_settings=...): # -> tuple[Callable[..., dict[str, dict[str, list[dict[str, Any]]]]], Callable[..., Generator[dict[str, list[dict[str, Any]]], Any, None]]]:
    """
    Default inference AI service function.

    :param vector_store_settings: Vector store settings, such as `connection_id`, `collection_name` and scope identifier: space_id/project_id,
                                 encapsulated in a dictionary. Setting these parameters when creating deployment one can overwrite the defaults.
    :type vector_store_settings: dict, optional

    .. code-block:: python

        from ibm_watsonx_ai import APIClient, Credentials

        client = APIClient(
            credentials=Credentials(url="<url>", token="<token>"), space_id=space_id
        )

        meta_props = {
            client.deployments.ConfigurationMetaNames.NAME: "SAMPLE DEPLOYMENT NAME",
            client.deployments.ConfigurationMetaNames.ONLINE: {
                "parameters": {
                    "vector_store_settings": {
                        "connection_id": "<connection_to_vector_store>",
                        "collection_name": "<collection_name>",
                        "project_id": "<project_id>",
                    }
                }
            },
        }

        deployment_details = client.deployments.create(ai_service_id, meta_props)

    Input schema:
    payload = {
       "messages":[
            {
                "role" : "user",
                "content" : "question_1"
            }
        ]
    }

    Output schema:
    result = {
        'choices': [
            {
                'index': 0,
                'message': {
                    'content': 'generated_content',
                    'role': 'assistant'
                },
                "reference_documents" : [
                            {
                                'sequence_number': [1, 2, 3],
                                'document_id': '<document_id>'
                            }
                        ]
            }
        ]
    }
    """
    ...

