"""
This type stub file was generated by pyright.
"""

class CPDVersion:
    """Storage for cpd version. Comparison operators are
    overloaded to allow comparison with numeric values.

    Class attribute:
    :param supported_version_list: List of supported CPD versions.
    :type supported_version_list: list

    Attribute:
    :param cpd_version: Store CPD version.
    :type cpd_version: Optional[str], optional

    .. code-block:: python

        from ibm_watsonx_ai.utils import CPDVersion

        version = CPDVersion()

        if not version:
            print("CPD version is None")

        version.cpd_version = "4.5"

        if version > 4:
            print("version greater than 4.0")

    """
    supported_version_list = ...
    def __init__(self, version: str | None = ...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def cpd_version(self) -> float:
        """Attribute that stores cpd version. Before the value is set,
        validation is performed against a supported versions.
        """
        ...
    
    @cpd_version.setter
    def cpd_version(self, value: float | str) -> None:
        ...
    
    @cpd_version.getter
    def cpd_version(self) -> float | None:
        ...
    
    def __bool__(self) -> bool:
        ...
    
    def __eq__(self, value: float) -> bool:
        ...
    
    def __ne__(self, value: float) -> bool:
        ...
    
    def __lt__(self, value: float) -> bool:
        ...
    
    def __le__(self, value: float) -> bool:
        ...
    
    def __gt__(self, value: float) -> bool:
        ...
    
    def __ge__(self, value: float) -> bool:
        ...
    


