"""
This type stub file was generated by pyright.
"""

from typing import List, TYPE_CHECKING, Union
from ibm_watsonx_ai.helpers.connections import DataConnection
from ibm_watsonx_ai.workspace import WorkSpace

if TYPE_CHECKING:
    ...
__all__ = ["validate_source_data_connections", "create_results_data_connection", "validate_results_data_connection", "create_deployment_output_data_connection", "validate_deployment_output_connection", "get_max_sample_size_limit"]
def validate_source_data_connections(source_data_connections: List[DataConnection], workspace: WorkSpace, deployment=...) -> List[DataConnection]:
    ...

def create_results_data_connection(source_data_connections: List[DataConnection], workspace: WorkSpace) -> DataConnection:
    ...

def validate_results_data_connection(results_data_connection: Union[DataConnection, None], workspace: WorkSpace, source_data_connections: List[DataConnection] = ...) -> DataConnection:
    ...

def create_deployment_output_data_connection(source_data_connections: List[DataConnection], output_filename=...) -> DataConnection:
    ...

def validate_deployment_output_connection(results_data_connection: Union[DataConnection, None], workspace: WorkSpace, source_data_connections: List[DataConnection] = ...) -> DataConnection:
    ...

def get_max_sample_size_limit() -> int:
    """Get Sample Size Limit based on T-Shirt size if code is run on training pod:
    For memory < 16 (T-Shirts: XS,S) default is 10MB,
    For memory < 32 & >= 16 (T-Shirts: M) default is 100MB,
    For memory = 32 (T-Shirt L) default is 0.7GB,
    For memory > 32 (T-Shirt XL) or runs outside pod default is 1GB.
    Returns sample size limit in bytes.
    """
    ...

