"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.wml_client_error import WMLClientError

__all__ = ["MissingPipeline", "FitNotCompleted", "FitNeeded", "AutoAIComputeError", "MissingAutoPipelinesParameters", "UseWMLClient", "PipelineNotLoaded", "MissingCOSStudioConnection", "MissingIBMWatsonStudioLib", "LocalInstanceButRemoteParameter", "DataFormatNotSupported", "HoldoutSplitNotSupported", "LibraryNotCompatible", "CannotInstallLibrary", "InvalidCOSCredentials", "CannotDownloadTrainingDetails", "TShirtSizeNotSupported", "MissingPositiveLabel", "MissingDataPreprocessingStep", "CannotDownloadWMLPipelineDetails", "SetIDFailed", "MissingLocalAsset", "DataSourceSizeNotSupported", "TrainingDataSourceIsNotFile", "VisualizationFailed", "InvalidPredictionType", "InvalidIdType", "NoneDataConnection", "CannotReadSavedRemoteDataBeforeFit", "NotExistingCOSResource", "AdditionalParameterIsUnexpected", "ForecastPredictionColumnsMissing", "TimeseriesAnomalyPredictionFeatureColumnsMissing", "TimeseriesAnomalyPredictionUnsupportedMetric", "NonForecastPredictionColumnMissing", "ForecastingCannotBeRunAsLocalScenario", "TimeseriesAnomalyPredictionCannotBeRunAsLocalScenario", "ForecastingUnsupportedOperation", "InvalidSequenceValue", "NoAvailableMetrics", "WrongAssetType", "TSNotSupported", "TSADNotSupported", "InvalidDataAsset", "CannotConnectToWebsocket", "TestDataNotPresent", "NoAutomatedHoldoutSplit", "DiscardedModel", "WrongModelName", "StrategyIsNotApplicable", "NumericalImputationStrategyValueMisused", "InvalidImputationParameterNonTS", "InvalidImputationParameterTS", "InconsistentImputationListElements", "ImputationListNotSupported", "MissingEstimatorForExistingBatchedEstimator", "FutureExogenousFeaturesNotSupported", "NoAvailableNotebookLocation", "ContainerTypeNotSupported", "InvalidSizeLimit", "CorruptedData", "MissingMandatoryKey", "MaxSizeOfFileExceeded", "InvalidLocationInDataConnection", "DirectoryHasNoFilename", "CannotGetFilename", "TokenRemovedDuringClientCopy", "FolderDownloadNotSupported", "NoDocumentsLoaded"]
class MissingPipeline(WMLClientError, ValueError):
    def __init__(self, value_name, reason=...) -> None:
        ...
    


class FitNotCompleted(WMLClientError, ValueError):
    def __init__(self, value_name, reason=...) -> None:
        ...
    


class FitNeeded(WMLClientError, ValueError):
    def __init__(self, value_name=..., reason=...) -> None:
        ...
    


class AutoAIComputeError(WMLClientError, ValueError):
    def __init__(self, value_name, reason=...) -> None:
        ...
    


class MissingAutoPipelinesParameters(WMLClientError, ValueError):
    def __init__(self, value_name, reason=...) -> None:
        ...
    


class UseWMLClient(WMLClientError, ValueError):
    def __init__(self, value_name, reason=...) -> None:
        ...
    


class PipelineNotLoaded(WMLClientError, ValueError):
    def __init__(self, value_name, reason=...) -> None:
        ...
    


class MissingCOSStudioConnection(WMLClientError, ValueError):
    def __init__(self, reason=...) -> None:
        ...
    


class MissingIBMWatsonStudioLib(WMLClientError, ValueError):
    def __init__(self, reason=...) -> None:
        ...
    


class LocalInstanceButRemoteParameter(WMLClientError, ValueError):
    def __init__(self, value_name=..., reason=...) -> None:
        ...
    


class DataFormatNotSupported(WMLClientError, ValueError):
    def __init__(self, reason=...) -> None:
        ...
    


class HoldoutSplitNotSupported(WMLClientError, ValueError):
    def __init__(self, value_name=..., reason=...) -> None:
        ...
    


class LibraryNotCompatible(WMLClientError, ValueError):
    def __init__(self, value_name=..., reason=...) -> None:
        ...
    


class CannotInstallLibrary(WMLClientError, ValueError):
    def __init__(self, value_name=..., reason=...) -> None:
        ...
    


class InvalidCOSCredentials(WMLClientError, ValueError):
    def __init__(self, value_name=..., reason=...) -> None:
        ...
    


class CannotDownloadTrainingDetails(WMLClientError, ValueError):
    def __init__(self, value_name, reason=...) -> None:
        ...
    


class TShirtSizeNotSupported(WMLClientError, ValueError):
    def __init__(self, value_name=..., reason=...) -> None:
        ...
    


class MissingPositiveLabel(WMLClientError, ValueError):
    def __init__(self, value_name=..., reason=...) -> None:
        ...
    


class MissingDataPreprocessingStep(WMLClientError, ValueError):
    def __init__(self, value_name=..., reason=...) -> None:
        ...
    


class CannotDownloadWMLPipelineDetails(WMLClientError, ValueError):
    def __init__(self, value_name, reason=...) -> None:
        ...
    


class SetIDFailed(WMLClientError, ValueError):
    def __init__(self, value_name=..., reason=...) -> None:
        ...
    


class MissingLocalAsset(WMLClientError, ValueError):
    def __init__(self, value_name=..., reason=...) -> None:
        ...
    


class DataSourceSizeNotSupported(WMLClientError, ValueError):
    def __init__(self, reason=...) -> None:
        ...
    


class TrainingDataSourceIsNotFile(WMLClientError, ValueError):
    def __init__(self, data_location=..., reason=...) -> None:
        ...
    


class VisualizationFailed(WMLClientError, ValueError):
    def __init__(self, value_name=..., reason=...) -> None:
        ...
    


class InvalidPredictionType(WMLClientError, ValueError):
    def __init__(self, value_name=..., reason=...) -> None:
        ...
    


class InvalidIdType(WMLClientError, ValueError):
    def __init__(self, typ) -> None:
        ...
    


class NoneDataConnection(WMLClientError, ValueError):
    def __init__(self, resource_name) -> None:
        ...
    


class CannotReadSavedRemoteDataBeforeFit(WMLClientError, ValueError):
    def __init__(self) -> None:
        ...
    


class NotExistingCOSResource(WMLClientError, ValueError):
    def __init__(self, bucket, path) -> None:
        ...
    


class AdditionalParameterIsUnexpected(WMLClientError):
    def __init__(self, param) -> None:
        ...
    


class ForecastPredictionColumnsMissing(WMLClientError):
    def __init__(self) -> None:
        ...
    


class TimeseriesAnomalyPredictionFeatureColumnsMissing(WMLClientError):
    def __init__(self) -> None:
        ...
    


class TimeseriesAnomalyPredictionUnsupportedMetric(WMLClientError):
    def __init__(self, metric) -> None:
        ...
    


class NonForecastPredictionColumnMissing(WMLClientError):
    def __init__(self, prediction_type) -> None:
        ...
    


class ForecastingCannotBeRunAsLocalScenario(WMLClientError):
    def __init__(self) -> None:
        ...
    


class TimeseriesAnomalyPredictionCannotBeRunAsLocalScenario(WMLClientError):
    def __init__(self) -> None:
        ...
    


class ForecastingUnsupportedOperation(WMLClientError):
    def __init__(self) -> None:
        ...
    


class InvalidSequenceValue(WMLClientError, ValueError):
    def __init__(self, el, correct_values) -> None:
        ...
    


class NoAvailableMetrics(WMLClientError):
    def __init__(self) -> None:
        ...
    


class WrongAssetType(WMLClientError):
    def __init__(self, asset_type: str) -> None:
        ...
    


class TSNotSupported(WMLClientError):
    def __init__(self) -> None:
        ...
    


class TSADNotSupported(WMLClientError):
    def __init__(self) -> None:
        ...
    


class InvalidDataAsset(WMLClientError, ValueError):
    def __init__(self, reason=...) -> None:
        ...
    


class CannotConnectToWebsocket(WMLClientError, ValueError):
    def __init__(self, n) -> None:
        ...
    


class TestDataNotPresent(WMLClientError, ValueError):
    def __init__(self, reason) -> None:
        ...
    


class NoAutomatedHoldoutSplit(WMLClientError, ValueError):
    def __init__(self, reason) -> None:
        ...
    


class DiscardedModel(WMLClientError, ValueError):
    def __init__(self, model_name) -> None:
        ...
    


class WrongModelName(WMLClientError, ValueError):
    def __init__(self, model_name) -> None:
        ...
    


class StrategyIsNotApplicable(WMLClientError, ValueError):
    def __init__(self, strategy, prediction_type, valid_strategies) -> None:
        ...
    


class NumericalImputationStrategyValueMisused(WMLClientError, ValueError):
    def __init__(self) -> None:
        ...
    


class InvalidImputationParameterNonTS(WMLClientError, ValueError):
    def __init__(self) -> None:
        ...
    


class InvalidImputationParameterTS(WMLClientError, ValueError):
    def __init__(self) -> None:
        ...
    


class InconsistentImputationListElements(WMLClientError, ValueError):
    def __init__(self, strategies) -> None:
        ...
    


class ImputationListNotSupported(WMLClientError, ValueError):
    def __init__(self) -> None:
        ...
    


class InvalidSamplingType(WMLClientError, ValueError):
    def __init__(self, sampling_type: str, predcition_type: str) -> None:
        ...
    


class MissingEstimatorForExistingBatchedEstimator(WMLClientError, ValueError):
    def __init__(self, batched_estimator: str, missing_estimator: str) -> None:
        ...
    


class FutureExogenousFeaturesNotSupported(WMLClientError, ValueError):
    def __init__(self, prediction_type: str) -> None:
        ...
    


class NoAvailableNotebookLocation(WMLClientError, ValueError):
    def __init__(self, pipeline_name) -> None:
        ...
    


class ContainerTypeNotSupported(WMLClientError, ValueError):
    def __init__(self) -> None:
        ...
    


class ConnectionAssetNotSupported(WMLClientError, ValueError):
    def __init__(self) -> None:
        ...
    


class InvalidSizeLimit(WMLClientError, ValueError):
    def __init__(self, size_limit, max_size_limit) -> None:
        ...
    


class CorruptedData(WMLClientError, ValueError):
    def __init__(self, reason=...) -> None:
        ...
    


class MissingMandatoryKey(WMLClientError, ValueError):
    def __init__(self, missed_key) -> None:
        ...
    


class MaxSizeOfFileExceeded(WMLClientError, ValueError):
    def __init__(self, size, max_size) -> None:
        ...
    


class NotS3Connection(WMLClientError, ValueError):
    def __init__(self, _internal: bool = ...) -> None:
        ...
    


class InvalidLocationInDataConnection(WMLClientError, ValueError):
    def __init__(self, location) -> None:
        ...
    


class DirectoryHasNoFilename(WMLClientError, ValueError):
    def __init__(self) -> None:
        ...
    


class CannotGetFilename(WMLClientError, ValueError):
    def __init__(self) -> None:
        ...
    


class TokenRemovedDuringClientCopy(WMLClientError):
    def __init__(self) -> None:
        ...
    


class FolderDownloadNotSupported(WMLClientError):
    def __init__(self) -> None:
        ...
    


class NoDocumentsLoaded(WMLClientError):
    def __init__(self, last_exception) -> None:
        ...
    


