"""
This type stub file was generated by pyright.
"""

from abc import ABC
from ibm_watsonx_ai.helpers.connections.connections import DataConnection

class BaseKnowledgeBase(ABC):
    """Base class for knowledge base objects in AutoAI RAG.

    :param name: name of the knowledge base
    :type name: str

    :param description: description of the knowledge base
    :type description: str

    :param knowledge_base_type: type of the knowledge base
    :type knowledge_base_type: str

    :param connection: connection to the knowledge base, must be a connection asset
    :type connection: DataConnection

    :raises: ValueError if connection is not a connection asset
    """
    def __init__(self, name: str, description: str, knowledge_base_type: str, connection: DataConnection) -> None:
        ...
    
    def to_dict(self) -> dict:
        """Convert knowledge base instance to dict.

        :return: dict representing knowledge base
        :rtype: dict

        **Example:**

        .. code-block:: python

            knowledge_base.to_dict()
        """
        ...
    


class DatabaseKnowledgeBase(BaseKnowledgeBase):
    """Reference to SQL DB knowledge.

    :param name: name of the knowledge base
    :type name: str

    :param description: description of the knowledge base
    :type description: str

    :param connection: connection to the knowledge base, must be a connection asset
    :type connection: DataConnection

    :param settings: settings of the database knowledge base
    :type settings: dict, optional

    :raises: ValueError if connection is not a connection asset
    :raises: TypeError if connection location is not a database location

    **Example:**

    .. code-block:: python

        database_knowledge_base = DatabaseKnowledgeBase(
            name="customers",
            description="Database containing information about customers",
            connection=DataConnection(
                connection_asset_id="<connection_id>",
                location=DatabaseLocation(schema_name="customers"),
            ),
            settings={"dialect": "mysql"},
        )

    """
    def __init__(self, name: str, description: str, connection: DataConnection, settings: dict | None = ...) -> None:
        ...
    
    def to_dict(self) -> dict:
        ...
    


class VectorStoreKnowledgeBase(BaseKnowledgeBase):
    """Reference to vector store knowledge.

    :param name: name of the vector store knowledge base
    :type name: str

    :param description: description of the vector store knowledge base
    :type description: str

    :param connection: connection to the vector store knowledge base, must be a connection asset
    :type connection: DataConnection

    :param settings: settings of the vector store knowledge base
    :type settings: dict

    :raises: ValueError if connection is not a connection asset

    **Example:**

    .. code-block:: python

        vector_store_knowledge_base = VectorStoreKnowledgeBase(
            name="customers",
            description="Database containing information about customers",
            connection=DataConnection(connection_asset_id="<connection_id>"),
            settings={
                "index_name": "autoai_rag_id_pipeline_id_index",
                "fields_mapping": [
                    {
                        "role": KnowledgeBaseFieldRole.DENSE_VECTOR_EMBEDDINGS,
                        "field_name": "vector_embeddings",
                    }
                ],
                "embeddings": {"model_id": "ibm/slate-125m-english-rtrvr"},
                "hybrid_ranker": {"sparse_vectors": {"model_id": "BM25"}},
            },
        )

    """
    def __init__(self, name: str, description: str, connection: DataConnection, settings: dict) -> None:
        ...
    
    def to_dict(self) -> dict:
        ...
    


