"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.helpers.connections import AssetLocation, ConnectionAsset, ConnectionAssetLocation, ContainerLocation, DataConnection, DatabaseLocation, FSLocation, NFSConnection, NFSLocation, RemoteFileStorageLocation, S3Connection, S3Location
from ibm_watsonx_ai.helpers.helpers import *

__all__ = ["AssetLocation", "ConnectionAsset", "ConnectionAssetLocation", "ContainerLocation", "DatabaseLocation", "DataConnection", "FSLocation", "NFSConnection", "NFSLocation", "S3Connection", "S3Location", "RemoteFileStorageLocation"]
