"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import TYPE_CHECKING, Union
from IPython.display import HTML

if TYPE_CHECKING:
    ...
__all__ = ["get_credentials_from_config", "pipeline_to_script"]
def get_credentials_from_config(env_name: str, credentials_name: str, config_path: str | Path = ...): # -> Any:
    """Load credentials from the config file.

    ::

        [DEV_LC]

        credentials = {}
        cos_credentials = {}

    :param env_name: name of [ENV] defined in the config file
    :type env_name: str
    :param credentials_name: name of credentials
    :type credentials_name: str
    :param config_path: path to the config file
    :type config_path: str | Path
    :return: loaded credentials
    :rtype: dict

    **Example:**

    .. code-block:: python

        get_credentials_from_config(
            env_name="DEV_LC", credentials_name="credentials"
        )

    """
    ...

def pipeline_to_script(pipeline) -> Union[str, HTML]:
    """Create a python script based on a passed pipeline model. (Python code representation of pipeline model)

    :param pipeline: pipeline model to be written as a script
    :type pipeline: Pipeline or TrainedPipeline

    :return: information about the script location
    :rtype: str or html

    **Example:**

    .. code-block:: python

        pipeline_to_script(pipeline=best_pipeline)
    """
    ...

