"""
This type stub file was generated by pyright.
"""

import pandas as pd
from logging import Logger
from typing import Any
from ibm_watsonx_ai import APIClient
from ibm_watsonx_ai.wml_resource import WMLResource

def get_status(asked_object: Any) -> tuple[str, dict, dict]:
    ...

def wait_for_run_finish(asked_object: Any, res_name: str, logger: Logger) -> dict:
    ...

class BaseRuns(WMLResource):
    def __init__(self, name: str, client: APIClient, url: str, filter: str | None = ..., limit: int = ...) -> None:
        ...
    
    def __call__(self, *, filter: str | None = ..., limit: int = ...) -> BaseRuns:
        ...
    
    def list(self) -> pd.DataFrame:
        ...
    
    def get_run_details(self, run_id: str | None = ...) -> dict:
        ...
    


