"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ibm_watsonx_ai.foundation_models.ilab.helper import BaseRuns
from ibm_watsonx_ai.helpers.connections import DataConnection
from ibm_watsonx_ai.wml_resource import WMLResource
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class Taxonomy:
    """Class of InstructLab taxonomy."""
    def __init__(self, id: str, api_client: APIClient) -> None:
        ...
    
    def get_details(self) -> dict:
        """Get taxonomy import details

        :return: details of taxonomy import
        :rtype: dict
        """
        ...
    
    def get_taxonomy_import(self) -> TaxonomyImport:
        """Get taxonomy import object

        :return: taxonomy import
        :rtype: TaxonomyImport
        """
        ...
    
    def get_taxonomy_tree(self) -> dict:
        """Get taxonomy import tree

        :return: taxonomy import tree
        :rtype: dict
        """
        ...
    
    def update_taxonomy_tree(self, updated_taxonomy_tree: dict) -> dict:
        """Update taxonomy import tree

        :param updated_taxonomy_tree: taxonomy tree with updated nodes
        :type updated_taxonomy_tree: dict
        """
        ...
    
    def delete(self) -> dict:
        """Delete taxonomy import"""
        ...
    


class TaxonomyImport:
    """Class of InstructLab taxonomy import."""
    id: str
    def __init__(self, name: str, api_client: APIClient) -> None:
        ...
    
    def get_run_details(self) -> dict:
        """Get details of taxonomy import run

        :returns: details of taxonomy import
        :rtype: dict
        """
        ...
    
    def get_run_status(self) -> str:
        """Get status of taxonomy import run

        :returns: status of taxonomy import
        :rtype: str
        """
        ...
    
    def delete_run(self) -> str:
        """Delete taxonomy import run"""
        ...
    
    def cancel_run(self) -> str:
        """Cancel taxonomy import run"""
        ...
    
    def get_taxonomy(self) -> Taxonomy:
        """Get taxonomy object for given taxonomy import

        :returns: taxonomy object
        :rtype: Taxonomy
        """
        ...
    


class TaxonomiesRuns(BaseRuns):
    """Class of InstructLab taxonomy import runs."""
    def __init__(self, api_client: APIClient) -> None:
        ...
    
    def get_taxonomy_import(self, taxonomy_import_id: str) -> TaxonomyImport:
        """Get taxonomy import object by id.

        :param taxonomy_import_id: id of given taxonomy import
        :type taxonomy_import_id: str

        :returns: taxonomy import object
        :rtype: TaxonomyImport
        """
        ...
    


class Taxonomies(WMLResource):
    """Class of InstructLab taxonomy import module."""
    _logger = ...
    def __init__(self, ilab_tuner_name: str, api_client: APIClient) -> None:
        ...
    
    def run_import(self, *, data_reference: DataConnection, name: str | None = ..., background_mode: bool = ...) -> TaxonomyImport:
        """Run a taxonomy import process using `data_reference` with taxonomy Github location to `results_reference location`.

        :param data_reference: reference to github repo where taxonomy is stored
        :type data_reference: DataConnection

        :param background_mode: indicator if the method will run in the background, async or sync
        :type background_mode: bool, optional

        :return: taxonomy import object
        :rtype: TaxonomyImport

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment
            from ibm_watsonx_ai.helpers import DataConnection, GithubLocation

            experiment = TuneExperiment(credentials, ...)
            ilab_tuner = experiment.ilab_tuner(...)

            taxonomy_import = ilab_tuner.taxonomies.run_import(
                name="my_taxonomy",
                data_reference=DataConnection(
                    location=GithubLocation(
                        secret_manager_url="...", secret_id="...", path="."
                    )
                ),
            )
        """
        ...
    
    def runs(self) -> TaxonomiesRuns:
        """Get the historical runs.

        :returns: runs object
        :rtype: TaxonomiesRuns
        """
        ...
    


