"""
This type stub file was generated by pyright.
"""

class FunctionArtifactLoader:
    def load(self, path=...): # -> str:
        ...
    
    def extract_content(self, file_path=...): # -> str:
        ...
    


