"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.libs.repo.mlrepositoryartifact.function_artifact_loader import FunctionArtifactLoader

class FunctionLoader(FunctionArtifactLoader):
    """
        Returns  Generic function instance associated with this function artifact.

        :return: function
        :rtype:
        """
    def function_instance(self): # -> str:
        """
         :return: returns function path
         """
        ...
    
    def download_function(self, path): # -> str:
        """
         :return: returns function path
         """
        ...
    


