"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.libs.repo.mlrepository.artifact_reader import ArtifactReader
from ibm_watsonx_ai.libs.repo.base_constants import *

logger = ...
class GenericFileReader(ArtifactReader):
    def __init__(self, compressed_archive_path) -> None:
        ...
    
    def read(self): # -> BufferedReader[_BufferedReaderStream]:
        ...
    
    def close(self): # -> None:
        ...
    


