"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.libs.repo.mlrepository import WmlLibrariesArtifact

class LibrariesArtifact(WmlLibrariesArtifact):
    """
    Class representing LibrariesArtifact artifact.

    :param str uid: optional, uid which indicate that artifact already exists in repository service
    :param str name: optional, name of artifact
    :param str description: optional, description of artifact
    :param str version: version of libraries
    :param str  platform of libraries
    """
    def __init__(self, library=..., uid=..., name=..., meta_props=...) -> None:
        ...
    
    def reader(self): # -> LibrariesArtifactReader:
        """
        Returns reader used for getting library content.

        :return: reader for LibrariesArtifact.library
        :rtype: LibrariesArtifactReader
        """
        ...
    


