"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.libs.repo.mlrepository.artifact_reader import ArtifactReader

logger = ...
class RuntimesArtifactReader(ArtifactReader):
    def __init__(self, runtimespec_path) -> None:
        ...
    
    def read(self): # -> TextIOWrapper[_WrappedBuffer]:
        ...
    
    def close(self): # -> None:
        ...
    


