"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.libs.repo.mlrepository.artifact_reader import ArtifactReader
from ibm_watsonx_ai.libs.repo.base_constants import *

lib_checker = ...
if lib_checker.installed_libs[SCIKIT]:
    ...
logger = ...
class ScikitPipelineReader(ArtifactReader):
    def __init__(self, scikit_pipeline) -> None:
        ...
    
    def read(self): # -> BufferedReader[_BufferedReaderStream]:
        ...
    
    def close(self): # -> None:
        ...
    


