"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.libs.repo.mlrepository import ModelArtifact
from ibm_watsonx_ai.libs.repo.base_constants import *

lib_checker = ...
if lib_checker.installed_libs[SCIKIT]:
    ...
if lib_checker.installed_libs[XGBOOST]:
    ...
class ScikitPipelineModelArtifact(ModelArtifact):
    """
    Class of model artifacts created with MLRepositoryCLient.

    :param sklearn.pipeline.Pipeline scikit_pipeline_model: Pipeline Model which will be wrapped
    """
    def __init__(self, scikit_pipeline_model, training_features=..., training_target=..., feature_names=..., label_column_names=..., uid=..., name=..., meta_props=...) -> None:
        ...
    
    def pipeline_artifact(self): # -> None:
        """
        Returns None. Pipeline is not implemented for scikit model.
        """
        ...
    
    def reader(self): # -> XGBoostModelReader | ScikitPipelineReader:
        """
        Returns reader used for getting pipeline model content.

        :return: reader for sklearn.pipeline.Pipeline
        :rtype: ScikitPipelineReader
        """
        ...
    


