"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.libs.repo.base_constants import *
from ibm_watsonx_ai.libs.repo.mlrepository import PipelineArtifact

lib_checker = ...
class SparkPipelineArtifact(PipelineArtifact):
    """
    Class of pipeline artifacts created with MLRepositoryCLient.

    :param pyspark.ml.Pipeline ml_pipeline: Pipeline which will be wrapped

    :ivar pyspark.ml.Pipeline ml_pipeline: Pipeline associated with this artifact
    """
    def __init__(self, ml_pipeline, uid=..., name=..., meta_props=...) -> None:
        ...
    
    def pipeline_instance(self): # -> Any:
        ...
    
    def reader(self): # -> SparkPipelineReader:
        """
        Returns reader used for getting pipeline content.

        :return: reader for pyspark.ml.Pipeline
        :rtype: SparkPipelineReader
        """
        ...
    


