"""
This type stub file was generated by pyright.
"""

from .spark_artifact_loader import SparkArtifactLoader

class SparkPipelineModelLoader(SparkArtifactLoader):
    """
        Returns pipeline model instance associated with this model artifact.

        :return: pipeline model
        :rtype: pyspark.ml.PipelineModel
        """
    def model_instance(self):
        ...
    


