"""
This type stub file was generated by pyright.
"""

from .spark_artifact_loader import SparkArtifactLoader

class SparkPipelineLoader(SparkArtifactLoader):
    """
    Returns pipeline instance associated with this pipeline artifact.

    :return: pipeline
    :rtype: pyspark.ml.Pipeline
    """
    def pipeline_instance(self):
        ...
    


