"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.libs.repo.mlrepository.artifact_reader import ArtifactReader
from ibm_watsonx_ai.libs.repo.base_constants import *

lib_checker = ...
logger = ...
class TensorflowPipelineReader(ArtifactReader):
    def __init__(self, tensorflow_pipeline, signature_def_map, tags, assets_collection, legacy_init_op, clear_devices, main_op) -> None:
        ...
    
    def read(self): # -> BufferedReader[_BufferedReaderStream]:
        ...
    
    def close(self): # -> None:
        ...
    


