"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.libs.repo.base_constants import *

lib_checker = ...
class VersionHelper:
    @staticmethod
    def significant(): # -> str:
        ...
    
    @staticmethod
    def getFrameworkVersion(ml_pipeline): # -> str | None:
        ...
    
    @staticmethod
    def pipeline_type(ml_pipeline): # -> Literal['mllib', 'wml']:
        ...
    
    @staticmethod
    def model_type(ml_pipeline_model): # -> Literal['mllib', 'wml']:
        ...
    


class ScikitVersionHelper:
    @staticmethod
    def model_type(scikit_pipeline_model): # -> Literal['scikit-learn']:
        ...
    
    @staticmethod
    def model_version(scikit_pipeline_model): # -> str:
        ...
    


class TensorflowVersionHelper:
    @staticmethod
    def model_type(tensorflow_pipeline_model): # -> Literal['tensorflow']:
        ...
    
    @staticmethod
    def model_version(tensorflow_pipeline_model): # -> str:
        ...
    


class XGBoostVersionHelper:
    @staticmethod
    def model_type(xgboost_model): # -> Literal['xgboost']:
        ...
    
    @staticmethod
    def model_version(xgboost_model): # -> None:
        ...
    


class ScikitModelBinary:
    @staticmethod
    def model_bin_name(): # -> Literal['scikit_model.pkl']:
        ...
    
    @staticmethod
    def bin_ext(): # -> Literal['.pkl']:
        ...
    
    @staticmethod
    def bin_ext_v0(): # -> Literal['.bin']:
        ...
    


class XGBoostModelBinary:
    @staticmethod
    def model_bin_name(): # -> Literal['xgboost_model.pkl']:
        ...
    
    @staticmethod
    def bin_ext(): # -> Literal['.pkl']:
        ...
    


class TensorflowModelBinary:
    @staticmethod
    def bin_ext(): # -> Literal['.pb']:
        ...
    


