"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from ibm_watsonx_ai.foundation_models.base_tuner import BaseTuner
from ibm_watsonx_ai.foundation_models.schema import PeftParameters
from ibm_watsonx_ai.helpers.connections import DataConnection
from pandas import DataFrame
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class FineTuner(BaseTuner):
    id: str | None = ...
    _client: APIClient = ...
    _training_metadata: dict | None = ...
    def __init__(self, name: str, task_id: str, api_client: APIClient, *, description: str | None = ..., base_model: str | None = ..., num_epochs: int | None = ..., learning_rate: float | None = ..., batch_size: int | None = ..., max_seq_length: int | None = ..., accumulate_steps: int | None = ..., verbalizer: str | None = ..., response_template: str | None = ..., gpu: dict | None = ..., peft_parameters: dict | PeftParameters | None = ..., auto_update_model: bool = ..., group_by_name: bool = ..., gradient_checkpointing: bool | None = ...) -> None:
        ...
    
    def run(self, training_data_references: list[DataConnection], training_results_reference: DataConnection | None = ..., background_mode: bool = ..., custom: dict | None = ...) -> dict:
        """Run a fine-tuning process of foundation model on top of the training data referenced by DataConnection.

        :param training_data_references: data storage connection details to inform where training data is stored
        :type training_data_references: list[DataConnection]

        :param training_results_reference: data storage connection details to store pipeline training results
        :type training_results_reference: DataConnection, optional

        :param background_mode: indicator if fit() method will run in background (async) or (sync)
        :type background_mode: bool, optional

        :param custom: user defined properties specified as key-value pairs
        :type custom: dict, optional

        :return: run details
        :rtype: dict

        **Example**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment
            from ibm_watsonx_ai.helpers import DataConnection, S3Location

            experiment = TuneExperiment(credentials, ...)
            fine_tuner = experiment.fine_tuner(...)

            fine_tuner.run(
                training_data_references=[DataConnection(
                    connection_asset_id=connection_id,
                    location=S3Location(
                        bucket='fine_tuning_data',
                        path='ft_train_data.json')
                    )
                )]
                background_mode=False)
        """
        ...
    
    def get_params(self) -> dict:
        """Get configuration parameters of FineTuner.

        :return: FineTuner parameters
        :rtype: dict

        **Example**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            fine_tuner = experiment.fine_tuner(...)

            fine_tuner.get_params()

            # Result:
            #
            # {'base_model': {'model_id': 'bigscience/bloom-560m'},
            #  'name': 'Fine-Tuning of bloom-560m model',
            #  'auto_update_model': False,
            #  'group_by_name': False}
        """
        ...
    
    def get_run_status(self) -> str:
        """Check status/state of initialized Fine-Tuning run if ran in background mode.

        :return: Fine-tuning run status
        :rtype: str

        **Example**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            fine_tuner = experiment.fine_tuner(...)
            fine_tuner.run(...)

            fine_tuner.get_run_details()

            # Result:
            # 'completed'
        """
        ...
    
    def get_run_details(self, include_metrics: bool = ...) -> dict:
        """Get fine-tuning run details.

        :param include_metrics: indicates to include metrics in the training details output
        :type include_metrics: bool, optional

        :return: Fine-tuning details
        :rtype: dict

        **Example**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            fine_tuner = experiment.fine_tuner(...)
            fine_tuner.run(...)

            fine_tuner.get_run_details()
        """
        ...
    
    def plot_learning_curve(self, **kwargs: Any) -> None:
        """Plot learning curves.

        .. note ::
            Available only for Jupyter notebooks.

        **Example**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            fine_tuner = experiment.fine_tuner(...)
            fine_tuner.run(...)

            fine_tuner.plot_learning_curve()
        """
        ...
    
    def summary(self, scoring: str = ...) -> DataFrame:
        ...
    
    def get_model_id(self) -> str:
        """Get model id.

        **Example**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            fine_tuner = experiment.fine_tuner(...)
            fine_tuner.run(...)

            fine_tuner.get_model_id()
        """
        ...
    
    def cancel_run(self, hard_delete: bool = ...) -> None:
        """Cancels or deletes a Fine-Tuning run.

        :param hard_delete: When True then the completed or cancelled fine-tuning run is deleted,
                            if False then the current run is canceled. Default: False
        :type hard_delete: bool, optional
        """
        ...
    
    def get_data_connections(self) -> list[DataConnection]:
        """Create DataConnection objects for further user usage
            (eg. to handle data storage connection).

        :return: list of DataConnections
        :rtype: list['DataConnection']

        **Example**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            fine_tuner = experiment.fine_tuner(...)
            fine_tuner.run(...)

            data_connections = fine_tuner.get_data_connections()
        """
        ...
    
    def get_logs(self) -> str:
        """
        Get logs of a Fine-Tuning training run.

        return: path to saved logs
        :rtype: str

        """
        ...
    


