"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ibm_watsonx_ai.foundation_models.base_tuner import BaseTuner
from ibm_watsonx_ai.helpers.connections import DataConnection
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class ILabTuner(BaseTuner):
    """Class of InstructLab fine tuner."""
    id: str | None = ...
    _client: APIClient = ...
    _training_metadata: dict | None = ...
    def __init__(self, name: str, api_client: APIClient) -> None:
        ...
    
    def run(self, training_data_references: list[DataConnection], training_results_reference: DataConnection | None = ..., background_mode: bool = ...) -> dict:
        """Run an ilab tuning process of a foundation model on top of the training data referenced by DataConnection.

        :param training_data_references: data storage connection details to inform where the training data is stored
        :type training_data_references: list[DataConnection]

        :param training_results_reference: data storage connection details to store pipeline training results
        :type training_results_reference: DataConnection, optional

        :param background_mode: indicator if the fit() method will run in the background, async or sync
        :type background_mode: bool, optional

        :return: run details
        :rtype: dict

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment
            from ibm_watsonx_ai.helpers import DataConnection, GithubLocation

            experiment = TuneExperiment(credentials, ...)
            ilab_tuner = experiment.ilab_tuner(...)

            taxonomy_import = ilab_tuner.taxonomies.run_import(
                name="my_taxonomy",
                data_reference=DataConnection(
                    location=GithubLocation(
                        secret_manager_url="...", secret_id="...", path="."
                    )
                ),
                results_reference=DataConnection(
                    location=ContainerLocation(path=".")
                ),
            )

            taxonomy = taxonomy_import.get_taxonomy()

            sdg = ilab_tuner.synthetic_data.generate(
                name="my_sdg", taxonomy=taxonomy
            )

            ilab_tuner.run(
                training_data_references=[sdg.get_results_reference()],
                training_results_reference=DataConnection(
                    location=ContainerLocation(path="fine_tuning_result")
                ),
            )
        """
        ...
    
    def get_params(self) -> dict:
        """Get configuration parameters of ILabTuner.

        :return: ILabTuner parameters
        :rtype: dict

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            ilab_tuner = experiment.ilab_tuner(...)

            ilab_tuner.get_params()

            # Result:
            #
            # {'name': 'ILab tuning'}
        """
        ...
    
    def get_run_status(self) -> str:
        """Check the status/state of an initialized ilab tuning run if it was run in background mode.

        :return: status of the ILab Tuning run
        :rtype: str

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            ilab_tuner = experiment.ilab_tuner(...)
            ilab_tuner.run(...)

            ilab_tuner.get_run_details()

            # Result:
            # 'completed'
        """
        ...
    
    def get_run_details(self, include_metrics: bool = ...) -> dict:
        """Get details of an ilab tuning run.

        :param include_metrics: indicates to include metrics in the training details output
        :type include_metrics: bool, optional

        :return: details of the ilab tuning
        :rtype: dict

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            ilab_tuner = experiment.ilab_tuner(...)
            ilab_tuner.run(...)

            ilab_tuner.get_run_details()
        """
        ...
    
    def cancel_run(self) -> None:
        """Cancel a ILab Tuning run."""
        ...
    
    def delete_run(self) -> None:
        """Delete a ILab Tuning run."""
        ...
    
    def get_data_connections(self) -> list[DataConnection]:
        """Create DataConnection objects for further usage
            (eg. to handle data storage connection).

        :return: list of DataConnections
        :rtype: list['DataConnection']

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            ilab_tuner = experiment.ilab_tuner(...)
            ilab_tuner.run(...)

            data_connections = ilab_tuner.get_data_connections()
        """
        ...
    


