"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ibm_watsonx_ai.foundation_models.base_tuner import BaseTuner
from ibm_watsonx_ai.helpers.connections import DataConnection
from pandas import DataFrame
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class PromptTuner(BaseTuner):
    id: str | None = ...
    _client: APIClient = ...
    _training_metadata: dict | None = ...
    def __init__(self, name: str, task_id: str, *, description: str | None = ..., base_model: str | None = ..., accumulate_steps: int | None = ..., batch_size: int | None = ..., init_method: str | None = ..., init_text: str | None = ..., learning_rate: float | None = ..., max_input_tokens: int | None = ..., max_output_tokens: int | None = ..., num_epochs: int | None = ..., verbalizer: str | None = ..., tuning_type: str | None = ..., auto_update_model: bool = ..., group_by_name: bool | None = ...) -> None:
        ...
    
    def run(self, training_data_references: list[DataConnection], training_results_reference: DataConnection | None = ..., background_mode: bool = ...) -> dict:
        """Run a prompt tuning process of a foundation model on top of the training data referenced by DataConnection.

        :param training_data_references: data storage connection details to inform where the training data is stored
        :type training_data_references: list[DataConnection]

        :param training_results_reference: data storage connection details to store pipeline training results
        :type training_results_reference: DataConnection, optional

        :param background_mode: indicator if the fit() method will run in the background, async or sync
        :type background_mode: bool, optional

        :return: run details
        :rtype: dict

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment
            from ibm_watsonx_ai.helpers import DataConnection, S3Location

            experiment = TuneExperiment(credentials, ...)
            prompt_tuner = experiment.prompt_tuner(...)

            prompt_tuner.run(
                training_data_references=[DataConnection(
                    connection_asset_id=connection_id,
                    location=S3Location(
                        bucket='prompt_tuning_data',
                        path='pt_train_data.json')
                    )
                )]
                background_mode=False)
        """
        ...
    
    def get_params(self) -> dict:
        """Get configuration parameters of PromptTuner.

        :return: PromptTuner parameters
        :rtype: dict

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            prompt_tuner = experiment.prompt_tuner(...)

            prompt_tuner.get_params()

            # Result:
            #
            # {'base_model': {'name': 'google/flan-t5-xl'},
            #  'task_id': 'summarization',
            #  'name': 'Prompt Tuning of Flan T5 model',
            #  'auto_update_model': False,
            #  'group_by_name': False}
        """
        ...
    
    def get_run_status(self) -> str:
        """Check the status/state of an initialized prompt tuning run if it was run in background mode.

        :return: status of the Prompt Tuning run
        :rtype: str

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            prompt_tuner = experiment.prompt_tuner(...)
            prompt_tuner.run(...)

            prompt_tuner.get_run_details()

            # Result:
            # 'completed'
        """
        ...
    
    def get_run_details(self, include_metrics: bool = ...) -> dict:
        """Get details of a prompt tuning run.

        :param include_metrics: indicates to include metrics in the training details output
        :type include_metrics: bool, optional

        :return: details of the prompt tuning
        :rtype: dict

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            prompt_tuner = experiment.prompt_tuner(...)
            prompt_tuner.run(...)

            prompt_tuner.get_run_details()
        """
        ...
    
    def plot_learning_curve(self) -> None:
        """Plot learning curves.

        .. note ::
            Available only for Jupyter notebooks.

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            prompt_tuner = experiment.prompt_tuner(...)
            prompt_tuner.run(...)

            prompt_tuner.plot_learning_curve()
        """
        ...
    
    def summary(self, scoring: str = ...) -> DataFrame:
        """Print the details of PromptTuner models (prompt-tuned models).

        :param scoring: scoring metric for sorting pipelines,
            when not provided, uses loss one
        :type scoring: string, optional

        :return: computed models and metrics
        :rtype: pandas.DataFrame

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            prompt_tuner = experiment.prompt_tuner(...)
            prompt_tuner.run(...)

            prompt_tuner.summary()

            # Result:
            #                          Enhancements            Base model  ...         loss
            #       Model Name
            # Prompt_tuned_M_1      [prompt_tuning]     google/flan-t5-xl  ...     0.449197
        """
        ...
    
    def get_model_id(self) -> str:
        """Get the model ID.

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            prompt_tuner = experiment.prompt_tuner(...)
            prompt_tuner.run(...)

            prompt_tuner.get_model_id()
        """
        ...
    
    def cancel_run(self, hard_delete: bool = ...) -> None:
        """Cancel or delete a Prompt Tuning run.

        :param hard_delete: if True, the completed or cancelled prompt tuning run is deleted,
                            if False, the current run is canceled. Default: False
        :type hard_delete: bool, optional
        """
        ...
    
    def get_data_connections(self) -> list[DataConnection]:
        """Create DataConnection objects for further usage
            (eg. to handle data storage connection).

        :return: list of DataConnections
        :rtype: list['DataConnection']

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.experiment import TuneExperiment

            experiment = TuneExperiment(credentials, ...)
            prompt_tuner = experiment.prompt_tuner(...)
            prompt_tuner.run(...)

            data_connections = prompt_tuner.get_data_connections()
        """
        ...
    


