"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.wml_client_error import WMLClientError

__all__ = ["WrongDeploymnetType", "ModelTypeNotSupported", "NotAutoAIExperiment", "EnvironmentNotSupported", "BatchJobFailed", "MissingScoringResults", "ModelStoringFailed", "DeploymentNotSupported", "MissingSpace", "PromotionFailed", "ModelPromotionFailed", "ServingNameNotAvailable"]
class WrongDeploymnetType(WMLClientError, ValueError):
    def __init__(self, value_name: str, reason: str | None = ...) -> None:
        ...
    


class ModelTypeNotSupported(WMLClientError, ValueError):
    def __init__(self, value_name: str, reason: str | None = ...) -> None:
        ...
    


class NotAutoAIExperiment(WMLClientError, ValueError):
    def __init__(self, value_name: str, reason: str | None = ...) -> None:
        ...
    


class EnvironmentNotSupported(WMLClientError, ValueError):
    def __init__(self, value_name: str, reason: str | None = ...) -> None:
        ...
    


class BatchJobFailed(WMLClientError, ValueError):
    def __init__(self, value_name: str | None = ..., reason: str | None = ...) -> None:
        ...
    


class MissingScoringResults(WMLClientError, ValueError):
    def __init__(self, value_name: str | None = ..., reason: str | None = ...) -> None:
        ...
    


class ModelStoringFailed(WMLClientError, ValueError):
    def __init__(self, value_name: str | None = ..., reason: str | None = ...) -> None:
        ...
    


class DeploymentNotSupported(WMLClientError, ValueError):
    def __init__(self, value_name: str | None = ..., reason: str | None = ...) -> None:
        ...
    


class MissingSpace(WMLClientError, ValueError):
    def __init__(self, value_name: str | None = ..., reason: str | None = ...) -> None:
        ...
    


class PromotionFailed(WMLClientError, ValueError):
    def __init__(self, project_id: str, space_id: str, promotion_response: dict | None = ..., reason: str | None = ...) -> None:
        ...
    


class ModelPromotionFailed(PromotionFailed):
    def __init__(self, project_id: str, space_id: str, promotion_response: dict | None = ..., reason: str | None = ...) -> None:
        ...
    


class ServingNameNotAvailable(WMLClientError, ValueError):
    def __init__(self, message: str) -> None:
        ...
    


