"""
This type stub file was generated by pyright.
"""

import pandas
from typing import Any, Literal
from ibm_watsonx_ai import APIClient
from ibm_watsonx_ai.wml_resource import WMLResource

class VectorIndexes(WMLResource):
    """Initiate the Vector Indexes class.

    :param api_client: instance of APIClient with default project_id set
    :type api_client: APIClient

    **Example:**

        .. code-block:: python

            vector_indexes = VectorIndexes(api_client=api_client)

    """
    def __init__(self, api_client: APIClient) -> None:
        ...
    
    def create(self, name: str, description: str | None = ..., store: dict | None = ..., settings: dict | None = ..., tags: list[str] | None = ..., sample_questions: list[str] | None = ..., **kwargs: Any) -> dict:
        """
        Creates a new Vector Index Asset.

        :param name: name for vector index asset
        :type name: str

        :param description: optional description for the vector index asset, defaults to None
        :type description: str | None

        :param store: store parameters, defaults to None
        :type store: dict | None, optional

        :param settings: settings of vector index, defaults to None
        :type settings: dict | None, optional

        :param tags: tags attached to the asset, defaults to None
        :type tags: list[str] | None, optional

        :param sample_questions: sample asked questions, defaults to None
        :type sample_questions: list[str] | None, optional

        :param data_assets: IDs of the associated data assets used in the vector index, defaults to None
        :type data_assets: list[str] | None, optional

        :param build: the associated build to process the data for external vector stores, defaults to None
        :type build: dict | None, optional

        :param status: the status of the vector index, defaults to None
        :type status: str | None, optional

        :return: metadata of the created Vector Index Asset
        :rtype: dict

        **Example:**

        .. code-block:: python

            params = dict(
                name="test_sdk_vector_index",
                description="Description",
                settings={
                    "embedding_model_id": "<model_id>",
                    "top_k": 1,
                    "schema_fields": {"text": "text"},
                },
                store={
                    "type": "watsonx.data",
                    "connection_id": "<connection_id>",
                    "index": "<index_name>",
                    "new_index": False,
                    "database": "default",
                },
                tags=["test_tag"],
                sample_questions=["Sample question"],
                status="ready",
            )

            vector_index_details = vector_indexes.create(**params)

        """
        ...
    
    def update(self, index_id: str, name: str | None = ..., description: str | None = ..., store: dict | None = ..., settings: dict | None = ..., tags: list[str] | None = ..., sample_questions: list[str] | None = ..., **kwargs: Any) -> dict:
        """Update a Vector Index Asset with the given id.

        :param index_id: Vector Index ids
        :type index_id: str

        :param name: name for vector index asset, defaults to None
        :type name: str | None

        :param description: optional description for the vector index asset, defaults to None
        :type description: str | None

        :param store: store parameters, defaults to None
        :type store: dict | None, optional

        :param settings: settings of vector index, defaults to None
        :type settings: dict | None, optional

        :param tags: tags attached to the asset, defaults to None
        :type tags: list[str] | None, optional

        :param sample_questions: sample asked questions, defaults to None
        :type sample_questions: list[str] | None, optional

        :param data_assets: IDs of the associated data assets used in the vector index, defaults to None
        :type data_assets: list[str] | None, optional

        :param build: the associated build to process the data for external vector stores, defaults to None
        :type build: dict | None, optional

        :param status: the status of the vector index, defaults to None
        :type status: str | None, optional

        :return: metadata of the created Vector Index Asset
        :rtype: dict

        **Example:**

        .. code-block:: python

            vector_indexes.update(
                index_id, name="new_name", description="new_description"
            )

        """
        ...
    
    def get_details(self, index_id: str) -> dict:
        """Get details of Vector Index Asset with given `index_id`.

        :param index_id: Vector Index id
        :type index_id: str

        :return: details of Vector Index Asset with given index_id
        :rtype: dict

        **Example:**

        .. code-block:: python

            vector_indexes.get_details(index_id)

        """
        ...
    
    def delete(self, index_id: str) -> Literal["SUCCESS"]:
        """Delete a vector index with the given id.

        :param index_id: Vector Index id
        :type index_id: str

        :return: "SUCCESS" if delete successfully
        :rtype: str

        **Example:**

        .. code-block:: python

            vector_indexes.delete(index_id)

        """
        ...
    
    def list(self, *, limit: int | None = ...) -> pandas.DataFrame:
        """List all available Vector Index Assets in the DataFrame format.

        :param limit: limit number of fetched records, defaults to None.
        :type limit: int, optional

        :return: DataFrame of fundamental properties of available Vector Index Assets.
        :rtype: pandas.core.frame.DataFrame

        **Example:**

        .. code-block:: python

            vector_indexes.list(
                limit=5
            )  # list of 5 recently created vector index assets

        """
        ...
    


