"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.foundation_models.prompts.base_prompt import BasePrompt

class BasePromptTemplate(BasePrompt):
    """Base class for Prompt Template Asset."""
    def __init__(self, input_mode: str, name: str | None = ..., model_id: str | None = ..., description: str | None = ..., task_ids: list[str] | None = ..., model_params: dict | None = ..., template_version: str | None = ..., input_text: str | None = ..., input_variables: list | dict[str, dict[str, str]] | None = ...) -> None:
        ...
    
    @property
    def template_version(self) -> str | None:
        ...
    
    @template_version.setter
    def template_version(self, value: str | None) -> None:
        ...
    


