"""
This type stub file was generated by pyright.
"""

from abc import ABC
from typing import TYPE_CHECKING
from .prompt_template import PromptTemplateLock

if TYPE_CHECKING:
    ...
class BasePrompt(ABC):
    """Base class for Prompt Asset."""
    def __init__(self, input_mode: str, name: str | None = ..., model_id: str | None = ..., description: str | None = ..., task_ids: list[str] | None = ..., model_params: dict | None = ..., prompt_version: str | None = ...) -> None:
        ...
    
    @property
    def prompt_id(self) -> str | None:
        ...
    
    @property
    def created_at(self) -> str | None:
        ...
    
    @property
    def lock(self) -> PromptTemplateLock | None:
        ...
    
    @property
    def is_template(self) -> bool | None:
        ...
    
    def __repr__(self) -> str:
        ...
    


