"""
This type stub file was generated by pyright.
"""

from typing import Any, TypeAlias
from ibm_watsonx_ai import APIClient
from ibm_watsonx_ai.foundation_models.embeddings import BaseEmbeddings
from ibm_watsonx_ai.foundation_models.extensions.rag.vector_stores.langchain_vector_store_adapter import LangChainVectorStoreAdapter
from ibm_watsonx_ai.utils.utils import is_lib_installed
from langchain_milvus import Milvus
from langchain_milvus.utils.sparse import BaseSparseEmbedding as LCMilvusBaseSparseEmbedding
from langchain_core.documents import Document
from langchain_core.embeddings import Embeddings as LCEmbeddings

if not is_lib_installed(ext := "langchain-milvus"):
    ...
if not is_lib_installed(ext := "langchain-core"):
    ...
if not is_lib_installed(ext := "pymilvus"):
    ...
logger = ...
EmbeddingType: TypeAlias = BaseEmbeddings | LCEmbeddings | LCMilvusBaseSparseEmbedding
class MilvusVectorStore(LangChainVectorStoreAdapter[Milvus]):
    """MilvusVectorStore vector store client for a RAG pattern.

    Instantiates the vector store connection in the watsonx.ai environment and handles the necessary operations.
    The parameters given by the keyword arguments are used to instantiate the vector store client in their
    particular constructor. Those parameters might be parsed differently.

    :param api_client: api client is required if connecting by connection_id, defaults to None
    :type api_client: APIClient, optional

    :param connection_id: connection asset ID, defaults to None
    :type connection_id: str, optional

    :param vector_store: initialized langchain_milvus vector store, defaults to None
    :type vector_store: langchain_milvus.Milvus, optional

    :param embedding_function: list of dense or sparse embedding function, defaults to None
    :type embedding_function: BaseEmbeddings | LCEmbeddings | LCMilvusBaseSparseEmbedding | list[BaseEmbeddings | LCEmbeddings | LCMilvusBaseSparseEmbedding], optional

    :param collection_name: name of the Milvus vector database collection, defaults to None
    :type collection_name: str, optional

    :param document_name_field: mapping field for document name, defaults to `document_id`
    :type document_name_field: str, optional

    :param chunk_sequence_number_field: mapping field for chunk sequence number, defaults to `sequence_number`
    :type chunk_sequence_number_field: str, optional

    :param text_field: mapping field for text field
    :type text_field: str, optional

    :param kwargs: keyword arguments that will be directly passed to `langchain_milvus.Milvus` constructor
    :type kwargs: Any, optional

    .. note::

        For hybrid search (multi-vector search), if no `ranker_type` is specified, a `weighted` reranker with default weights equal to 1 is used.
        For more details, see the `langchain_milvus` documentation https://python.langchain.com/docs/integrations/vectorstores/milvus/#hybrid-search.

    **Example:**

    To connect, provide the connection asset ID.
    You can use custom embeddings to add and search documents.

    .. code-block:: python

        from ibm_watsonx_ai import APIClient, Credentials
        from ibm_watsonx_ai.foundation_models.extensions.rag.vector_stores import (
            MilvusVectorStore,
        )
        from ibm_watsonx_ai.foundation_models.embeddings import Embeddings

        credentials = Credentials(
            api_key=IAM_API_KEY, url="https://us-south.ml.cloud.ibm.com"
        )

        api_client = APIClient(credentials)

        embedding = Embeddings(
            model_id=EmbeddingTypes.IBM_SLATE_30M_ENG, api_client=api_client
        )

        vector_store = MilvusVectorStore(
            api_client,
            connection_id="***",
            collection_name="my_test_collection",
            embedding_function=embedding,
        )

        vector_store.add_documents(
            [
                {
                    "content": "document one content",
                    "metadata": {"url": "ibm.com"},
                },
                {
                    "content": "document two content",
                    "metadata": {"url": "ibm.com"},
                },
            ]
        )

        vector_store.search("one", k=1)

    .. note::
        To use hybrid search you need to pass several embedding function.

    Example with weighted ranker.

    .. code-block:: python

        from ibm_watsonx_ai import APIClient, Credentials
        from ibm_watsonx_ai.foundation_models.extensions.rag.vector_stores import (
            MilvusVectorStore,
            MilvusSpladeEmbeddingFunction
        )

        credentials = Credentials(api_key=IAM_API_KEY, url="https://us-south.ml.cloud.ibm.com")

        api_client = APIClient(credentials)

        dense_embedding = Embeddings(
                 model_id=EmbeddingTypes.IBM_SLATE_30M_ENG,
                 api_client=api_client
                 )

        splade_func = MilvusSpladeEmbeddingFunction(model_name="naver/splade-cocondenser-selfdistil", device="cpu")

        vector_store = MilvusVectorStore(
            api_client,
            connection_id=es_connection_id,
            collection_name="my_test_collection",
            embedding_function=[dense_embedding, splade_func]
        )

        vector_store.add_documents(
            [
                {"content": "document one content", "metadata": {"url": "ibm.com"}},
                {"content": "document two content", "metadata": {"url": "ibm.com"}},
            ]
        )

        # `weighted` ranker
        vector_store.search("one", k=1, ranker_type="weighted", ranker_params={"weights": [0.0, 1.0])

        # `rrf` ranker
        vector_store.search("one", k=1, ranker_type="rrf", ranker_params={"k": 50)


    .. note::
        Please note that since Milvus v2.5 a full-text search can be used https://milvus.io/blog/introduce-milvus-2-5-full-text-search-powerful-metadata-filtering-and-more.md

    .. code-block:: python

        from ibm_watsonx_ai import APIClient, Credentials
        from ibm_watsonx_ai.foundation_models.extensions.rag.vector_stores import (
            MilvusVectorStore,
            MilvusBM25BuiltinFunction(
        )

        credentials = Credentials(api_key=IAM_API_KEY, url="https://us-south.ml.cloud.ibm.com")

        api_client = APIClient(credentials)

        dense_embedding = Embeddings(
                 model_id=EmbeddingTypes.IBM_SLATE_30M_ENG,
                 api_client=api_client
                 )
        bm25_builtin_func = MilvusBM25BuiltinFunction()

        vector_store = MilvusVectorStore(
            api_client,
            connection_id=es_connection_id,
            collection_name="my_test_collection",
            embedding_function=dense_embedding,
            builtin_function=bm25_builtin_func,
        )

        vector_store.add_documents(
            [
                {"content": "document one content", "metadata": {"url": "ibm.com"}},
                {"content": "document two content", "metadata": {"url": "ibm.com"}},
            ]
        )

        # `weighted` ranker
        vector_store.search("one", k=1, ranker_type="weighted", ranker_params={"weights": [0.0, 1.0])

        # `rrf` ranker
        vector_store.search("one", k=1, ranker_type="rrf", ranker_params={"k": 50)


    """
    def __init__(self, api_client: APIClient | None = ..., *, connection_id: str | None = ..., vector_store: Milvus | None = ..., embedding_function: EmbeddingType | list[EmbeddingType] | None = ..., collection_name: str | None = ..., document_name_field: str = ..., chunk_sequence_number_field: str = ..., text_field: str | None = ..., **kwargs: Any) -> None:
        ...
    
    def get_client(self) -> Milvus:
        """Get langchain_milvus.Milvus instance."""
        ...
    
    def clear(self) -> None:
        """
        Clear collection by removing all records.
        """
        ...
    
    def count(self) -> int:
        """
        Count number of records in collection.
        """
        ...
    
    def add_documents(self, content: list[str] | list[dict] | list[Document], **kwargs: Any) -> list[str]:
        """
        Embed documents and add to the vectorstore.

        :param content: Documents to add to the vectorstore.
        :type content: list[str] | list[dict] | list[langchain_core.documents.Document]

        :return: List of IDs of the added texts.
        :rtype: list[str]
        """
        ...
    
    async def add_documents_async(self, content: list[str] | list[dict] | list[Document], **kwargs: Any) -> list[str]:
        """
        Embed documents and add to the vectorstore in asynchronous manner.

        :param content: Documents to add to the vectorstore.
        :type content: list[str] | list[dict] | list[langchain_core.documents.Document]

        :return: List of IDs of the added texts.
        :rtype: list[str]
        """
        ...
    
    def to_dict(self) -> dict:
        """Serialize ``MilvusVectorStore`` into a dict that allows reconstruction using the ``from_dict`` class method.

        :return: dict for the from_dict initialization
        :rtype: dict

        :raises VectorStoreSerializationError: when instance is not serializable
        """
        ...
    
    @classmethod
    def from_dict(cls, api_client: APIClient | None = ..., data: dict | None = ...) -> MilvusVectorStore:
        """Creates ``MilvusVectorStore`` using only a primitive data type dict.

        :param api_client: initialised APIClient used in vector store constructor, defaults to None
        :type api_client: APIClient, optional

        :param data: dict in schema like the ``to_dict()`` method
        :type data: dict

        :return: reconstructed MilvusVectorStore
        :rtype: MilvusVectorStore
        """
        ...
    


