"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai import APIClient, Credentials
from ibm_watsonx_ai.wml_resource import WMLResource

class Gateway(WMLResource):
    """Model Gateway class."""
    def __init__(self, *, credentials: Credentials | None = ..., verify: bool | str | None = ..., api_client: APIClient | None = ...) -> None:
        class _ChatCompletions(WMLResource):
            ...
        
        
        class _Chat:
            ...
        
        
        class _Completions(WMLResource):
            ...
        
        
        class _Embeddings(WMLResource):
            ...
        
        
    


