"""
This type stub file was generated by pyright.
"""

import pandas as pd
from ibm_watsonx_ai import APIClient
from ibm_watsonx_ai.wml_resource import WMLResource

class Policies(WMLResource):
    """Model Gateway policies class."""
    def __init__(self, api_client: APIClient) -> None:
        ...
    
    def create(self, action: str, resource: str, subject: str, effect: str | None = ...) -> None:
        """Create policy.

        :param action: action for policy
        :type action: str

        :param resource: resource for policy
        :type resource: str

        :param subject: subject for policy
        :type subject: str

        :param effect: effect for policy
        :type effect: str, optional
        """
        ...
    
    def delete(self, policy_id: str) -> str:
        """Delete policy.

        :param policy_id: ID of policy
        :type policy_id: str

        :return: status ("SUCCESS" if succeeded)
        :rtype: str
        """
        ...
    
    def get_details(self) -> dict:
        """Get policies details.

        :returns: policies details
        :rtype: dict
        """
        ...
    
    def list(self) -> pd.DataFrame:
        """List policies.

        :returns: dataframe with policies details
        :rtype: pandas.DataFrame
        """
        ...
    
    @staticmethod
    def get_id(policy_details: dict) -> str:
        """Get policy ID from policy details.

        :param policy_details: details of the policy for asset registered in Model Gateway
        :type policy_details: dict

        :returns: unique policy ID
        :rtype: str
        """
        ...
    


