"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import TypedDict
from ibm_watsonx_ai import APIClient
from ibm_watsonx_ai.wml_resource import WMLResource

class RateLimitSettings(TypedDict):
    """
    Model Gateway rate limit settings.

    :param amount: amount is the number of tokens refilled into the bucket each interval
    :type amount: int

    :param capacity: capacity is the maximum number of tokens (requests) the bucket can hold
    :type capacity: int

    :param duration: duration is the refill interval, formatted as a Go duration string
        (for more information please see: https://pkg.go.dev/time#ParseDuration)
    :type duration: str
    """
    amount: int
    capacity: int
    duration: str
    ...


class RateLimits(WMLResource):
    """Model Gateway rate limits class."""
    def __init__(self, api_client: APIClient) -> None:
        ...
    
    def create_for_tenant(self, *, request: RateLimitSettings | None = ..., token: RateLimitSettings | None = ...) -> dict:
        """Create rate limit for tenant in Model Gateway.

        :param request: request rate limiting settings
        :type request: RateLimitSettings, optional

        :param token: token rate limiting settings
        :type token: RateLimitSettings, optional

        :returns: rate limit details
        :rtype: dict
        """
        ...
    
    def create_for_provider(self, provider_id: str, *, request: RateLimitSettings | None = ..., token: RateLimitSettings | None = ...) -> dict:
        """Create rate limit for provider in Model Gateway.

        :param provider_id: ID of the Model Gateway provider
        :type provider_id: str

        :param request: request rate limiting settings
        :type request: RateLimitSettings, optional

        :param token: token rate limiting settings
        :type token: RateLimitSettings, optional

        :returns: rate limit details
        :rtype: dict
        """
        ...
    
    def create_for_model(self, model_id: str, *, request: RateLimitSettings | None = ..., token: RateLimitSettings | None = ...) -> dict:
        """Create rate limit for model in Model Gateway.

        :param model_id: ID of the Model Gateway model
        :type model_id: str

        :param request: request rate limiting settings
        :type request: RateLimitSettings, optional

        :param token: token rate limiting settings
        :type token: RateLimitSettings, optional

        :returns: rate limit details
        :rtype: dict
        """
        ...
    
    def update_for_tenant(self, rate_limit_id: str, *, request: RateLimitSettings | None = ..., token: RateLimitSettings | None = ...) -> dict:
        """Update rate limit for tenant in Model Gateway.

        :param rate_limit_id: ID of the rate limit
        :type rate_limit_id: str

        :param request: request rate limiting settings
        :type request: RateLimitSettings, optional

        :param token: token rate limiting settings
        :type token: RateLimitSettings, optional

        :returns: rate limit details
        :rtype: dict
        """
        ...
    
    def update_for_provider(self, rate_limit_id: str, provider_id: str, *, request: RateLimitSettings | None = ..., token: RateLimitSettings | None = ...) -> dict:
        """Update rate limit for provider in Model Gateway.

        :param rate_limit_id: ID of the rate limit
        :type rate_limit_id: str

        :param provider_id: ID of the Model Gateway provider
        :type provider_id: str

        :param request: request rate limiting settings
        :type request: RateLimitSettings, optional

        :param token: token rate limiting settings
        :type token: RateLimitSettings, optional

        :returns: rate limit details
        :rtype: dict
        """
        ...
    
    def update_for_model(self, rate_limit_id: str, model_id: str, *, request: RateLimitSettings | None = ..., token: RateLimitSettings | None = ...) -> dict:
        """Update rate limit for model in Model Gateway.

        :param rate_limit_id: ID of the rate limit
        :type rate_limit_id: str

        :param model_id: ID of the Model Gateway model
        :type model_id: str

        :param request: request rate limiting settings
        :type request: RateLimitSettings, optional

        :param token: token rate limiting settings
        :type token: RateLimitSettings, optional

        :returns: rate limit details
        :rtype: dict
        """
        ...
    
    def get_details(self, *, rate_limit_id: str | None = ...) -> dict:
        """Get details of rate limits.
        If ``rate_limit_id`` is specified, returns details of that rate limit.

        :param rate_limit_id: ID of the rate limit
        :type rate_limit_id: str, optional

        :returns: details of rate limits or rate limit if ``rate_limit_id`` is specified
        :rtype: dict
        """
        ...
    
    def list(self) -> pd.DataFrame:
        """List rate limits registered in Model Gateway.

        :returns: dataframe containing list results
        :rtype: pandas.DataFrame
        """
        ...
    
    def delete(self, rate_limit_id: str) -> str:
        """Delete rate limit from Model Gateway.

        :param rate_limit_id: ID of the rate limit
        :type rate_limit_id: str

        :return: status "SUCCESS" if deletion is successful
        :rtype: Literal["SUCCESS"]
        :raises: ApiRequestFailure if deletion failed
        """
        ...
    
    @staticmethod
    def get_id(rate_limit_details: dict) -> str:
        """Get rate limit ID from rate limit details.

        :param rate_limit_details: details of the rate limit
        :type rate_limit_details: dict

        :returns: ID of the rate limit
        :rtype: str
        """
        ...
    


