"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.foundation_models.embeddings.base_embeddings import BaseEmbeddings

class SentenceTransformerEmbeddings(BaseEmbeddings):
    """Embedding that utilizes sentence transformer, compatibile with ``RAGPattern``.

    Requires sentence_transformers to be installed by pip.

    .. deprecated:: 1.3.2

        This class has been deprecated since version 1.3.2 and is retained only for backward compatibility. It may be removed in a future release.

    :param model_name: name of the model from Huggingface
    :type model_name: str

    :param model_params: parameters given to the ``SentenceTransformer`` model constructor, defaults to None
    :type model_params: dict, optional

    :param encode_params: parameters given to the ``SentenceTransformer`` model ``encode`` method, defaults to None
    :type encode_params: dict, optional
    """
    def __init__(self, model_name: str, model_params: dict | None = ..., encode_params: dict | None = ...) -> None:
        ...
    
    def embed_documents(self, texts: list[str]) -> list[list[float]]:
        ...
    
    def embed_query(self, text: str) -> list[float]:
        ...
    
    def to_dict(self) -> dict:
        ...
    


