"""
This type stub file was generated by pyright.
"""

from importlib.metadata import version
from typing import TYPE_CHECKING
from .client import APIClient
from .credentials import Credentials
from .utils.enums import AssetDuplicateAction

if TYPE_CHECKING:
    ...
package_name = ...
__version__ = ...
__all__ = ["APIClient", "AssetDuplicateAction", "Credentials", "package_name"]
def __getattr__(name: str): # -> type[APIClient] | type[Credentials] | type[AssetDuplicateAction]:
    ...

