"""
This type stub file was generated by pyright.
"""

import httpx
from pathlib import Path
from typing import Any, TYPE_CHECKING, TypeAlias
from ibm_watsonx_ai.credentials import Credentials
from ibm_watsonx_ai.utils.utils import HttpClientConfig

"""
.. module:: APIClient
   :platform: Unix, Windows
   :synopsis: IBM watsonx.ai API Client.

.. moduleauthor:: IBM
"""
if TYPE_CHECKING:
    ...
RequestsLikeType: TypeAlias = Any
class APIClient:
    """The main class of ibm_watsonx_ai. The very heart of the module. APIClient contains objects that manage the service resources.

    To explore how to use APIClient, refer to:

    - :ref:`Setup<setup>` - to check correct initialization of APIClient for a specific environment.
    - :ref:`Core<core>` - to explore core properties of an APIClient object.

    :param url: URL of the service
    :type url: str

    :param credentials: credentials used to connect with the service
    :type credentials: Credentials

    :param project_id: ID of the project that is used
    :type project_id: str, optional

    :param space_id: ID of deployment space that is used
    :type space_id: str, optional

    :param verify: certificate verification flag, deprecated, use Credentials(verify=...) to set `verify`
    :type verify: bool | str | Path, optional

    :param httpx_client: A customizable `httpx.Client` for ModelInference, Embeddings and methods related to the deployments management and scoring.
        The `httpx.Client` is used to improve performance across deployments, foundation models, and embeddings. This parameter accepts two types of input:

        - A direct instance of `httpx.Client()`
        - A set of parameters provided via the `HttpClientConfig` class

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.utils.utils import HttpClientConfig

            limits = httpx.Limits(max_connections=5)
            timeout = httpx.Timeout(7)
            http_config = HttpClientConfig(timeout=timeout, limits=limits)

        If not provided, a default instance of `httpx.Client` is created.

        .. note::
            If you need to adjust timeouts or limits, using ``HttpClientConfig`` is the recommended approach.
            When the ``proxies`` parameter is provided in credentials, ``httpx.Client`` will use these proxies.
            However, if you want to create a separate ``httpx.Client``, all parameters must be provided by the user.
    :type httpx_client: httpx.Client | HttpClientConfig, optional

    :param async_httpx_client: A customizable `httpx.AsyncClient` for ModelInference. The `httpx.AsyncClient` is used to improve performance of foundation models inference. This parameter accepts two types of input:

        - A direct instance of `httpx.AsyncClient`
        - A set of parameters provided via the `HttpClientConfig` class

        **Example:**

        .. code-block:: python

            from ibm_watsonx_ai.utils.utils import HttpClientConfig

            limits = httpx.Limits(max_connections=5)
            timeout = httpx.Timeout(7)
            http_config = HttpClientConfig(timeout=timeout, limits=limits)

        If not provided, a default instance of `httpx.AsyncClient` is created.

        .. note::
            If you need to adjust timeouts or limits, using ``HttpClientConfig`` is the recommended approach.
            When the ``proxies`` parameter is provided in credentials, ``httpx.Client`` will use these proxies.
            However, if you want to create a separate ``httpx.Client``, all parameters must be provided by the user.

    :type async_httpx_client: httpx.AsyncClient | HttpClientConfig, optional

    **Example:**

    .. code-block:: python

        from ibm_watsonx_ai import APIClient, Credentials

        credentials = Credentials(url="<url>", api_key=IAM_API_KEY)

        client = APIClient(credentials, space_id="<space_id>")

        client.models.list()
        client.deployments.get_details()

        client.set.default_project("<project_id>")

        ...

    """
    version: str | None = ...
    _internal: bool = ...
    PLATFORM_URLS_MAP = ...
    def __init__(self, credentials: Credentials | dict[str, str] | None = ..., project_id: str | None = ..., space_id: str | None = ..., verify: str | Path | bool | None = ..., httpx_client: httpx.Client | HttpClientConfig = ..., async_httpx_client: (httpx.AsyncClient | HttpClientConfig) = ..., **kwargs: Any) -> None:
        ...
    
    def get_copy(self) -> APIClient:
        """Prepares clean copy of APIClient. The clean copy contains no token, password, api key data. It is used
        in AI services scenarios, when the client is used in deployed code, and can be reused between users.

        The copy needs to be set with current user token in the inner function of AI service.

        :returns: APIClient which is 2-level copy of the current one, without user secrets
        :rtype: APIClient

        **Example:**

        .. code-block:: python

            def deployable_ai_service(context, params={"k1": "v1"}, **kwargs):
                # imports
                from ibm_watsonx_ai import Credentials, APIClient
                from ibm_watsonx_ai.foundation_models import ModelInference

                task_token = context.generate_token()

                outer_context = context

                client = APIClient(
                    Credentials(
                        url="https://us-south.ml.cloud.ibm.com", token=task_token
                    )
                )

                # operations with client

                def generate(context):
                    user_client = client.get_copy()
                    user_client.set_token(context.generate_token())

                    # operations with user_client

                    return {"body": response_body}

                return generate


            stored_ai_service_details = client._ai_services.store(
                deployable_ai_service, meta_props
            )

        """
        ...
    
    @property
    def wml_credentials(self) -> dict[str, str]:
        ...
    
    @wml_credentials.setter
    def wml_credentials(self, value: dict[str, str]) -> None:
        ...
    
    @property
    def wml_token(self) -> str | None:
        ...
    
    @wml_token.setter
    def wml_token(self, value: str) -> None:
        ...
    
    @property
    def token(self) -> str:
        ...
    
    @token.setter
    def token(self, value: str) -> None:
        ...
    
    @property
    def proceed(self) -> bool:
        ...
    
    @property
    def project_type(self) -> str | None:
        ...
    
    @project_type.setter
    def project_type(self, value: str) -> None:
        ...
    
    @property
    def httpx_client(self) -> httpx.Client:
        ...
    
    @httpx_client.setter
    def httpx_client(self, value: httpx.Client): # -> None:
        ...
    
    @property
    def async_httpx_client(self) -> httpx.AsyncClient:
        ...
    
    @async_httpx_client.setter
    def async_httpx_client(self, value: httpx.AsyncClient): # -> None:
        ...
    
    def get_headers(self, content_type: str | None = ..., include_user_agent: bool = ...) -> dict:
        """Get HTTP headers used during requests.

        :param content_type: value for `Content-Type` header, defaults to `application/json`
        :type name: str, optional

        :param include_user_agent: whether the result should include `User-Agent` header, defaults to `False`
        :type name: bool, optional

        :return: headers used during requests
        :rtype: dict
        """
        ...
    
    def set_token(self, token: str) -> None:
        """
        Method which allows refresh/set new User Authorization Token.

        .. note::
            * Using this function will cause that token will not be automatically refreshed anymore, if `password` or `apikey` were passed.
              The user needs to take care of token refresh using `set_token` function from that point in time until they finish using the client instance.
            * If ``trusted_profile_id`` and ``token`` were passed in credentials,
              the ``trusted_profile_id`` will be used for generating a new trusted profile token based on token passed to this method
              until the client lifecycle. The generating process takes place when retrieving a token.

        :param token: User Authorization Token
        :type token: str

        **Examples**

        .. code-block:: python

            client.set_token("<USER AUTHORIZATION TOKEN>")

        """
        ...
    
    def set_headers(self, headers: dict) -> None:
        """
        Method which allows refresh/set new User Request Headers.

        :param headers: User Request Headers
        :type headers: dict

        **Examples**

        .. code-block:: python

            headers = {
                "Authorization": "Bearer <USER AUTHORIZATION TOKEN>",
                "User-Agent": "ibm-watsonx-ai/1.0.1 (lang=python; arch=x86_64; os=darwin; python.version=3.10.13)",
                "Content-Type": "application/json",
            }

            client.set_headers(headers)

        """
        ...
    


