"""
This type stub file was generated by pyright.
"""

import pandas
from pathlib import Path
from typing import TYPE_CHECKING
from ibm_watsonx_ai.wml_resource import WMLResource
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class Export(WMLResource):
    def __init__(self, client: APIClient) -> None:
        ...
    
    def start(self, meta_props: dict[str, str | bool | list], space_id: str | None = ..., project_id: str | None = ...) -> dict:
        """Start the export. You must provide the space_id or the project_id.
        ALL_ASSETS is by default False. You don't need to provide it unless it is set to True.
        You must provide one of the following in the meta_props: ALL_ASSETS, ASSET_TYPES, or ASSET_IDS. Only one of these can be
        provided.

        In the `meta_props`:

        ALL_ASSETS is a boolean. When set to True, it exports all assets in the given space.
        ASSET_IDS is an array that contains the list of assets IDs to be exported.
        ASSET_TYPES is used to provide the asset types to be exported. All assets of that asset type will be exported.

                Eg: wml_model, wml_model_definition, wml_pipeline, wml_function, wml_experiment,
                software_specification, hardware_specification, package_extension, script

        :param meta_props: metadata,
            to see available meta names use ``client.export_assets.ConfigurationMetaNames.get()``
        :type meta_props: dict
        :param space_id: space identifier
        :type space_id: str, optional
        :param project_id: project identifier
        :type project: str, optional

        :return: Response json
        :rtype: dict

        **Example:**

        .. code-block:: python

            metadata = {
                client.export_assets.ConfigurationMetaNames.NAME: "export_model",
                client.export_assets.ConfigurationMetaNames.ASSET_IDS: [
                    "13a53931-a8c0-4c2f-8319-c793155e7517",
                    "13a53931-a8c0-4c2f-8319-c793155e7518",
                ],
            }

            details = client.export_assets.start(
                meta_props=metadata, space_id="98a53931-a8c0-4c2f-8319-c793155e4598"
            )

        .. code-block:: python

            metadata = {
                client.export_assets.ConfigurationMetaNames.NAME: "export_model",
                client.export_assets.ConfigurationMetaNames.ASSET_TYPES: [
                    "wml_model"
                ],
            }

            details = client.export_assets.start(
                meta_props=metadata, space_id="98a53931-a8c0-4c2f-8319-c793155e4598"
            )

        .. code-block:: python

            metadata = {
                client.export_assets.ConfigurationMetaNames.NAME: "export_model",
                client.export_assets.ConfigurationMetaNames.ALL_ASSETS: True,
            }

            details = client.export_assets.start(
                meta_props=metadata, space_id="98a53931-a8c0-4c2f-8319-c793155e4598"
            )

        """
        ...
    
    def cancel(self, export_id: str, space_id: str | None = ..., project_id: str | None = ...) -> str:
        """Cancel an export job. `space_id` or `project_id` has to be provided.

        .. note::
            To delete an `export_id` job, use ``delete()`` API.

        :param export_id: export job identifier
        :type export_id: str
        :param space_id: space identifier
        :type space_id: str, optional
        :param project_id: project identifier
        :type project_id: str, optional

        :returns: status ("SUCCESS" or "FAILED")
        :rtype: str

        **Example:**

        .. code-block:: python

            client.export_assets.cancel(
                export_id="6213cf1-252f-424b-b52d-5cdd9814956c",
                space_id="3421cf1-252f-424b-b52d-5cdd981495fe",
            )
        """
        ...
    
    def delete(self, export_id: str, space_id: str | None = ..., project_id: str | None = ...) -> str:
        """Delete the given `export_id` job. `space_id` or `project_id` has to be provided.

        :param export_id: export job identifier
        :type export_id: str
        :param space_id: space identifier
        :type space_id: str, optional
        :param project_id: project identifier
        :type project_id: str, optional

        :return: status ("SUCCESS" or "FAILED")
        :rtype: str

        **Example:**

        .. code-block:: python

            client.export_assets.delete(
                export_id="6213cf1-252f-424b-b52d-5cdd9814956c",
                space_id="98a53931-a8c0-4c2f-8319-c793155e4598",
            )
        """
        ...
    
    def get_details(self, export_id: str | None = ..., space_id: str | None = ..., project_id: str | None = ..., limit: int | None = ..., asynchronous: bool = ..., get_all: bool = ...) -> dict:
        """Get metadata of a given export job. If no `export_id` is specified, all export metadata is returned.

        :param export_id: export job identifier
        :type export_id: str, optional
        :param space_id: space identifier
        :type space_id: str, optional
        :param project_id: project identifier
        :type project_id: str, optional
        :param limit: limit number of fetched records
        :type limit: int, optional
        :param asynchronous: if `True`, it will work as a generator
        :type asynchronous: bool, optional
        :param get_all: if `True`, it will get all entries in 'limited' chunks
        :type get_all: bool, optional

        :return: export metadata
        :rtype: dict (if export_id is not None) or {"resources": [dict]} (if export_id is None)

        **Example:**

        .. code-block:: python

            details = client.export_assets.get_details(
                export_id, space_id="98a53931-a8c0-4c2f-8319-c793155e4598"
            )
            details = client.export_assets.get_details()
            details = client.export_assets.get_details(limit=100)
            details = client.export_assets.get_details(limit=100, get_all=True)
            details = []
            for entry in client.export_assets.get_details(
                limit=100, asynchronous=True, get_all=True
            ):
                details.extend(entry)

        """
        ...
    
    def list(self, space_id: str | None = ..., project_id: str | None = ..., limit: int | None = ...) -> pandas.DataFrame:
        """Return export jobs in a table format.

        :param space_id: space identifier
        :type space_id: str, optional
        :param project_id: project identifier
        :type project_id: str, optional
        :param limit: limit number of fetched records
        :type limit: int, optional

        :return: pandas.DataFrame with listed connections
        :rtype: pandas.DataFrame

        **Example:**

        .. code-block:: python

            client.export_assets.list()
        """
        ...
    
    @staticmethod
    def get_id(export_details: dict) -> str:
        """Get the ID of the export job from export details.

        :param export_details: metadata of the export job
        :type export_details: dict

        :return: ID of the export job
        :rtype: str

        **Example:**

        .. code-block:: python

            id = client.export_assets.get_id(export_details)
        """
        ...
    
    def get_exported_content(self, export_id: str, space_id: str | None = ..., project_id: str | None = ..., file_path: str | Path | None = ...) -> str:
        """Get the exported content as a zip file.

        :param export_id: export job identifier
        :type export_id: str
        :param space_id: space identifier
        :type space_id: str, optional
        :param project_id: project identifier
        :type project_id: str, optional
        :param file_path: name of local file to create, this should be absolute path of the file
            and the file shouldn't exist
        :type file_path: str | Path, optional


        :return: path to the downloaded function content
        :rtype: str

        **Example:**

        .. code-block:: python

            client.export_assets.get_exported_content(
                export_id,
                space_id="98a53931-a8c0-4c2f-8319-c793155e4598",
                file_path="/home/user/my_exported_content.zip",
            )
        """
        ...
    


