"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ibm_watsonx_ai.wml_resource import WMLResource
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class Factsheets(WMLResource):
    """Link WML Model to Model Entry."""
    cloud_platform_spaces: bool = ...
    icp_platform_spaces: bool = ...
    def __init__(self, client: APIClient) -> None:
        ...
    
    def register_model_entry(self, model_id: str, meta_props: dict[str, str], catalog_id: str | None = ...) -> dict:
        """Link WML Model to Model Entry

        :param model_id: ID of the published model/asset
        :type model_id: str

        :param meta_props: metaprops, to see the available list of meta names use:

            .. code-block:: python

                client.factsheets.ConfigurationMetaNames.get()

        :type meta_props: dict[str, str]

        :param catalog_id: catalog ID where you want to register model
        :type catalog_id: str, optional

        :return: metadata of the registration
        :rtype: dict

        **Example:**

        .. code-block:: python

            meta_props = {
                client.factsheets.ConfigurationMetaNames.ASSET_ID: "83a53931-a8c0-4c2f-8319-c793155e7517"
            }

            registration_details = client.factsheets.register_model_entry(
                model_id, catalog_id, meta_props
            )

        or

        .. code-block:: python

            meta_props = {
                client.factsheets.ConfigurationMetaNames.NAME: "New model entry",
                client.factsheets.ConfigurationMetaNames.DESCRIPTION: "New model entry",
            }

            registration_details = client.factsheets.register_model_entry(
                model_id, meta_props
            )

        """
        ...
    
    def list_model_entries(self, catalog_id: str | None = ...) -> dict:
        """Return all WKC Model Entry assets for a catalog.

        :param catalog_id: catalog ID where you want to register model. If no catalog_id is provided, WKC Model Entry assets from all catalogs are listed.
        :type catalog_id: str, optional

        :return: all WKC Model Entry assets for a catalog
        :rtype: dict

        **Example:**

        .. code-block:: python

            model_entries = client.factsheets.list_model_entries(catalog_id)

        """
        ...
    
    def unregister_model_entry(self, asset_id: str, catalog_id: str | None = ...) -> None:
        """Unregister WKC Model Entry

        :param asset_id: ID of the WKC model entry
        :type asset_id: str

        :param catalog_id: catalog ID where the asset is stored, when not provided,
            default client space or project will be taken
        :type catalog_id: str, optional

        **Example:**

        .. code-block:: python

            model_entries = client.factsheets.unregister_model_entry(
                asset_id="83a53931-a8c0-4c2f-8319-c793155e7517",
                catalog_id="34553931-a8c0-4c2f-8319-c793155e7517",
            )

        or

        .. code-block:: python

            client.set.default_space("98f53931-a8c0-4c2f-8319-c793155e7517")
            model_entries = client.factsheets.unregister_model_entry(
                asset_id="83a53931-a8c0-4c2f-8319-c793155e7517"
            )

        """
        ...
    


