"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.wml_client_error import WMLClientError

class BothValuesAndRangePassed(WMLClientError):
    def __init__(self) -> None:
        ...
    


class EmptyValues(WMLClientError):
    def __init__(self) -> None:
        ...
    


class InconsistentValuesTypes(WMLClientError):
    def __init__(self, types: list[type]) -> None:
        ...
    


class MissingElementOfRange(WMLClientError):
    def __init__(self, el: str) -> None:
        ...
    


def HPOParameter(name: str, values: list[str] | list[float] | None = ..., max: float | None = ..., min: float | None = ..., step: float | None = ...) -> dict:
    """Prepares dict element describing hyper parameter. Hyper parameter may be contructed in two ways:

    * ``HPOParameter('name', values=['val1', 'val2'])   # values``
    * ``HPOParameter('name', min=0.5, max=10, step=0.1) # range``

    In range description `min` and `step` are optional (by default `min` is set to 0 and `step` is set to 1).

    :param name: name of parameter
    :type name: str
    :param values: if parameter should have only values provided by user, this param should contain these values
    :type values: list[str] or list[int] or list[float], optional
    :param max: if parameter should contain numbers from range, this will be maximal value of this range
    :type max: int or float, optional
    :param min: if parameter should contain numbers from range, this will be minimal value of this range
    :type min: int or float, optional
    :param step: if parameter should contain numbers from range, this will be step between elements from range
    :type step: int or float, optional

    :return: description of HPO parameter
    :rtype: dict

    **Example:**

    .. code-block:: python

        (HPOParameter("param1", values=["a", "b", "c"]),)
        (HPOParameter("param2", values=[0, 1, 9]),)
        (HPOParameter("param3", values=[0.1, 0.5, 0.8]),)
        (HPOParameter("param4", max=10),)
        (HPOParameter("param5", min=2, max=10),)
        (HPOParameter("param6", max=10, step=2),)
        (HPOParameter("param7", max=10.0),)
        (HPOParameter("param8", min=0.1, max=10),)
        HPOParameter("param9", min=0.5, max=10, step=0.1)

    """
    ...

def HPOMethodParam(name: str | None = ..., value: str | float | None = ...) -> dict:
    ...

