"""
This type stub file was generated by pyright.
"""

import pandas as pd
from pathlib import Path
from typing import TYPE_CHECKING
from ibm_watsonx_ai.wml_resource import WMLResource
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class Import(WMLResource):
    def __init__(self, client: APIClient) -> None:
        ...
    
    def start(self, file_path: str | Path, space_id: str | None = ..., project_id: str | None = ...) -> dict:
        """Start the import. You must provide the space_id or the project_id.

        :param file_path: file path to the zip file with exported assets
        :type file_path: str | Path
        :param space_id: space identifier
        :type space_id: str, optional
        :param project_id: project identifier
        :type project_id: str, optional

        :return: response json
        :rtype: dict

        **Example:**

        .. code-block:: python

            details = client.import_assets.start(
                space_id="98a53931-a8c0-4c2f-8319-c793155e4598",
                file_path="/home/user/data_to_be_imported.zip",
            )
        """
        ...
    
    def cancel(self, import_id: str, space_id: str | None = ..., project_id: str | None = ...) -> None:
        """Cancel an import job. You must provide the space_id or the project_id.

        .. note::

            To delete an import_id job, use delete() api

        :param import_id: import the job identifier
        :type import_id: str
        :param space_id: space identifier
        :type space_id: str, optional
        :param project_id: project identifier
        :type project_id: str, optional


        **Example:**

        .. code-block:: python

            client.import_assets.cancel(
                import_id="6213cf1-252f-424b-b52d-5cdd9814956c",
                space_id="3421cf1-252f-424b-b52d-5cdd981495fe",
            )

        """
        ...
    
    def delete(self, import_id: str, space_id: str | None = ..., project_id: str | None = ...) -> None:
        """Deletes the given import_id job. You must provide the space_id or the project_id.

        :param import_id: import the job identifier
        :type import_id: str
        :param space_id: space identifier
        :type space_id: str, optional
        :param project_id: project identifier
        :type project_id: str, optional

        **Example:**

        .. code-block:: python

            client.import_assets.delete(
                import_id="6213cf1-252f-424b-b52d-5cdd9814956c",
                space_id="98a53931-a8c0-4c2f-8319-c793155e4598",
            )
        """
        ...
    
    def get_details(self, import_id: str | None = ..., space_id: str | None = ..., project_id: str | None = ..., limit: int | None = ..., asynchronous: bool = ..., get_all: bool = ...) -> dict:
        """Get metadata of the given import job. If no `import_id` is specified, all import metadata is returned.

        :param import_id: import the job identifier
        :type import_id: str, optional
        :param space_id: space identifier
        :type space_id: str, optional
        :param project_id: project identifier
        :type project_id: str, optional
        :param limit: limit number of fetched records
        :type limit: int, optional
        :param asynchronous: if `True`, it will work as a generator
        :type asynchronous: bool, optional
        :param get_all: if `True`, it will get all entries in 'limited' chunks
        :type get_all: bool, optional

        :return: import(s) metadata
        :rtype: dict (if import_id is not None) or {"resources": [dict]} (if import_id is None)

        **Example:**

        .. code-block:: python

            details = client.import_assets.get_details(import_id)
            details = client.import_assets.get_details()
            details = client.import_assets.get_details(limit=100)
            details = client.import_assets.get_details(limit=100, get_all=True)
            details = []
            for entry in client.import_assets.get_details(
                limit=100, asynchronous=True, get_all=True
            ):
                details.extend(entry)

        """
        ...
    
    def list(self, space_id: str | None = ..., project_id: str | None = ..., limit: int | None = ...) -> pd.DataFrame:
        """Return import jobs in a table format.

        :param space_id: space identifier
        :type space_id: str, optional
        :param project_id: project identifier
        :type project_id: str, optional
        :param limit: limit number of fetched records
        :type limit: int, optional

        :return: pandas.DataFrame with listed assets
        :rtype: pandas.DataFrame

        **Example:**

        .. code-block:: python

            client.import_assets.list()
        """
        ...
    
    @staticmethod
    def get_id(import_details: dict) -> str:
        """Get ID of the import job from import details.

        :param import_details: metadata of the import job
        :type import_details: dict

        :return: ID of the import job
        :rtype: str

        **Example:**

        .. code-block:: python

            id = client.import_assets.get_id(import_details)
        """
        ...
    


