"""
This type stub file was generated by pyright.
"""

import pandas
from pathlib import Path
from typing import Any, TYPE_CHECKING
from ibm_watsonx_ai.wml_resource import WMLResource
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class ModelDefinition(WMLResource):
    """Store and manage model definitions."""
    ConfigurationMetaNames = ...
    def __init__(self, client: APIClient) -> None:
        ...
    
    def store(self, model_definition: str | Path, meta_props: dict[str, str | dict]) -> dict:
        """Create a model definition.

        :param meta_props: metadata of the model definition configuration. To see available meta names, use:

            .. code-block:: python

                client.model_definitions.ConfigurationMetaNames.get()

        :type meta_props: dict

        :param model_definition: path to the content file to be uploaded
        :type model_definition: str | Path

        :return: metadata of the created model definition
        :rtype: dict

        **Example:**

        .. code-block:: python

            client.model_definitions.store(model_definition, meta_props)
        """
        ...
    
    async def astore(self, model_definition: str | Path, meta_props: dict[str, str | dict]) -> dict:
        """Create a model definition asynchronously.

        :param meta_props: metadata of the model definition configuration. To see available meta names, use:

            .. code-block:: python

                client.model_definitions.ConfigurationMetaNames.get()

        :type meta_props: dict

        :param model_definition: path to the content file to be uploaded
        :type model_definition: str | Path

        :return: metadata of the created model definition
        :rtype: dict

        **Example:**

        .. code-block:: python

            await client.model_definitions.astore(model_definition, meta_props)
        """
        ...
    
    def get_details(self, model_definition_id: str | None = ..., limit: int | None = ..., get_all: bool | None = ..., **kwargs: Any) -> dict:
        """Get metadata of a stored model definition. If no `model_definition_id` is passed,
        details for all model definitions are returned.

        :param model_definition_id: unique ID of the model definition
        :type model_definition_id: str, optional

        :param limit:  limit number of fetched records
        :type limit: int, optional

        :param get_all:  if True, it will get all entries in 'limited' chunks
        :type get_all: bool, optional

        :return: metadata of model definition
        :rtype: dict (if `model_definition_id` is not None)

        **Example:**

        .. code-block: python

            model_definition_details = client.model_definitions.get_details(model_definition_id)

        """
        ...
    
    async def aget_details(self, model_definition_id: str | None = ..., limit: int | None = ..., get_all: bool | None = ...) -> dict:
        """Get metadata of a stored model definition asynchronously. If no `model_definition_id` is passed,
        details for all model definitions are returned.

        :param model_definition_id: unique ID of the model definition
        :type model_definition_id: str, optional

        :param limit:  limit number of fetched records
        :type limit: int, optional

        :param get_all:  if True, it will get all entries in 'limited' chunks
        :type get_all: bool, optional

        :return: metadata of model definition
        :rtype: dict (if `model_definition_id` is not None)

        **Example:**

        .. code-block: python

            details = await client.model_definitions.aget_details(model_definition_id)

        """
        ...
    
    def download(self, model_definition_id: str | None, filename: str | Path | None = ..., rev_id: str | None = ..., **kwargs: Any) -> str:
        """Download the content of a model definition asset.

        :param model_definition_id: unique ID of the model definition asset to be downloaded
        :type model_definition_id: str
        :param filename: filename to be used for the downloaded file
        :type filename: str | Path
        :param rev_id: revision ID
        :type rev_id: str, optional

        :return: path to the downloaded asset content
        :rtype: str

        **Example:**

        .. code-block:: python

            client.model_definitions.download(
                model_definition_id, "model_definition_file"
            )
        """
        ...
    
    async def adownload(self, model_definition_id: str, filename: str | Path, rev_id: str | None = ...) -> str:
        """Download the content of a model definition asset asynchronously.

        :param model_definition_id: unique ID of the model definition asset to be downloaded
        :type model_definition_id: str
        :param filename: filename to be used for the downloaded file
        :type filename: str | Path
        :param rev_id: revision ID
        :type rev_id: str, optional

        :return: path to the downloaded asset content
        :rtype: str

        **Example:**

        .. code-block:: python

            await client.model_definitions.adownload(
                model_definition_id, "model_definition_file"
            )
        """
        ...
    
    def delete(self, model_definition_id: str | None = ..., **kwargs: Any) -> str:
        """Delete a stored model definition.

        :param model_definition_id: unique ID of the stored model definition
        :type model_definition_id: str

        :return: status "SUCCESS" if deletion is successful
        :rtype: Literal["SUCCESS"]
        :raises: ApiRequestFailure if deletion failed

        **Example:**

        .. code-block:: python

            client.model_definitions.delete(model_definition_id)

        """
        ...
    
    async def adelete(self, model_definition_id: str) -> str:
        """Delete a stored model definition asynchronously.

        :param model_definition_id: unique ID of the stored model definition
        :type model_definition_id: str

        :return: status "SUCCESS" if deletion is successful
        :rtype: Literal["SUCCESS"]
        :raises: ApiRequestFailure if deletion failed

        **Example:**

        .. code-block:: python

            await client.model_definitions.adelete(model_definition_id)

        """
        ...
    
    def list(self, limit: int | None = ...) -> pandas.DataFrame:
        """Return the stored model definition assets in a table format.

        :param limit: limit number of fetched records
        :type limit: int, optional

        :return: pandas.DataFrame with listed model definitions
        :rtype: pandas.DataFrame

        **Example:**

        .. code-block:: python

            client.model_definitions.list()

        """
        ...
    
    def get_id(self, model_definition_details: dict) -> str:
        """Get the unique ID of a stored model definition asset.

        :param model_definition_details: metadata of the stored model definition asset
        :type model_definition_details: dict

        :return: unique ID of the stored model definition asset
        :rtype: str

        **Example:**

        .. code-block:: python

            asset_id = client.model_definition.get_id(asset_details)

        """
        ...
    
    def get_uid(self, model_definition_details: dict) -> str:
        """Get the UID of the stored model.

        *Deprecated:* Use ``get_id(model_definition_details)`` instead.

        :param model_definition_details: details of the stored model definition
        :type model_definition_details: dict

        :return: UID of the stored model definition
        :rtype: str

        **Example:**

        .. code-block:: python

            model_definition_uid = client.model_definitions.get_uid(
                model_definition_details
            )
        """
        ...
    
    def get_href(self, model_definition_details: dict) -> str:
        """Get the href of a stored model definition.

        :param model_definition_details: details of the stored model definition
        :type model_definition_details: dict

        :return: href of the stored model definition
        :rtype: str

        **Example:**

        .. code-block:: python

            model_definition_id = client.model_definitions.get_href(
                model_definition_details
            )
        """
        ...
    
    def update(self, model_definition_id: str, meta_props: dict[str, str | dict] | None = ..., file_path: str | Path | None = ...) -> dict:
        """Update the model definition with metadata, attachment, or both.

        :param model_definition_id: ID of the model definition
        :type model_definition_id: str
        :param meta_props: metadata of the model definition configuration to be updated
        :type meta_props: dict, optional
        :param file_path: path to the content file to be uploaded
        :type file_path: str | Path, optional

        :return: updated metadata of the model definition
        :rtype: dict

        **Example:**

        .. code-block:: python

            model_definition_details = client.model_definition.update(
                model_definition_id, meta_props, file_path
            )
        """
        ...
    
    async def aupdate(self, model_definition_id: str, meta_props: dict[str, str | dict] | None = ..., file_path: str | Path | None = ...) -> dict:
        """Update the model definition with metadata, attachment, or both asynchronously.

        :param model_definition_id: ID of the model definition
        :type model_definition_id: str
        :param meta_props: metadata of the model definition configuration to be updated
        :type meta_props: dict, optional
        :param file_path: path to the content file to be uploaded
        :type file_path: str | Path, optional

        :return: updated metadata of the model definition
        :rtype: dict

        **Example:**

        .. code-block:: python

            model_definition_details = await client.model_definition.aupdate(
                model_definition_id, meta_props, file_path
            )
        """
        ...
    
    def create_revision(self, model_definition_id: str | None = ..., **kwargs: Any) -> dict:
        """Create a revision for the given model definition. Revisions are immutable once created.
        The metadata and attachment of the model definition is taken and a revision is created out of it.

        :param model_definition_id: ID of the model definition
        :type model_definition_id: str

        :return: revised metadata of the stored model definition
        :rtype: dict

        **Example:**

        .. code-block:: python

            model_definition_revision = client.model_definitions.create_revision(
                model_definition_id
            )
        """
        ...
    
    async def acreate_revision(self, model_definition_id: str) -> dict:
        """Create a revision for the given model definition asynchronously. Revisions are immutable once created.
        The metadata and attachment of the model definition is taken and a revision is created out of it.

        :param model_definition_id: ID of the model definition
        :type model_definition_id: str

        :return: revised metadata of the stored model definition
        :rtype: dict

        **Example:**

        .. code-block:: python

            model_definition_revision = (
                await client.model_definitions.acreate_revision(model_definition_id)
            )
        """
        ...
    
    def get_revision_details(self, model_definition_id: str | None = ..., rev_id: str | None = ..., **kwargs: Any) -> dict:
        """Get metadata of a model definition.

        :param model_definition_id: ID of the model definition
        :type model_definition_id: str

        :param rev_id: ID of the revision. If this parameter is not provided, it returns the latest revision. If there is no latest revision, it returns an error.
        :type rev_id: str, optional

        :return: metadata of the stored model definition
        :rtype: dict

        **Example:**

        .. code-block:: python

            script_details = client.model_definitions.get_revision_details(
                model_definition_id, rev_id
            )
        """
        ...
    
    async def aget_revision_details(self, model_definition_id: str, rev_id: str | None = ...) -> dict:
        """Get metadata of a model definition.

        :param model_definition_id: ID of the model definition
        :type model_definition_id: str

        :param rev_id: ID of the revision. If this parameter is not provided, it returns the latest revision. If there is no latest revision, it returns an error.
        :type rev_id: str, optional

        :return: metadata of the stored model definition
        :rtype: dict

        **Example:**

        .. code-block:: python

            script_details = client.model_definitions.get_revision_details(
                model_definition_id, rev_id
            )
        """
        ...
    
    def list_revisions(self, model_definition_id: str | None = ..., limit: int | None = ..., **kwargs: Any) -> pandas.DataFrame:
        """Return the stored model definition assets in a table format.

        :param model_definition_id: unique ID of the model definition
        :type model_definition_id: str
        :param limit: limit number of fetched records
        :type limit: int, optional

        :return: pandas.DataFrame with listed model definitions
        :rtype: pandas.DataFrame

        **Example:**

        .. code-block:: python

            client.model_definitions.list_revisions()

        """
        ...
    


