"""
This type stub file was generated by pyright.
"""

from typing import Literal, TYPE_CHECKING, TypeAlias
from ibm_watsonx_ai.wml_resource import WMLResource
from pandas import DataFrame
from ibm_watsonx_ai import APIClient

ListType: TypeAlias = list
if TYPE_CHECKING:
    ...
class ParameterSets(WMLResource):
    """Store and manage parameter sets."""
    ConfigurationMetaNames = ...
    def __init__(self, client: APIClient) -> None:
        ...
    
    def get_details(self, parameter_set_id: str | None = ...) -> dict:
        """Get parameter set details. If no parameter_sets_id is passed, details for all parameter sets
        are returned.

        :param parameter_set_id: ID of the software specification
        :type parameter_set_id: str, optional

        :return: metadata of the stored parameter set(s)
        :rtype:
          - **dict** - if `parameter_set_id` is not None
          - **{"parameter_sets": [dict]}** - if `parameter_set_id` is None

        **Examples**

        If `parameter_set_id` is None:

        .. code-block:: python

            parameter_sets_details = client.parameter_sets.get_details()

        If `parameter_set_id` is given:

        .. code-block:: python

            parameter_sets_details = client.parameter_sets.get_details(
                parameter_set_id
            )

        """
        ...
    
    def create(self, meta_props: dict) -> dict:
        """Create a parameter set.

        :param meta_props: metadata of the space configuration. To see available meta names, use:

            .. code-block:: python

                client.parameter_sets.ConfigurationMetaNames.get()

        :type meta_props: dict

        :return: metadata of the stored parameter set
        :rtype: dict

        **Example:**

        .. code-block:: python

            meta_props = {
                client.parameter_sets.ConfigurationMetaNames.NAME: "Example name",
                client.parameter_sets.ConfigurationMetaNames.DESCRIPTION: "Example description",
                client.parameter_sets.ConfigurationMetaNames.PARAMETERS: [
                    {
                        "name": "string",
                        "description": "string",
                        "prompt": "string",
                        "type": "string",
                        "subtype": "string",
                        "value": "string",
                        "valid_values": ["string"],
                    }
                ],
                client.parameter_sets.ConfigurationMetaNames.VALUE_SETS: [
                    {
                        "name": "string",
                        "values": [{"name": "string", "value": "string"}],
                    }
                ],
            }

            parameter_sets_details = client.parameter_sets.create(meta_props)
        """
        ...
    
    def list(self, limit: int | None = ...) -> DataFrame:
        """List parameter sets in a table format.

        :param limit: limit number of fetched records
        :type limit: int, optional

        :return: pandas.DataFrame with listed parameter sets
        :rtype: pandas.DataFrame

        **Example:**

        .. code-block:: python

            client.parameter_sets.list()
        """
        ...
    
    def delete(self, parameter_set_id: str) -> str:
        """Delete a parameter set.

        :param parameter_set_id: unique ID of the parameter set
        :type parameter_set_id: str

        :return: status ("SUCCESS" or "FAILED")
        :rtype: str

        **Example:**

        .. code-block:: python

            client.parameter_sets.delete(parameter_set_id)

        """
        ...
    
    def get_id_by_name(self, parameter_set_name: str) -> str:
        """Get the unique ID of a parameter set.

        :param parameter_set_name: name of the parameter set
        :type parameter_set_name: str

        :return: unique ID of the parameter set
        :rtype: str

        **Example:**

        .. code-block:: python

            asset_id = client.parameter_sets.get_id_by_name(parameter_set_name)

        """
        ...
    
    def update(self, parameter_set_id: str, new_data: ListType[dict] | str, file_path: Literal["description", "parameters", "value_sets"]) -> dict:
        """Update parameter sets.

        :param parameter_set_id: unique ID of the parameter sets
        :type parameter_set_id: str

        :param new_data: new data for parameters
        :type new_data: str, list

        :param file_path: path to update
        :type file_path: str

        :return: metadata of the updated parameter sets
        :rtype: dict

        **Example for description**

        .. code-block:: python

            new_description_data = "New description"
            parameter_set_details = client.parameter_sets.update(
                parameter_set_id, new_description_data, "description"
            )

        **Example for parameters**

        .. code-block:: python

            new_parameters_data = [
                {
                    "name": "string",
                    "description": "new_description",
                    "prompt": "new_string",
                    "type": "new_string",
                    "subtype": "new_string",
                    "value": "new_string",
                    "valid_values": ["new_string"],
                }
            ]
            parameter_set_details = client.parameter_sets.update(
                parameter_set_id, new_parameters_data, "parameters"
            )

        **Example for value_sets**

        .. code-block:: python

            new_value_sets_data = [
                {
                    "name": "string",
                    "values": [{"name": "string", "value": "new_string"}],
                }
            ]
            parameter_set_details = client.parameter_sets.update_value_sets(
                parameter_set_id, new_value_sets_data, "value_sets"
            )

        """
        ...
    


