"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Literal, TYPE_CHECKING
from ibm_watsonx_ai.wml_resource import WMLResource
from pandas import DataFrame
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class PkgExtn(WMLResource):
    """Store and manage software Packages Extension specs."""
    ConfigurationMetaNames = ...
    def __init__(self, client: APIClient) -> None:
        ...
    
    def get_details(self, pkg_extn_id: str) -> dict:
        """Get package extensions details.

        :param pkg_extn_id: unique ID of the package extension
        :type pkg_extn_id: str

        :return: details of the package extension
        :rtype: dict

        **Example:**

        .. code-block:: python

            pkg_extn_details = client.pkg_extn.get_details(pkg_extn_id)

        """
        ...
    
    async def aget_details(self, pkg_extn_id: str) -> dict:
        """Get package extensions details asynchronously.

        :param pkg_extn_id: unique ID of the package extension
        :type pkg_extn_id: str

        :return: details of the package extension
        :rtype: dict

        **Example:**

        .. code-block:: python

            pkg_extn_details = await client.pkg_extn.aget_details(pkg_extn_id)

        """
        ...
    
    def store(self, meta_props: dict, file_path: str | Path) -> dict:
        """Create a package extension.

        :param meta_props: metadata of the package extension. To see available meta names, use:

            .. code-block:: python

                client.package_extensions.ConfigurationMetaNames.get()

        :type meta_props: dict

        :param file_path: path to the file to be uploaded as a package extension
        :type file_path: str

        :return: metadata of the package extension
        :rtype: dict

        **Example:**

        .. code-block:: python

            meta_props = {
                client.package_extensions.ConfigurationMetaNames.NAME: "skl_pipeline_heart_problem_prediction",
                client.package_extensions.ConfigurationMetaNames.DESCRIPTION: "description scikit-learn_0.20",
                client.package_extensions.ConfigurationMetaNames.TYPE: "conda_yml",
            }

            pkg_extn_details = client.package_extensions.store(
                meta_props=meta_props, file_path="/path/to/file"
            )

        """
        ...
    
    async def astore(self, meta_props: dict, file_path: str | Path) -> dict:
        """Create a package extension asynchronously.

        :param meta_props: metadata of the package extension. To see available meta names, use:

            .. code-block:: python

                client.package_extensions.ConfigurationMetaNames.get()

        :type meta_props: dict

        :param file_path: path to the file to be uploaded as a package extension
        :type file_path: str | Path

        :return: metadata of the package extension
        :rtype: dict

        **Example:**

        .. code-block:: python

            meta_props = {
                client.package_extensions.ConfigurationMetaNames.NAME: "skl_pipeline_heart_problem_prediction",
                client.package_extensions.ConfigurationMetaNames.DESCRIPTION: "description scikit-learn_0.20",
                client.package_extensions.ConfigurationMetaNames.TYPE: "conda_yml",
            }

            pkg_extn_details = await client.package_extensions.astore(
                meta_props=meta_props, file_path="/path/to/file"
            )

        """
        ...
    
    def list(self) -> DataFrame:
        """List the package extensions in a table format.

        :return: pandas.DataFrame with listed package extensions
        :rtype: pandas.DataFrame

        .. code-block:: python

            client.package_extensions.list()

        """
        ...
    
    @staticmethod
    def get_id(pkg_extn_details: dict) -> str:
        """Get the unique ID of a package extension.

        :param pkg_extn_details: details of the package extension
        :type pkg_extn_details: dict

        :return: unique ID of the package extension
        :rtype: str

        **Example:**

        .. code-block:: python

            asset_id = client.package_extensions.get_id(pkg_extn_details)

        """
        ...
    
    def get_id_by_name(self, pkg_extn_name: str) -> str:
        """Get the ID of a package extension.

        :param pkg_extn_name: name of the package extension
        :type pkg_extn_name: str

        :return: unique ID of the package extension
        :rtype: str

        **Example:**

        .. code-block:: python

            asset_id = client.package_extensions.get_id_by_name(pkg_extn_name)

        """
        ...
    
    async def aget_id_by_name(self, pkg_extn_name: str) -> str:
        """Get the ID of a package extension asynchronously.

        :param pkg_extn_name: name of the package extension
        :type pkg_extn_name: str

        :return: unique ID of the package extension
        :rtype: str

        **Example:**

        .. code-block:: python

            asset_id = await client.package_extensions.aget_id_by_name(
                pkg_extn_name
            )

        """
        ...
    
    @staticmethod
    def get_href(pkg_extn_details: dict) -> str:
        """Get the URL of a stored package extension.

        :param pkg_extn_details: details of the package extension
        :type pkg_extn_details: dict

        :return: href of the package extension
        :rtype: str

        **Example:**

        .. code-block:: python

            pkg_extn_details = client.package_extensions.get_details(pkg_extn_id)
            pkg_extn_href = client.package_extensions.get_href(pkg_extn_details)

        """
        ...
    
    def delete(self, pkg_extn_id: str) -> Literal["SUCCESS"]:
        """Delete a package extension.

        :param pkg_extn_id: unique ID of the package extension
        :type pkg_extn_id: str

        :return: status "SUCCESS" if deletion is successful
        :rtype: Literal["SUCCESS"]
        :raises: ApiRequestFailure if deletion failed

        **Example:**

        .. code-block:: python

            client.package_extensions.delete(pkg_extn_id)

        """
        ...
    
    async def adelete(self, pkg_extn_id: str) -> Literal["SUCCESS"]:
        """Delete a package extension asynchronously.

        :param pkg_extn_id: unique ID of the package extension
        :type pkg_extn_id: str

        :return: status "SUCCESS" if deletion is successful
        :rtype: Literal["SUCCESS"]
        :raises: ApiRequestFailure if deletion failed

        **Example:**

        .. code-block:: python

            await client.package_extensions.adelete(pkg_extn_id)

        """
        ...
    
    def download(self, pkg_extn_id: str, filename: str | Path) -> str:
        """Download a package extension.

        :param pkg_extn_id: unique ID of the package extension to be downloaded
        :type pkg_extn_id: str

        :param filename: filename to be used for the downloaded file
        :type filename: str | Path

        :return: path to the downloaded package extension content
        :rtype: str

        **Example:**

        .. code-block:: python

            client.package_extensions.download(
                pkg_extn_id, "sample_conda.yml/custom_library.zip"
            )

        """
        ...
    
    async def adownload(self, pkg_extn_id: str, filename: str | Path) -> str:
        """Download a package extension asynchronously.

        :param pkg_extn_id: unique ID of the package extension to be downloaded
        :type pkg_extn_id: str

        :param filename: filename to be used for the downloaded file
        :type filename: str | Path

        :return: path to the downloaded package extension content
        :rtype: str

        **Example:**

        .. code-block:: python

            file_path = await client.package_extensions.adownload(
                pkg_extn_id, "sample_conda.yml/custom_library.zip"
            )

        """
        ...
    


