"""
This type stub file was generated by pyright.
"""

from typing import Any, Literal, TYPE_CHECKING
from ibm_watsonx_ai.metanames import MemberMetaNames
from ibm_watsonx_ai.wml_resource import WMLResource
from pandas import DataFrame
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class Projects(WMLResource):
    """Store and manage projects.

    .. note::
        Projects module is available since Python SDK version 1.3.5.

    """
    ConfigurationMetaNames = ...
    MemberMetaNames = ...
    def __init__(self, client: APIClient) -> None:
        ...
    
    def store(self, meta_props: dict) -> dict:
        """Create a project.

        :param meta_props: metadata of the project configuration. To see available meta names, use:

            .. code-block:: python

                client.projects.ConfigurationMetaNames.get()

        :type meta_props: dict

        :return: metadata of the stored project
        :rtype: dict

        **Example:**

        .. code-block:: python

            meta_props = {
                client.projects.ConfigurationMetaNames.NAME: "my project",
                client.projects.ConfigurationMetaNames.DESCRIPTION: "test project",
                client.projects.ConfigurationMetaNames.STORAGE: {
                    "type": "assetfiles"
                },
            }

            projects_details = client.projects.store(meta_props)
        """
        ...
    
    @staticmethod
    def get_id(project_details: dict) -> str:
        """Get the project_id from the project details.

        :param project_details: metadata of the stored project
        :type project_details: dict

        :return: ID of the stored project
        :rtype: str

        **Example:**

        .. code-block:: python

            project_details = client.projects.store(meta_props)
            project_id = client.projects.get_id(project_details)
        """
        ...
    
    def get_id_by_name(self, project_name: str) -> str:
        """Get the ID of a stored project by name.

        :param project_name: name of the stored project
        :type project_name: str

        :return: ID of the stored project
        :rtype: str

        **Example:**

        .. code-block:: python

            project_id = client.projects.get_id_by_name(project_name)

        """
        ...
    
    def delete(self, project_id: str) -> Literal["SUCCESS"]:
        """Delete a stored project.

        :param project_id: ID of the project
        :type project_id: str

        :return: status "SUCCESS" if deletion is successful
        :rtype: Literal["SUCCESS"]

        **Example:**

        .. code-block:: python

            client.projects.delete(project_id)
        """
        ...
    
    def get_details(self, project_id: str | None = ..., limit: int | None = ..., asynchronous: bool | None = ..., get_all: bool | None = ..., project_name: str | None = ..., **kwargs: Any) -> dict:
        """Get metadata of stored project(s).

        :param project_id: ID of the project
        :type project_id: str, optional
        :param limit: applicable when `project_id` is not provided, otherwise `limit` will be ignored
        :type limit: int, optional
        :param asynchronous: if `True`, it will work as a generator
        :type asynchronous: bool, optional
        :param get_all:  if `True`, it will get all entries in 'limited' chunks
        :type get_all: bool, optional
        :param project_name: name of the stored project, can be used only when `project_id` is None
        :type project_name: str, optional

        :return: metadata of stored project(s)
        :rtype:
            - **dict** - if project_id is not None
            - **{"resources": [dict]}** - if project_id is None

        **Example:**

        .. code-block:: python

            project_details = client.projects.get_details(project_id)
            project_details = client.projects.get_details(project_name)
            project_details = client.projects.get_details(limit=100)
            project_details = client.projects.get_details(limit=100, get_all=True)
            project_details = []
            for entry in client.projects.get_details(
                limit=100, asynchronous=True, get_all=True
            ):
                project_details.extend(entry)

        """
        ...
    
    def list(self, limit: int | None = ..., member: str | None = ..., roles: str | None = ..., project_type: str | None = ...) -> DataFrame:
        """List stored projects in a table format.

        :param limit: limit number of fetched records
        :type limit: int, optional
        :param member: filters the result list, only includes projects where the user with a matching user ID
            is a member
        :type member: str, optional
        :param roles: a list of comma-separated project roles to use to filter the query results,
            must be used in conjunction with the "member" query parameter,
            available values : `admin`, `editor`, `viewer`
        :type roles: str, optional
        :param project_type: filter projects by their type, available types are 'cpd', 'wx', 'wca', 'dpx' and 'wxbi'
        :type project_type: str, optional

        :return: pandas.DataFrame with listed projects
        :rtype: pandas.DataFrame

        **Example:**

        .. code-block:: python

            client.projects.list()
        """
        ...
    
    def update(self, project_id: str, changes: dict) -> dict:
        """Update existing project metadata. 'STORAGE' cannot be updated.

        :param project_id: ID of the project with the definition to be updated
        :type project_id: str
        :param changes: elements to be changed, where keys are ConfigurationMetaNames
        :type changes: dict

        :return: metadata of the updated project
        :rtype: dict

        **Example:**

        .. code-block:: python

            metadata = {
                client.projects.ConfigurationMetaNames.NAME: "updated_project",
                client.projects.ConfigurationMetaNames.COMPUTE: {
                    "name": "test_instance",
                    "crn": "v1:staging:public:pm-20-dev:us-south:a/09796a1b4cddfcc9f7fe17824a68a0f8:f1026e4b-77cf-4703-843d-c9984eac7272::",
                },
            }
            project_details = client.projects.update(project_id, changes=metadata)
        """
        ...
    
    def create_member(self, project_id: str, meta_props: dict) -> dict:
        """Create a member within a project.

        :param project_id: ID of the project with the definition to be updated
        :type project_id: str
        :param meta_props: metadata of the member configuration. To see available meta names, use:

            .. code-block:: python

                client.projects.MemberMetaNames.get()

        :type meta_props: dict

        :return: metadata of the stored member
        :rtype: dict

        .. note::
            * `role` can be any one of the following: "viewer", "editor", "admin"
            * `type` can be any one of the following: "user", "service"
            * `id` can be one of the following: service-ID or IAM-userID

        **Examples**

        .. code-block:: python

            metadata = {
                client.projects.MemberMetaNames.MEMBERS: [
                    {"id": "IBMid-100000DK0B", "type": "user", "role": "admin"}
                ]
            }
            members_details = client.projects.create_member(
                project_id=project_id, meta_props=metadata
            )

        .. code-block:: python

            metadata = {
                client.projects.MemberMetaNames.MEMBERS: [
                    {
                        "id": "iam-ServiceId-5a216e59-6592-43b9-8669-625d341aca71",
                        "type": "service",
                        "role": "admin",
                    }
                ]
            }
            members_details = client.projects.create_member(
                project_id=project_id, meta_props=metadata
            )
        """
        ...
    
    def get_member_details(self, project_id: str, user_name: str | None = ...) -> dict:
        """Get metadata of a member associated with a project. If no user_name is passed, all members details will be returned.

        :param project_id: ID of that project with the definition to be updated
        :type project_id: str
        :param user_name: name of the member
        :type user_name: str, optional

        :return: metadata of the project member
        :rtype: dict

        **Example:**

        .. code-block:: python

            member_details = client.projects.get_member_details(
                project_id, "test@ibm.com"
            )
            members_details = client.projects.get_member_details(project_id)
        """
        ...
    
    def delete_member(self, project_id: str, user_name: str | None = ...) -> str:
        """Delete a member associated with a project.

        :param project_id: ID of the project
        :type project_id: str
        :param user_name: name of the member
        :type user_name: str, optional

        :return: status ("SUCCESS" if succeeded)
        :rtype: str

        **Example:**

        .. code-block:: python

            client.projects.delete_member(project_id, user_name)
        """
        ...
    
    def update_member(self, project_id: str, user_name: str, changes: dict) -> dict:
        """Update the metadata of an existing member.

        :param project_id: ID of the project
        :type project_id: str
        :param user_name: name of the member to be updated
        :type user_name: str
        :param changes: elements to be changed, where keys are ConfigurationMetaNames
        :type changes: dict

        :return: metadata of the updated member
        :rtype: dict

        **Example:**

        .. code-block:: python

            metadata = {client.projects.MemberMetaNames.MEMBER: {"role": "editor"}}
            member_details = client.projects.update_member(
                project_id, user_name, changes=metadata
            )
        """
        ...
    
    def list_members(self, project_id: str, limit: int | None = ..., identity_type: str | None = ..., role: str | None = ..., state: str | None = ...) -> DataFrame:
        """Print the stored members of a project in a table format.

        :param project_id: ID of the project
        :type project_id: str
        :param limit: limit number of fetched records
        :type limit: int, optional
        :param identity_type: filter the members by type
        :type identity_type: str, optional
        :param role: filter the members by role
        :type role: str, optional
        :param state: filter the members by state
        :type state: str, optional

        :return: pandas.DataFrame with listed members
        :rtype: pandas.DataFrame

        **Example:**

        .. code-block:: python

            client.projects.list_members(project_id)
        """
        ...
    


