"""
This type stub file was generated by pyright.
"""

from typing import Literal, TYPE_CHECKING
from ibm_watsonx_ai.wml_resource import WMLResource
from pandas import DataFrame
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class RuntimeDefinitions(WMLResource):
    """Store and manage runtime definitions."""
    ConfigurationMetaNames = ...
    def __init__(self, client: APIClient) -> None:
        ...
    
    def store(self, meta_props: dict) -> dict:
        """Create a runtime definition.

        :param meta_props: metadata of the runtime definition configuration. To see available meta names, use:

            .. code-block:: python

                client.runtime_definitions.ConfigurationMetaNames.get()

        :type meta_props: dict

        :return: metadata of the created runtime definition
        :rtype: dict

        **Example:**

        .. code-block:: python

            meta_props = {
                client.runtime_definitions.ConfigurationMetaNames.NAME: "custom runtime definition",
                client.runtime_definitions.ConfigurationMetaNames.DESCRIPTION: "Custom runtime definition created with SDK",
            }

            client.runtime_definitions.store(meta_props)

        """
        ...
    
    def get_details(self, runtime_definition_id: str | None = ..., include: str | None = ...) -> dict:
        """Get runtime definitions details.

        :param runtime_definition_id: unique ID of the runtime definitions
        :type runtime_definition_id: str

        :param include: query parameter to include additional fields, e.g., ``launch_configuration``.
            Requires cluster admin privileges.
        :type include: str, optional

        :return: metadata of the runtime definitions
        :rtype: dict

        **Example:**

        .. code-block:: python

            runtime_definition_details = client.runtime_definitions.get_details(
                runtime_definition_id
            )

        """
        ...
    
    def list(self, limit: int | None = ...) -> DataFrame:
        """List runtime definitions in a table format.

        :param limit: limit number of fetched records
        :type limit: int, optional

        :return: pandas.DataFrame with listed runtime definitions
        :rtype: pandas.DataFrame

        **Example:**

        .. code-block:: python

            client.runtime_definitions.list()

        """
        ...
    
    @staticmethod
    def get_id(runtime_definition_details: dict) -> str:
        """Get the ID of a runtime definition asset.

        :param runtime_definition_details: metadata of the runtime definition
        :type runtime_definition_details: dict

        :return: unique ID of the runtime definition
        :rtype: str

        **Example:**

        .. code-block:: python

            asset_id = client.runtime_definitions.get_id(runtime_definition_details)

        """
        ...
    
    def get_id_by_name(self, runtime_definition_name: str) -> str:
        """Get the unique ID of a runtime definition for the given name.

        :param runtime_definition_name: name of the runtime definition
        :type runtime_definition_name: str

        :return: unique ID of the runtime definition
        :rtype: str

        **Example:**

        .. code-block:: python

            asset_id = client.runtime_definitions.get_id_by_name(
                runtime_definition_name
            )

        """
        ...
    
    def delete(self, runtime_definition_id: str) -> Literal["SUCCESS"]:
        """Delete a runtime definition.

        :param runtime_definition_id: unique ID of the runtime definition to be deleted
        :type runtime_definition_id: str

        :return: status "SUCCESS" if deletion is successful
        :rtype: Literal["SUCCESS"]

        **Example:**

        .. code-block:: python

            client.runtime_definitions.delete(runtime_definition_id)

        """
        ...
    
    def update(self, runtime_definition_id: str, changes: dict) -> dict:
        """Updates existing runtime definition asset metadata.

        :param runtime_definition_id: ID of runtime definition to be updated
        :type runtime_definition_id: str

        :param changes: elements that will be changed, where keys are ConfigurationMetaNames
        :type changes: dict

        **Example:**

        .. code-block:: python

            metadata = {
                client.runtime_definitions.ConfigurationMetaNames.NAME: "updated_runtime_definition"
            }

            runtime_definitions_details = client.runtime_definitions.update(
                runtime_definition_id, changes=metadata
            )

        """
        ...
    


