"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, TYPE_CHECKING, TypeAlias
from ibm_watsonx_ai.wml_resource import WMLResource
from pandas import DataFrame
from ibm_watsonx_ai import APIClient

ListType: TypeAlias = list
if TYPE_CHECKING:
    ...
class Script(WMLResource):
    """Store and manage script assets."""
    ConfigurationMetaNames = ...
    def __init__(self, client: APIClient) -> None:
        ...
    
    def get_details(self, script_id: str | None = ..., limit: int | None = ..., get_all: bool | None = ..., **kwargs: Any) -> dict:
        """Get script asset details. If no script_id is passed, details for all script assets are returned.

        :param script_id: unique ID of the script
        :type script_id: str, optional

        :param limit:  limit number of fetched records
        :type limit: int, optional

        :param get_all:  if True, it will get all entries in 'limited' chunks
        :type get_all: bool, optional

        :return: metadata of the stored script asset
        :rtype:
            - **dict** - if script_id is not None
            - **{"resources": [dict]}** - if script_id is None

        **Example:**

        .. code-block:: python

            script_details = client.script.get_details(script_id)

        """
        ...
    
    def store(self, meta_props: dict, file_path: str | Path) -> dict:
        """Create a script asset and upload content to it.

        :param meta_props: name to be given to the script asset
        :type meta_props: dict

        :param file_path: path to the content file to be uploaded
        :type file_path: str | Path

        :return: metadata of the stored script asset
        :rtype: dict

        **Example:**

        .. code-block:: python

            metadata = {
                client.script.ConfigurationMetaNames.NAME: "my first script",
                client.script.ConfigurationMetaNames.DESCRIPTION: "description of the script",
                client.script.ConfigurationMetaNames.SOFTWARE_SPEC_ID: "0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda",
            }

            asset_details = client.script.store(
                meta_props=metadata, file_path="/path/to/file"
            )

        """
        ...
    
    def list(self, limit: int | None = ...) -> DataFrame:
        """List stored scripts in a table format.

        :param limit: limit number of fetched records
        :type limit: int, optional

        :return: pandas.DataFrame with listed scripts
        :rtype: pandas.DataFrame

        **Example:**

        .. code-block:: python

            client.script.list()
        """
        ...
    
    def download(self, asset_id: str | None = ..., filename: str | Path | None = ..., rev_id: str | None = ..., **kwargs: Any) -> str:
        """Download the content of a script asset.

        :param asset_id: unique ID of the script asset to be downloaded
        :type asset_id: str

        :param filename: filename to be used for the downloaded file
        :type filename: str | Path

        :param rev_id: revision ID
        :type rev_id: str, optional

        :return: path to the downloaded asset content
        :rtype: str

        **Example:**

        .. code-block:: python

            client.script.download(asset_id, "script_file")
        """
        ...
    
    @staticmethod
    def get_id(asset_details: dict) -> str:
        """Get the unique ID of a stored script asset.

        :param asset_details: metadata of the stored script asset
        :type asset_details: dict

        :return: unique ID of the stored script asset
        :rtype: str

        **Example:**

        .. code-block:: python

            asset_id = client.script.get_id(asset_details)
        """
        ...
    
    @staticmethod
    def get_href(asset_details: dict) -> str:
        """Get the URL of a stored script asset.

        :param asset_details: details of the stored script asset
        :type asset_details: dict

        :return: href of the stored script asset
        :rtype: str

        **Example:**

        .. code-block:: python

            asset_details = client.script.get_details(asset_id)
            asset_href = client.script.get_href(asset_details)

        """
        ...
    
    def update(self, script_id: str | None = ..., meta_props: dict | None = ..., file_path: str | Path | None = ..., **kwargs: Any) -> dict:
        """Update a script with metadata, attachment, or both.

        :param script_id: ID of the script
        :type script_id: str

        :param meta_props: changes for the script matadata
        :type meta_props: dict, optional

        :param file_path: file path to the new attachment
        :type file_path: str | Path, optional

        :return: updated metadata of the script
        :rtype: dict

        **Example:**

        .. code-block:: python

            script_details = client.script.update(script_id, meta, content_path)
        """
        ...
    
    def delete(self, asset_id: str | None = ..., force: bool = ..., **kwargs: Any) -> dict | str:
        """Delete a stored script asset.

        :param asset_id: ID of the script asset
        :type asset_id: str

        :param force: if True, the delete operation will proceed even when the script deployment exists, defaults to False
        :type force: bool, optional

        :return: status ("SUCCESS" or "FAILED") if deleted synchronously or dictionary with response
        :rtype: str | dict

        **Example:**

        .. code-block:: python

            client.script.delete(asset_id)

        """
        ...
    
    def create_revision(self, script_id: str | None = ..., **kwargs: Any) -> dict:
        """Create a revision for the given script. Revisions are immutable once created.
        The metadata and attachment at `script_id` is taken and a revision is created out of it.

        :param script_id: ID of the script
        :type script_id: str

        :return: revised metadata of the stored script
        :rtype: dict

        **Example:**

        .. code-block:: python

            script_revision = client.script.create_revision(script_id)
        """
        ...
    
    def list_revisions(self, script_id: str | None = ..., limit: int | None = ..., **kwargs: Any) -> DataFrame:
        """Print all revisions for the given script ID in a table format.

        :param script_id: ID of the stored script
        :type script_id: str

        :param limit: limit number of fetched records
        :type limit: int, optional

        :return: pandas.DataFrame with listed revisions
        :rtype: pandas.DataFrame

        **Example:**

        .. code-block:: python

            client.script.list_revisions(script_id)
        """
        ...
    
    def get_revision_details(self, script_id: str | None = ..., rev_id: str | None = ..., **kwargs: Any) -> ListType:
        """Get metadata of the script revision.

        :param script_id: ID of the script
        :type script_id: str

        :param rev_id: ID of the revision. If this parameter is not provided, it returns the latest revision. If there is no latest revision, it returns an error.
        :type rev_id: str, optional

        :return: metadata of the stored script(s)
        :rtype: list

        **Example:**

        .. code-block:: python

            script_details = client.script.get_revision_details(script_id, rev_id)
        """
        ...
    


