"""
This type stub file was generated by pyright.
"""

from typing import Any, Literal, TYPE_CHECKING
from ibm_watsonx_ai.wml_resource import WMLResource
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class Set(WMLResource):
    """Set a space_id or a project_id to be used in the subsequent actions."""
    def __init__(self, client: APIClient) -> None:
        ...
    
    def default_space(self, space_id: str | None = ..., **kwargs: Any) -> Literal["SUCCESS"]:
        """Set a space ID.

        :param space_id: ID of the space to be used
        :type space_id: str

        :return: status ("SUCCESS" if succeeded)
        :rtype: str

        **Example:**

        .. code-block:: python

            client.set.default_space(space_id)

        """
        ...
    
    def default_project(self, project_id: str) -> Literal["SUCCESS"]:
        """Set a project ID.

        :param project_id: ID of the project to be used
        :type project_id: str

        :return: status ("SUCCESS" if succeeded)
        :rtype: str

        **Example:**

        .. code-block:: python

            client.set.default_project(project_id)
        """
        ...
    


