"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from ibm_watsonx_ai.lifecycle import SpecStates
from ibm_watsonx_ai.wml_resource import WMLResource
from pandas import DataFrame
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class SwSpec(WMLResource):
    """Store and manage software specs."""
    ConfigurationMetaNames = ...
    def __init__(self, client: APIClient) -> None:
        ...
    
    def get_details(self, sw_spec_id: str | None = ..., state_info: bool = ..., **kwargs: Any) -> dict[str, Any]:
        """Get software specification details.
        If no ``sw_spec_id`` is passed, details for all software specifications are returned.

        :param sw_spec_id: id of the software specification
        :type sw_spec_id: str, optional

        :param state_info: works only when ``sw_spec_id`` is None, instead of returning details of software specs, it returns
            the state of the software specs information (supported, unsupported, deprecated), containing suggested replacement
            in case of unsupported or deprecated software specs
        :type state_info: bool, optional

        :return: metadata of the stored software specification(s)
        :rtype: dict if ``sw_spec_id`` is not None, otherwise ``{"resources": [dict]}``

        **Examples**

        .. code-block:: python

            sw_spec_details = client.software_specifications.get_details(
                sw_spec_uid
            )
            sw_spec_details = client.software_specifications.get_details()
            sw_spec_state_details = client.software_specifications.get_details(
                state_info=True
            )

        """
        ...
    
    async def aget_details(self, sw_spec_id: str | None = ..., state_info: bool = ...) -> dict[str, Any]:
        """Get software specification details asynchronously.
        If no ``sw_spec_id`` is passed, details for all software specifications are returned.

        :param sw_spec_id: id of the software specification
        :type sw_spec_id: str, optional

        :param state_info: works only when `sw_spec_id` is None, instead of returning details of software specs, it returns
            the state of the software specs information (supported, unsupported, deprecated), containing suggested replacement
            in case of unsupported or deprecated software specs
        :type state_info: bool, optional

        :return: metadata of the stored software specification(s)
        :rtype:
          - **dict** - if `sw_spec_id` is not None
          - **{"resources": [dict]}** - if `sw_spec_id` is None

        **Examples**

        .. code-block:: python

            sw_spec_details = await client.software_specifications.aget_details(
                sw_spec_id
            )
            sw_spec_details = await client.software_specifications.aget_details()
            sw_spec_state_details = (
                await client.software_specifications.aget_details(state_info=True)
            )

        """
        ...
    
    def store(self, meta_props: dict) -> dict:
        """Create a software specification.

        :param meta_props: metadata of the space configuration. To see available meta names, use:

            .. code-block:: python

                client.software_specifications.ConfigurationMetaNames.get()

        :type meta_props: dict

        :return: metadata of the stored space
        :rtype: dict

        **Example:**

        .. code-block:: python

            meta_props = {
                client.software_specifications.ConfigurationMetaNames.NAME: "skl_pipeline_heart_problem_prediction",
                client.software_specifications.ConfigurationMetaNames.DESCRIPTION: "description scikit-learn_0.20",
                client.software_specifications.ConfigurationMetaNames.PACKAGE_EXTENSIONS: [],
                client.software_specifications.ConfigurationMetaNames.SOFTWARE_CONFIGURATION: {},
                client.software_specifications.ConfigurationMetaNames.BASE_SOFTWARE_SPECIFICATION: {
                    "guid": "<guid>"
                },
            }

            sw_spec_details = client.software_specifications.store(meta_props)

        """
        ...
    
    async def astore(self, meta_props: dict) -> dict:
        """Create a software specification asynchronously.

        :param meta_props: metadata of the space configuration. To see available meta names, use:

            .. code-block:: python

                client.software_specifications.ConfigurationMetaNames.get()

        :type meta_props: dict

        :return: metadata of the stored space
        :rtype: dict

        **Example:**

        .. code-block:: python

            meta_props = {
                client.software_specifications.ConfigurationMetaNames.NAME: "skl_pipeline_heart_problem_prediction",
                client.software_specifications.ConfigurationMetaNames.DESCRIPTION: "description scikit-learn_0.20",
                client.software_specifications.ConfigurationMetaNames.PACKAGE_EXTENSIONS: [],
                client.software_specifications.ConfigurationMetaNames.SOFTWARE_CONFIGURATION: {},
                client.software_specifications.ConfigurationMetaNames.BASE_SOFTWARE_SPECIFICATION: {
                    "guid": "<guid>"
                },
            }

            sw_spec_details = await client.software_specifications.astore(
                meta_props
            )

        """
        ...
    
    def list(self, limit: int | None = ..., spec_states: list[SpecStates] | None = ...) -> DataFrame:
        """List software specifications in a table format.

        :param limit: limit number of fetched records
        :type limit: int, optional

        :param spec_states: specification state filter, by default shows available, supported and custom software specifications
        :type spec_states: list[SpecStates], optional

        :return: pandas.DataFrame with listed software specifications
        :rtype: pandas.DataFrame

        **Example:**

        .. code-block:: python

            client.software_specifications.list()
        """
        ...
    
    @staticmethod
    def get_id(sw_spec_details: dict) -> str:
        """Get the unique ID of a software specification.

        :param sw_spec_details: metadata of the software specification
        :type sw_spec_details: dict

        :return: unique ID of the software specification
        :rtype: str

        **Example:**

        .. code-block:: python

            software_spec_id = client.software_specifications.get_id(
                sw_spec_details
            )

        """
        ...
    
    @staticmethod
    def get_uid(sw_spec_details: dict) -> str:
        """Get the unique ID of a software specification.

        *Deprecated:* Use ``get_id(sw_spec_details)`` instead.

        :param sw_spec_details: metadata of the software specification
        :type sw_spec_details: dict

        :return: unique ID of the software specification
        :rtype: str

        **Example:**

        .. code-block:: python

            software_spec_id = client.software_specifications.get_uid(
                sw_spec_details
            )

        """
        ...
    
    def get_id_by_name(self, sw_spec_name: str) -> str:
        """Get the unique ID of a software specification.

        :param sw_spec_name: name of the software specification
        :type sw_spec_name: str

        :return: unique ID of the software specification
        :rtype: str

        **Example:**

        .. code-block:: python

            software_spec_id = client.software_specifications.get_id_by_name(
                sw_spec_name
            )

        """
        ...
    
    async def aget_id_by_name(self, sw_spec_name: str) -> str:
        """Get the unique ID of a software specification asynchronously.

        :param sw_spec_name: name of the software specification
        :type sw_spec_name: str

        :return: unique ID of the software specification
        :rtype: str

        **Example:**

        .. code-block:: python

            software_spec_id = await client.software_specifications.aget_id_by_name(
                sw_spec_name
            )

        """
        ...
    
    def get_uid_by_name(self, sw_spec_name: str) -> str:
        """Get the unique ID of a software specification.

        *Deprecated:* Use ``get_id_by_name(self, sw_spec_name)`` instead.

        :param sw_spec_name: name of the software specification
        :type sw_spec_name: str

        :return: unique ID of the software specification
        :rtype: str

        **Example:**

        .. code-block:: python

            asset_uid = client.software_specifications.get_uid_by_name(sw_spec_name)

        """
        ...
    
    @staticmethod
    def get_href(sw_spec_details: dict) -> str:
        """Get the URL of a software specification.

        :param sw_spec_details: details of the software specification
        :type sw_spec_details: dict

        :return: href of the software specification
        :rtype: str

        **Example:**

        .. code-block:: python

            sw_spec_details = client.software_specifications.get_details(sw_spec_id)
            sw_spec_href = client.software_specifications.get_href(sw_spec_details)

        """
        ...
    
    def delete(self, sw_spec_id: str | None = ..., **kwargs: Any) -> str:
        """Delete a software specification.

        :param sw_spec_id: unique ID of the software specification
        :type sw_spec_id: str

        :return: status "SUCCESS" if deletion is successful
        :rtype: Literal["SUCCESS"]
        :raises: ApiRequestFailure if deletion failed

        **Example:**

        .. code-block:: python

            client.software_specifications.delete(sw_spec_id)

        """
        ...
    
    async def adelete(self, sw_spec_id: str) -> str:
        """Delete a software specification asynchronously.

        :param sw_spec_id: unique ID of the software specification
        :type sw_spec_id: str

        :return: status "SUCCESS" if deletion is successful
        :rtype: Literal["SUCCESS"]
        :raises: ApiRequestFailure if deletion failed

        **Example:**

        .. code-block:: python

            await client.software_specifications.adelete(sw_spec_id)

        """
        ...
    
    def add_package_extension(self, sw_spec_id: str | None = ..., pkg_extn_id: str | None = ..., **kwargs: Any) -> str:
        """Add a package extension to a software specification's existing metadata.

        :param sw_spec_id: unique ID of the software specification to be updated
        :type sw_spec_id: str

        :param pkg_extn_id: unique ID of the package extension to be added to the software specification
        :type pkg_extn_id: str

        :return: status
        :rtype: str

        **Example:**

        .. code-block:: python

            client.software_specifications.add_package_extension(
                sw_spec_id, pkg_extn_id
            )

        """
        ...
    
    async def aadd_package_extension(self, sw_spec_id: str, pkg_extn_id: str) -> str:
        """Add a package extension to a software specification's existing metadata asynchronously.

        :param sw_spec_id: unique ID of the software specification to be updated
        :type sw_spec_id: str

        :param pkg_extn_id: unique ID of the package extension to be added to the software specification
        :type pkg_extn_id: str

        :return: status
        :rtype: str

        **Example:**

        .. code-block:: python

            await client.software_specifications.aadd_package_extension(
                sw_spec_id, pkg_extn_id
            )

        """
        ...
    
    def delete_package_extension(self, sw_spec_id: str | None = ..., pkg_extn_id: str | None = ..., **kwargs: Any) -> str:
        """Delete a package extension from a software specification's existing metadata.

        :param sw_spec_id: unique ID of the software specification to be updated
        :type sw_spec_id: str

        :param pkg_extn_id: unique ID of the package extension to be deleted from the software specification
        :type pkg_extn_id: str

        :return: status
        :rtype: str

        **Example:**

        .. code-block:: python

            client.software_specifications.delete_package_extension(
                sw_spec_uid, pkg_extn_id
            )

        """
        ...
    
    async def adelete_package_extension(self, sw_spec_id: str, pkg_extn_id: str) -> str:
        """Delete a package extension from a software specification's existing metadata asynchronously.

        :param sw_spec_id: unique ID of the software specification to be updated
        :type sw_spec_id: str

        :param pkg_extn_id: unique ID of the package extension to be deleted from the software specification
        :type pkg_extn_id: str

        :return: status
        :rtype: str

        **Example:**

        .. code-block:: python

            await client.software_specifications.adelete_package_extension(
                sw_spec_id, pkg_extn_id
            )

        """
        ...
    


