"""
This type stub file was generated by pyright.
"""

import pandas
from pathlib import Path
from typing import Any, Literal, TYPE_CHECKING
from ibm_watsonx_ai.utils.utils import raise_exception_about_unsupported_on_cloud
from ibm_watsonx_ai.wml_resource import WMLResource
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class Volume(WMLResource):
    """Store and manage volume assets."""
    ConfigurationMetaNames = ...
    def __init__(self, client: APIClient) -> None:
        ...
    
    @raise_exception_about_unsupported_on_cloud
    def get_details(self, volume_id: str) -> dict:
        """Get volume details.

        :param volume_id: Unique ID of the volume
        :type volume_id: str

        :return: metadata of the volume details
        :rtype: dict

        **Example:**

        .. code-block:: python

            volume_details = client.volumes.get_details(volume_id)

        """
        ...
    
    @raise_exception_about_unsupported_on_cloud
    def create(self, meta_props: dict[str, Any]) -> dict:
        """Create a volume asset.

        :param meta_props: metadata of the volume asset
        :type meta_props: dict

        :return: metadata of the created volume details
        :rtype: dict

        **Examples**

        Provision new PVC volume:

        .. code-block:: python

            metadata = {
                client.volumes.ConfigurationMetaNames.NAME: 'volume-for-wml-test',
                client.volumes.ConfigurationMetaNames.NAMESPACE: 'wmldev2',
                client.volumes.ConfigurationMetaNames.STORAGE_CLASS: 'nfs-client'
                client.volumes.ConfigurationMetaNames.STORAGE_SIZE: "2G"
            }

            asset_details = client.volumes.store(meta_props=metadata)

        Provision an existing PVC volume:

        .. code-block:: python

            metadata = {
                client.volumes.ConfigurationMetaNames.NAME: "volume-for-wml-test",
                client.volumes.ConfigurationMetaNames.NAMESPACE: "wmldev2",
                client.volumes.ConfigurationMetaNames.EXISTING_PVC_NAME: "volume-for-wml-test",
            }

            asset_details = client.volumes.store(meta_props=metadata)

        """
        ...
    
    @raise_exception_about_unsupported_on_cloud
    def start(self, name: str, wait_for_available: bool = ...) -> Literal["SUCCESS", "FAILED"]:
        """Start the volume service.

        :param name: unique name of the volume to be started
        :type name: str

        :param wait_for_available: flag indicating if method should wait until volume service is available
        :type wait_for_available: bool

        :return: status ("SUCCESS" or "FAILED")
        :rtype: str

        **Example:**

        .. code-block:: python

            client.volumes.start(volume_name)

        """
        ...
    
    @raise_exception_about_unsupported_on_cloud
    def get_volume_status(self, name: str) -> bool:
        """Monitor a volume's file server status.

        :param name: name of the volume to retrieve status for
        :type name: str

        :return: status of the volume (True if volume is available, otherwise False)
        :rtype: bool

        **Example:**

        .. code-block:: python

            client.volumes.get_volume_status(volume_name)

        """
        ...
    
    @raise_exception_about_unsupported_on_cloud
    def upload_file(self, name: str, file_path: str | Path) -> Literal["SUCCESS", "FAILED"]:
        """Upload the data file into stored volume.

        :param name: unique name of the stored volume
        :type name: str
        :param file_path: file to be uploaded into the volume
        :type file_path: str | Path

        :return: status ("SUCCESS" or "FAILED")
        :rtype: str

        **Example:**

        .. code-block:: python

            client.volumes.upload_file("testA", "DRUG.csv")

        """
        ...
    
    @raise_exception_about_unsupported_on_cloud
    def list(self) -> pandas.DataFrame:
        """Lists stored volumes in a table format.

        :return: pandas.DataFrame with listed volumes
        :rtype: pandas.DataFrame

        **Example:**

        .. code-block:: python

            client.volumes.list()
        """
        ...
    
    @staticmethod
    def get_id(volume_details: dict) -> str:
        """Get unique Id of stored volume details.

        :param volume_details: metadata of the stored volume details
        :type volume_details: dict

        :return: unique Id of stored volume asset
        :rtype: str

        **Example:**

        .. code-block:: python

            volume_id = client.volumes.get_id(volume_details)

        """
        ...
    
    @staticmethod
    def get_name(volume_details: dict) -> str:
        """Get unique name of stored volume asset.

        :params volume_details: metadata of the stored volume asset
        :type volume_details: dict

        :return: unique name of stored volume asset
        :rtype: str

        **Example:**

        .. code-block:: python

            volume_name = client.volumes.get_name(asset_details)

        """
        ...
    
    @raise_exception_about_unsupported_on_cloud
    def delete(self, volume_id: str) -> Literal["SUCCESS", "FAILED"]:
        """Delete a volume.

        :param volume_id: unique ID of the volume
        :type volume_id: str

        :return: status ("SUCCESS" or "FAILED")
        :rtype: str

        **Example:**

        .. code-block:: python

            client.volumes.delete(volume_id)

        """
        ...
    
    @raise_exception_about_unsupported_on_cloud
    def stop(self, volume_name: str) -> Literal["SUCCESS", "FAILED"]:
        """Stop the volume service.

        :param volume_name: unique name of the volume
        :type volume_name: str

        :return: status ("SUCCESS" or "FAILED")
        :rtype: str

        **Example:**

        .. code-block:: python

            client.volumes.stop(volume_name)

        """
        ...
    


