"""
This type stub file was generated by pyright.
"""

import httpx
import requests
from typing import Literal, TYPE_CHECKING

if TYPE_CHECKING:
    ...
__all__ = ["WMLClientError", "MissingValue", "MissingMetaProp", "NotUrlNorID", "NoWMLCredentialsProvided", "ApiRequestFailure", "UnexpectedType", "ForbiddenActionForPlan", "NoVirtualDeploymentSupportedForICP", "MissingArgument", "WrongEnvironmentVersion", "CannotAutogenerateBedrockUrl", "WrongMetaProps", "CannotSetProjectOrSpace", "ForbiddenActionForGitBasedProject", "CannotInstallLibrary", "DataStreamError", "WrongLocationProperty", "WrongFileLocation", "EmptyDataSource", "SpaceIDandProjectIDCannotBeNone", "ParamOutOfRange", "InvalidMultipleArguments", "ValidationError", "InvalidValue", "PromptVariablesError", "UnsupportedOperation", "MissingExtension", "InvalidCredentialsError", "AuthenticationError", "ReadingDataTimeoutError", "LoadingDocumentError", "ExceededLimitOfAPICalls", "ResourceIdByNameNotFound", "ResourceByNameNotFound", "MultipleResourceIdByNameFound", "MissingToolRequiredProperties", "VectorStoreSerializationError", "GovCloudEnvironmentConsentError"]
class WMLClientError(Exception):
    def __init__(self, error_msg: str, reason: str | list | None = ..., logg_messages: bool = ...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    


class MissingValue(WMLClientError, ValueError):
    def __init__(self, value_name: str, reason: str | None = ...) -> None:
        ...
    


class MissingMetaProp(MissingValue):
    def __init__(self, name: str, reason: str | None = ...) -> None:
        ...
    


class NotUrlNorID(WMLClientError, ValueError):
    def __init__(self, value_name: str, value: str, reason: str | None = ...) -> None:
        ...
    


class NoWMLCredentialsProvided(MissingValue):
    def __init__(self, reason: str | None = ...) -> None:
        ...
    


class ApiRequestFailure(WMLClientError):
    def __init__(self, error_msg: str, response: requests.Response | httpx.Response, reason: str | None = ...) -> None:
        ...
    


class UnexpectedType(WMLClientError, ValueError):
    def __init__(self, el_name: str, expected_type: type | str, actual_type: type) -> None:
        ...
    


class ForbiddenActionForPlan(WMLClientError):
    def __init__(self, operation_name: str, expected_plans: list, actual_plan: str) -> None:
        ...
    


class NoVirtualDeploymentSupportedForICP(MissingValue):
    def __init__(self, reason: str | None = ...) -> None:
        ...
    


class MissingArgument(WMLClientError, ValueError):
    def __init__(self, value_name: str, reason: str | None = ...) -> None:
        ...
    


class WrongEnvironmentVersion(WMLClientError, ValueError):
    def __init__(self, used_version: str, environment_name: str, supported_versions: tuple) -> None:
        ...
    


class CannotAutogenerateBedrockUrl(WMLClientError, ValueError):
    def __init__(self, e1: Exception, e2: Exception) -> None:
        ...
    


class WrongMetaProps(MissingValue):
    def __init__(self, reason: str | None = ...) -> None:
        ...
    


class MissingWMLComponent(WMLClientError):
    def __init__(self) -> None:
        ...
    


class CannotSetProjectOrSpace(WMLClientError):
    def __init__(self, reason: str) -> None:
        ...
    


class ForbiddenActionForGitBasedProject(WMLClientError):
    def __init__(self, reason: str) -> None:
        ...
    


class CannotInstallLibrary(WMLClientError, ValueError):
    def __init__(self, lib_name: str, reason: str) -> None:
        ...
    


class DataStreamError(WMLClientError, ConnectionError):
    def __init__(self, reason: str) -> None:
        ...
    


class WrongLocationProperty(WMLClientError, ConnectionError):
    def __init__(self, reason: str) -> None:
        ...
    


class WrongFileLocation(WMLClientError, ValueError):
    def __init__(self, reason: str) -> None:
        ...
    


class EmptyDataSource(WMLClientError, ValueError):
    def __init__(self) -> None:
        ...
    


class SpaceIDandProjectIDCannotBeNone(WMLClientError, ValueError):
    def __init__(self, reason: str) -> None:
        ...
    


class ParamOutOfRange(WMLClientError, ValueError):
    def __init__(self, param_name: str, value: int | float, min: int | float, max: int | float) -> None:
        ...
    


class InvalidMultipleArguments(WMLClientError, ValueError):
    def __init__(self, params_names_list: list, reason: str | None = ...) -> None:
        ...
    


class ValidationError(WMLClientError, KeyError):
    def __init__(self, key: str, additional_msg: str | None = ...) -> None:
        ...
    


class PromptVariablesError(WMLClientError, KeyError):
    def __init__(self, key: str) -> None:
        ...
    


class InvalidValue(WMLClientError, ValueError):
    def __init__(self, value_name: str, reason: str | None = ...) -> None:
        ...
    


class UnexpectedKeyWordArgument(WMLClientError, TypeError):
    def __init__(self, value_name: str, reason: str | None = ...) -> None:
        ...
    


class UnsupportedOperation(WMLClientError):
    def __init__(self, reason: str) -> None:
        ...
    


class MissingExtension(WMLClientError, ImportError):
    def __init__(self, extension_name: str, reason: str | None = ..., extra_info: Literal["rag"] | None = ...) -> None:
        ...
    


class MissingMetadata(MissingValue):
    def __init__(self, msg: str, reason: str | None = ...) -> None:
        ...
    


class InvalidCredentialsError(WMLClientError):
    def __init__(self, reason: str | requests.Response | httpx.Response, logg_messages: bool = ...) -> None:
        ...
    


class AuthenticationError(ApiRequestFailure):
    def __init__(self, token_auth_type: str, response: requests.Response | httpx.Response, reason: str | None = ...) -> None:
        ...
    


class ReadingDataTimeoutError(WMLClientError, TimeoutError):
    def __init__(self, timeout: str, time_unit=...) -> None:
        ...
    


class LoadingDocumentError(WMLClientError):
    def __init__(self, document_id, exception) -> None:
        ...
    


class ExceededLimitOfAPICalls(WMLClientError):
    def __init__(self, endpoint: str, reason: str) -> None:
        ...
    


class ResourceIdByNameNotFound(WMLClientError, ValueError):
    def __init__(self, name, resource_name) -> None:
        ...
    


class ResourceByNameNotFound(ResourceIdByNameNotFound):
    ...


class MultipleResourceIdByNameFound(WMLClientError, ValueError):
    def __init__(self, name, resource_name) -> None:
        ...
    


class MissingToolRequiredProperties(WMLClientError, KeyError):
    def __init__(self, required_properties: str) -> None:
        ...
    


class VectorStoreSerializationError(TypeError, ValueError):
    ...


class HybridSemanticChunkerException(WMLClientError):
    ...


class GovCloudEnvironmentConsentError(WMLClientError):
    ...


