"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import TYPE_CHECKING, TypedDict
from ibm_watsonx_ai.foundation_models.schema import RerankParameters
from ibm_watsonx_ai.wml_resource import WMLResource
from ibm_watsonx_ai import APIClient, Credentials

if TYPE_CHECKING:
    ...
class TextDict(TypedDict):
    text: str
    ...


class Rerank(WMLResource):
    """
    Rerank texts based on some queries.

    :param model_id: type of model to use
    :type model_id: str

    :param params: parameters to use during request generation
    :type params: dict, RerankParameters, optional

    :param credentials: credentials for the Watson Machine Learning instance
    :type credentials: Credentials or dict, optional

    :param project_id: ID of the Watson Studio project
    :type project_id: str, optional

    :param space_id: ID of the Watson Studio space
    :type space_id: str, optional

    :param verify: You can pass one of the following as verify:

        * the path to a CA_BUNDLE file
        * the path of directory with certificates of trusted CAs
        * `True` - default path to truststore will be taken
        * `False` - no verification will be made
    :type verify: bool | str | Path, optional

    :param api_client: initialized APIClient object with a set project ID or space ID. If passed, ``credentials`` and ``project_id``/``space_id`` are not required.
    :type api_client: APIClient, optional

    **Example:**

    .. code-block:: python

        from ibm_watsonx_ai import Credentials
        from ibm_watsonx_ai.foundation_models import Rerank

        generate_params = {"truncate_input_tokens": 10}

        wx_ranker = Rerank(
            model_id="<RERANK MODEL>",
            params=generate_params,
            credentials=Credentials(
                api_key=IAM_API_KEY, url="https://us-south.ml.cloud.ibm.com"
            ),
            project_id=project_id,
        )

    """
    def __init__(self, model_id: str, params: dict | RerankParameters | None = ..., credentials: Credentials | None = ..., project_id: str | None = ..., space_id: str | None = ..., verify: bool | str | Path | None = ..., api_client: APIClient | None = ...) -> None:
        ...
    
    def generate(self, query: str, inputs: list[str | TextDict], params: dict | RerankParameters | None = ...) -> dict:
        """
        Calling this method generates the following auditing event.

        :param query: The rank query.
        :type query: str

        :param inputs: The rank input strings.
        :type inputs: list[str], list[dict['text', str]]

        :param params:
        :type params: dict, RerankParameters, optional

        **Example:**

        .. code-block:: python

            query = "As a Youth, I craved excitement while in adulthood I followed Enthusiastic Pursuit."
            inputs = [
                "In my younger years, I often reveled in the excitement of spontaneous adventures and embraced the thrill of the unknown, whereas in my grownup life, I have come to appreciate the comforting stability of a well-established routine.",
                "As a young man, I frequently sought out exhilarating experiences, craving the adrenaline rush of lifes novelties, while as a responsible adult, I have come to understand the profound value of accumulated wisdom and life experience.",
            ]
            response = wx_ranker.generate(query=query, inputs=inputs)

            # Print all response
            print(response)

        """
        ...
    


