"""
This type stub file was generated by pyright.
"""

import logging
from typing import Protocol
from pyarrow import flight

class CallbackSchema(Protocol):
    logger: logging.Logger
    def status_message(self, msg: str) -> None:
        ...
    


class SimplyCallback:
    def __init__(self, *, logger: logging.Logger) -> None:
        ...
    
    def status_message(self, msg: str) -> None:
        ...
    


class HeaderMiddleware(flight.ClientMiddleware):
    def __init__(self, *, headers: dict) -> None:
        ...
    
    def sending_headers(self) -> dict:
        ...
    


class HeaderMiddlewareFactory(flight.ClientMiddlewareFactory):
    def __init__(self, *, headers: dict) -> None:
        ...
    
    def start_call(self, info: flight.CallInfo) -> flight.ClientMiddleware:
        ...
    


