"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.helpers.connections.connections import AssetLocation, CloudAssetLocation, ConnectionAsset, ConnectionAssetLocation, ContainerLocation, DataConnection, DatabaseLocation, DeploymentOutputAssetLocation, FSLocation, NFSConnection, NFSLocation, RemoteFileStorageLocation, S3Connection, S3Location

__all__ = ["AssetLocation", "CloudAssetLocation", "ConnectionAsset", "ConnectionAssetLocation", "ContainerLocation", "DatabaseLocation", "DataConnection", "DeploymentOutputAssetLocation", "FSLocation", "NFSConnection", "NFSLocation", "S3Connection", "S3Location", "RemoteFileStorageLocation"]
