"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import TYPE_CHECKING, Tuple, Union
from pandas import DataFrame

__all__ = ["BaseDataConnection"]
if TYPE_CHECKING:
    ...
class BaseDataConnection(ABC):
    """Base class for DataConnection."""
    def __init__(self) -> None:
        ...
    
    @abstractmethod
    def read(self, with_holdout_split: bool = ...) -> Union[DataFrame, Tuple[DataFrame, DataFrame]]:
        """Download dataset stored in remote data storage."""
        ...
    
    @abstractmethod
    def write(self, data: Union[str, DataFrame], remote_name: str) -> None:
        """Upload file to a remote data storage."""
        ...
    


