"""
This type stub file was generated by pyright.
"""

import pandas as pd
from pathlib import Path
from typing import Iterator

class LocalBatchReader:
    """LocalBatchReader is designed to"""
    def __init__(self, file_path: str | Path, batch_size: int = ...) -> None:
        ...
    
    def __iter__(self) -> Iterator[pd.DataFrame]:
        ...
    


