"""
This type stub file was generated by pyright.
"""

"""
    IBM watsonx.ai REST API

    ## Authorization  ### IBM watsonx.ai Credentials  To start working with API one needs to generate an `access token` using the `username` and `password` available on the Service Credentials tab of the IBM watsonx.ai service instance or also available in the VCAP environment variable.  Example of the Service Credentials:  ```json {     \"url\": \"https://ibm-watson-ml.mybluemix.net\",     \"access_key\": \"ERY9vcBfE4sE+F4g8hcotF9L+j81WXWeZv\",     \"username\": \"c1ef4b80-2ee2-458e-ab92-e9ca97ec657d\",     \"password\": \"030528d4-5a3e-4d4c-9258-5d553513be6f\" } ```  Example of obtaining `access token` from Token Endpoint using HTTP Basic Auth (for details please refer to Token section below):  ` curl --basic --user username:password https://ibm-watson-ml.mybluemix.net/v2/identity/token `   ### Apache Spark Service Credentials  The IBM watsonx.ai co-operates with the Apache Spark as a Service to deploy pipeline models. For API methods requiring Apache Spark Service instance a custom header: `X-Spark-Service-Instance` with Service Credentials must be specified. The header value is a **base64 encoded** string with the Service Credentials JSON data.  [Example of API method requiring Apache Spark Service](https://console.ng.bluemix.net/docs/services/PredictiveModeling/index-gentopic1.html#pm_service_api_spark_batch)

    OpenAPI spec version: 2.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class ArrayModelVersionOutput:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, resources=...) -> None:
        """
        ArrayModelVersionOutput - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def resources(self): # -> None:
        """
        Gets the resources of this ArrayModelVersionOutput.


        :return: The resources of this ArrayModelVersionOutput.
        :rtype: list[ModelVersionOutput]
        """
        ...
    
    @resources.setter
    def resources(self, resources): # -> None:
        """
        Sets the resources of this ArrayModelVersionOutput.


        :param resources: The resources of this ArrayModelVersionOutput.
        :type: list[ModelVersionOutput]
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


