"""
This type stub file was generated by pyright.
"""

class ArtifactVersionRepository:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self) -> None:
        """
        ArtifactVersionRepository - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def guid(self): # -> None:
        """
        Gets the guid of this ArtifactVersionRepository.


        :return: The guid of this ArtifactVersionRepository.
        :rtype: UUID
        """
        ...
    
    @guid.setter
    def guid(self, guid): # -> None:
        """
        Sets the guid of this ArtifactVersionRepository.


        :param guid: The guid of this ArtifactVersionRepository.
        :type: UUID
        """
        ...
    
    @property
    def url(self): # -> None:
        """
        Gets the url of this ArtifactVersionRepository.


        :return: The url of this ArtifactVersionRepository.
        :rtype: str
        """
        ...
    
    @url.setter
    def url(self, url): # -> None:
        """
        Sets the url of this ArtifactVersionRepository.


        :param url: The url of this ArtifactVersionRepository.
        :type: str
        """
        ...
    
    @property
    def content_url(self): # -> None:
        """
        Gets the content_url of this ArtifactVersionRepository.


        :return: The content_url of this ArtifactVersionRepository.
        :rtype: str
        """
        ...
    
    @content_url.setter
    def content_url(self, content_url): # -> None:
        """
        Sets the content_url of this ArtifactVersionRepository.


        :param content_url: The content_url of this ArtifactVersionRepository.
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


