"""
This type stub file was generated by pyright.
"""

class BatchDeployOutput:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, meta=..., entity=...) -> None:
        """
        BatchDeployOutput - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def meta(self): # -> None:
        """
        Gets the meta of this BatchDeployOutput.


        :return: The meta of this BatchDeployOutput.
        :rtype: BatchDeployOutputMeta
        """
        ...
    
    @meta.setter
    def meta(self, meta): # -> None:
        """
        Sets the meta of this BatchDeployOutput.


        :param meta: The meta of this BatchDeployOutput.
        :type: BatchDeployOutputMeta
        """
        ...
    
    @property
    def entity(self): # -> None:
        """
        Gets the entity of this BatchDeployOutput.


        :return: The entity of this BatchDeployOutput.
        :rtype: BatchDeployOutputEntity
        """
        ...
    
    @entity.setter
    def entity(self, entity): # -> None:
        """
        Sets the entity of this BatchDeployOutput.


        :param entity: The entity of this BatchDeployOutput.
        :type: BatchDeployOutputEntity
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


