"""
This type stub file was generated by pyright.
"""

class ColsOutput:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self) -> None:
        """
        ColsOutput - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


