"""
This type stub file was generated by pyright.
"""

class ContentLocation:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, url=..., connection=..., source=...) -> None:
        """
        ContentLocation - location of model content defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def url(self): # -> None:
        """
        Gets the temp cos url of this ContentLocation.

        :return: The url of this ContentLocation.
        :rtype: dict(str, str)
        """
        ...
    
    @url.setter
    def url(self, url): # -> None:
        """
        Sets the url of temp cos of this ContentLocation.

        :param connection: The connection of this ContentLocation.
        :type: dict(str, str)
        """
        ...
    
    @property
    def connection(self): # -> None:
        """
        Gets the connection of this ContentLocation.

        :return: The connection of this ContentLocation.
        :rtype: dict(str, str)
        """
        ...
    
    @connection.setter
    def connection(self, connection): # -> None:
        """
        Sets the connection of this ContentLocation.

        :param connection: The connection of this ContentLocation.
        :type: dict(str, str)
        """
        ...
    
    @property
    def source(self): # -> None:
        """
        Gets the source of this ContentLocation.
        Details of the resource in the content source

        :return: The source of this ContentLocation.
        :rtype: dict(str, str)
        """
        ...
    
    @source.setter
    def source(self, source): # -> None:
        """
        Sets the source of this ContentLocation.
        Details of the resource in the content data source

        :param source: The source of this ContentLocation.
        :type: dict(str, str)
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


