"""
This type stub file was generated by pyright.
"""

class ContentStatus:
    def __init__(self, state=..., message=..., failure=...) -> None:
        """
        ModelMetrics - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def state(self): # -> None:
        """
        Gets the code of this ContentStatus.


        :return: The code of this ContentStatus.
        :rtype: str
        """
        ...
    
    @state.setter
    def state(self, state): # -> None:
        """
        Sets the state of this ContentStatus.


        :param state: The state of this ContentStatus.
        :type: str
        """
        ...
    
    @property
    def message(self): # -> None:
        """
        Gets the error message of this ContentStatus.


        :return: The error message of this ContentStatus.
        :rtype: str
        """
        ...
    
    @message.setter
    def message(self, message): # -> None:
        """
        Sets the message of this ContentStatus.


        :param message: The message of this ContentStatus.
        :type: str
        """
        ...
    
    @property
    def failure(self): # -> None:
        """
        Gets the details for the failure of this ContentStatus.


        :return: The the details for the failure of this ContetnStatus.
        :rtype: ErrorSchemaRepository
        """
        ...
    
    @failure.setter
    def failure(self, failure): # -> None:
        """
        Sets the failure details of this ContentStatus.


        :param failure: The failure details of this ContentStatus.
        :type: ErrorSchemaRepository
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


