"""
This type stub file was generated by pyright.
"""

class FrameworkOutputRepository:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=..., version=..., runtime=..., runtimes=..., libraries=...) -> None:
        """
        FrameworkOutputRepository - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def name(self): # -> None:
        """
        Gets the name of this FrameworkOutputRepository.


        :return: The name of this FrameworkOutputRepository.
        :rtype: str
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """
        Sets the name of this FrameworkOutputRepository.


        :param name: The name of this FrameworkOutputRepository.
        :type: str
        """
        ...
    
    @property
    def version(self): # -> None:
        """
        Gets the version of this FrameworkOutputRepository.


        :return: The version of this FrameworkOutputRepository.
        :rtype: str
        """
        ...
    
    @version.setter
    def version(self, version): # -> None:
        """
        Sets the version of this FrameworkOutputRepository.


        :param version: The version of this FrameworkOutputRepository.
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    @property
    def runtimes(self): # -> None:
        """
        Gets the runtimes of this FrameworkOutputRepository.


        :return: The runtimes of this FrameworkOutputRepository.
        :rtype: list[FrameworkOutputRepositoryRuntimes]
        """
        ...
    
    @runtimes.setter
    def runtimes(self, runtimes): # -> None:
        """
        Sets the runtimes of this FrameworkOutputRepository.


        :param runtimes: The runtimes of this FrameworkOutputRepository.
        :type: list[FrameworkOutputRepositoryRuntimes]
        """
        ...
    
    @property
    def libraries(self): # -> None:
        """
        Gets the libraries of this FrameworkOutputRepository.


        :return: The libraries of this FrameworkOutputRepository.
        :rtype: list[FrameworkOutputRepositoryLibraries]
        """
        ...
    
    @libraries.setter
    def libraries(self, libraries): # -> None:
        """
        Sets the libraries of this FrameworkOutputRepository.

        :param runtimes: The runtimes of this FrameworkOutputRepository.
        :type: list[FrameworkOutputRepositoryLibraries]
        """
        ...
    
    @property
    def runtime(self): # -> None:
        """
        Gets the runtime of this FrameworkOutputRepository.


        :return: The runtimes of this FrameworkOutputRepository.
        :rtype: list[FrameworkOutputRepositoryRuntimes]
        """
        ...
    
    @runtime.setter
    def runtime(self, runtime): # -> None:
        """
        Sets the runtimes of this FrameworkOutputRepository.


        :param runtimes: The runtimes of this FrameworkOutputRepository.
        :type: list[FrameworkOutputRepositoryRuntimes]
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


