"""
This type stub file was generated by pyright.
"""

class HyperParameters:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=..., string_value=..., double_value=..., int_value=...) -> None:
        """
        ContentLocation - location of model content defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def name(self): # -> None:
        """
        Gets the temp cos url of this ContentLocation.

        :return: The url of this ContentLocation.
        :rtype: dict(str, str)
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """
        Sets the url of temp cos of this ContentLocation.

        :param connection: The connection of this ContentLocation.
        :type: dict(str, str)
        """
        ...
    
    @property
    def string_value(self): # -> None:
        """
        Gets the value of this HyperParameters.


        :return: The value of this HyperParameters.
        :rtype: str
        """
        ...
    
    @string_value.setter
    def string_value(self, string_value): # -> None:
        """
        Sets the value of this HyperParameters.


        :param value: The value of this HyperParameters.
        :type: str
        """
        ...
    
    @property
    def double_value(self): # -> None:
        """
        Gets the value of this HyperParameters.


        :return: The value of this HyperParameters.
        :rtype: float
        """
        ...
    
    @double_value.setter
    def double_value(self, double_value): # -> None:
        """
        Sets the value of this HyperParameters.


        :param value: The value of this HyperParameters.
        :type: float
        """
        ...
    
    @property
    def int_value(self): # -> None:
        """
        Gets the value of this HyperParameters.


        :return: The value of this HyperParameters.
        :rtype: int
        """
        ...
    
    @int_value.setter
    def int_value(self, int_value): # -> None:
        """
        Sets the value of this HyperParameters.


        :param value: The value of this HyperParameters.
        :type: int
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


