"""
This type stub file was generated by pyright.
"""

class InternalInputBatch:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, source=..., connection=...) -> None:
        """
        InternalInputBatch - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def source(self): # -> None:
        """
        Gets the source of this InternalInputBatch.
        source parameters required by Ingest to read data

        :return: The source of this InternalInputBatch.
        :rtype: object
        """
        ...
    
    @source.setter
    def source(self, source): # -> None:
        """
        Sets the source of this InternalInputBatch.
        source parameters required by Ingest to read data

        :param source: The source of this InternalInputBatch.
        :type: object
        """
        ...
    
    @property
    def connection(self): # -> None:
        """
        Gets the connection of this InternalInputBatch.


        :return: The connection of this InternalInputBatch.
        :rtype: Connection
        """
        ...
    
    @connection.setter
    def connection(self, connection): # -> None:
        """
        Sets the connection of this InternalInputBatch.


        :param connection: The connection of this InternalInputBatch.
        :type: Connection
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


