"""
This type stub file was generated by pyright.
"""

class MetaObjectRepositoryMetadata:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, guid=..., created_at=..., modified_at=..., href=..., id=..., name=..., owner=..., space_id=..., project_id=...) -> None:
        """
        MetaObjectRepositoryMetadata - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def guid(self): # -> None:
        """
        Gets the guid of this MetaObjectRepositoryMetadata.


        :return: The guid of this MetaObjectRepositoryMetadata.
        :rtype: str
        """
        ...
    
    @guid.setter
    def guid(self, guid): # -> None:
        """
        Sets the guid of this MetaObjectRepositoryMetadata.


        :param guid: The guid of this MetaObjectRepositoryMetadata.
        :type: str
        """
        ...
    
    @property
    def created_at(self): # -> None:
        """
        Gets the created_at of this MetaObjectRepositoryMetadata.


        :return: The created_at of this MetaObjectRepositoryMetadata.
        :rtype: datetime
        """
        ...
    
    @created_at.setter
    def created_at(self, created_at): # -> None:
        """
        Sets the created_at of this MetaObjectRepositoryMetadata.


        :param created_at: The created_at of this MetaObjectRepositoryMetadata.
        :type: datetime
        """
        ...
    
    @property
    def modified_at(self): # -> None:
        """
        Gets the modified_at of this MetaObjectRepositoryMetadata.


        :return: The modified_at of this MetaObjectRepositoryMetadata.
        :rtype: datetime
        """
        ...
    
    @modified_at.setter
    def modified_at(self, modified_at): # -> None:
        """
        Sets the modified_at of this MetaObjectRepositoryMetadata.


        :param modified_at: The modified_at of this MetaObjectRepositoryMetadata.
        :type: datetime
        """
        ...
    
    @property
    def href(self): # -> None:
        """
        Gets the href of this MetaObjectRepositoryMetadata.


        :return: The href of this MetaObjectRepositoryMetadata.
        :rtype: str
        """
        ...
    
    @href.setter
    def href(self, href): # -> None:
        """
        Sets the href of this MetaObjectRepositoryMetadata.


        :param href: The href of this MetaObjectRepositoryMetadata.
        :type: str
        """
        ...
    
    @property
    def id(self):
        """
        Gets the id of this MetaObjectMetadata.


        :return: The id of this MetaObjectMetadata.
        :rtype: str
        """
        ...
    
    @id.setter
    def id(self, id): # -> None:
        """
        Sets the id of this MetaObjectMetadata.


        :param id: The guid of this MetaObjectMetadata.
        :type: str
        """
        ...
    
    @property
    def name(self):
        """
        Gets the name of this MetaObjectMetadata.


        :return: The name of this MetaObjectMetadata.
        :rtype: str
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """
        Sets the name of this MetaObjectMetadata.


        :param name: The name of this MetaObjectMetadata.
        :type: str
        """
        ...
    
    @property
    def owner(self):
        """
        Gets the owner of this MetaObjectMetadata.


        :return: The owner of this MetaObjectMetadata.
        :rtype: str
        """
        ...
    
    @owner.setter
    def owner(self, owner): # -> None:
        """
        Sets the owner of this MetaObjectMetadata.


        :param owner: The owner of this MetaObjectMetadata.
        :type: str
        """
        ...
    
    @property
    def space_id(self):
        """
        Gets the space_id of this MetaObjectMetadata.


        :return: The space_id of this MetaObjectMetadata.
        :rtype: str
        """
        ...
    
    @space_id.setter
    def space_id(self, space_id): # -> None:
        """
        Sets the space_id of this MetaObjectMetadata.


        :param space_id: The space_id of this MetaObjectMetadata.
        :type: str
        """
        ...
    
    @property
    def project_id(self):
        """
        Gets the project_id of this MetaObjectMetadata.


        :return: The project_id of this MetaObjectMetadata.
        :rtype: str
        """
        ...
    
    @project_id.setter
    def project_id(self, project_id): # -> None:
        """
        Sets the project_id of this MetaObjectMetadata.


        :param project_id: The project_id of this MetaObjectMetadata.
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


