"""
This type stub file was generated by pyright.
"""

class MlAssetsUploadContentOutputMetadata:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self) -> None:
        """
        MlAssetsUploadContentOutputMetadata - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def guid(self): # -> None:
        """
        Gets the guid of this MlAssetsUploadContentOutputMetadata.


        :return: The guid of this MlAssetsUploadContentOutputMetadata.
        :rtype: str
        """
        ...
    
    @guid.setter
    def guid(self, guid): # -> None:
        """
        Sets the guid of this MlAssetsUploadContentOutputMetadata.


        :param guid: The guid of this MlAssetsUploadContentOutputMetadata.
        :type: str
        """
        ...
    
    @property
    def created_at(self): # -> None:
        """
        Gets the created_at of this MlAssetsUploadContentOutputMetadata.


        :return: The created_at of this MlAssetsUploadContentOutputMetadata.
        :rtype: datetime
        """
        ...
    
    @created_at.setter
    def created_at(self, created_at): # -> None:
        """
        Sets the created_at of this MlAssetsUploadContentOutputMetadata.


        :param created_at: The created_at of this MlAssetsUploadContentOutputMetadata.
        :type: datetime
        """
        ...
    
    @property
    def modified_at(self): # -> None:
        """
        Gets the modified_at of this MlAssetsUploadContentOutputMetadata.


        :return: The modified_at of this MlAssetsUploadContentOutputMetadata.
        :rtype: datetime
        """
        ...
    
    @modified_at.setter
    def modified_at(self, modified_at): # -> None:
        """
        Sets the modified_at of this MlAssetsUploadContentOutputMetadata.


        :param modified_at: The modified_at of this MlAssetsUploadContentOutputMetadata.
        :type: datetime
        """
        ...
    
    @property
    def url(self): # -> None:
        """
        Gets the url of this MlAssetsUploadContentOutputMetadata.


        :return: The url of this MlAssetsUploadContentOutputMetadata.
        :rtype: str
        """
        ...
    
    @url.setter
    def url(self, url): # -> None:
        """
        Sets the url of this MlAssetsUploadContentOutputMetadata.


        :param url: The url of this MlAssetsUploadContentOutputMetadata.
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


