"""
This type stub file was generated by pyright.
"""

class MlAssetsGetPreSignedUrlOutput:
    def __init__(self, contentUrl=...) -> None:
        ...
    
    @property
    def contentUrl(self): # -> None:
        ...
    
    @contentUrl.setter
    def contentUrl(self, contentUrl): # -> None:
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


