"""
This type stub file was generated by pyright.
"""

class ModelOutputEntityPipelineVersion:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, guid=..., href=...) -> None:
        """
        ModelOutputEntityPipelineVersion - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def guid(self): # -> None:
        """
        Gets the guid of this ModelOutputEntityPipelineVersion.
        ID of the pipeline version from which the current model was created.

        :return: The guid of this ModelOutputEntityPipelineVersion.
        :rtype: str
        """
        ...
    
    @guid.setter
    def guid(self, guid): # -> None:
        """
        Sets the guid of this ModelOutputEntityPipelineVersion.
        ID of the pipeline version from which the current model was created.

        :param guid: The guid of this ModelOutputEntityPipelineVersion.
        :type: str
        """
        ...
    
    @property
    def href(self): # -> None:
        """
        Gets the href of this ModelOutputEntityPipelineVersion.
        Href of the pipeline version from which the current model was created.

        :return: The href of this ModelOutputEntityPipelineVersion.
        :rtype: str
        """
        ...
    
    @href.setter
    def href(self, href): # -> None:
        """
        Sets the href of this ModelOutputEntityPipelineVersion.
        Href of the pipeline version from which the current model was created.

        :param href: The href of this ModelOutputEntityPipelineVersion.
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


