"""
This type stub file was generated by pyright.
"""

class ModelMetricsValues:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=..., value=...) -> None:
        """
        ModelMetricsValues - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def name(self): # -> None:
        """
        Gets the name of this ModelMetricsValues.
        The name of the metric

        :return: The name of this ModelMetricsValues.
        :rtype: str
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """
        Sets the name of this ModelMetricsValues.
        The name of the metric

        :param name: The name of this ModelMetricsValues.
        :type: str
        """
        ...
    
    @property
    def value(self): # -> None:
        """
        Gets the value of this ModelMetricsValues.
        The mesured value

        :return: The value of this ModelMetricsValues.
        :rtype: float
        """
        ...
    
    @value.setter
    def value(self, value): # -> None:
        """
        Sets the value of this ModelMetricsValues.
        The mesured value

        :param value: The value of this ModelMetricsValues.
        :type: float
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


