"""
This type stub file was generated by pyright.
"""

class ModelMetrics:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, values=..., timestamp=...) -> None:
        """
        ModelMetrics - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def values(self): # -> None:
        """
        Gets the values of this ModelMetrics.


        :return: The values of this ModelMetrics.
        :rtype: list[ModelMetricsValues]
        """
        ...
    
    @values.setter
    def values(self, values): # -> None:
        """
        Sets the values of this ModelMetrics.


        :param values: The values of this ModelMetrics.
        :type: list[ModelMetricsValues]
        """
        ...
    
    @property
    def timestamp(self): # -> None:
        """
        Gets the timestamp of this ModelMetrics.
        The timestamp when the metric was mesured

        :return: The timestamp of this ModelMetrics.
        :rtype: datetime
        """
        ...
    
    @timestamp.setter
    def timestamp(self, timestamp): # -> None:
        """
        Sets the timestamp of this ModelMetrics.
        The timestamp when the metric was mesured

        :param timestamp: The timestamp of this ModelMetrics.
        :type: datetime
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


