"""
This type stub file was generated by pyright.
"""

class ModelVersionInput:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, training_data_ref=..., evaluation=...) -> None:
        """
        ModelVersionInput - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def training_data_ref(self): # -> None:
        """
        Gets the training_data_ref of this ModelVersionInput.


        :return: The training_data_ref of this ModelVersionInput.
        :rtype: ModelTrainingDataRef
        """
        ...
    
    @training_data_ref.setter
    def training_data_ref(self, training_data_ref): # -> None:
        """
        Sets the training_data_ref of this ModelVersionInput.


        :param training_data_ref: The training_data_ref of this ModelVersionInput.
        :type: ModelTrainingDataRef
        """
        ...
    
    @property
    def evaluation(self): # -> None:
        """
        Gets the evaluation of this ModelVersionInput.
        Definition of the evaluation method used for pipeline models

        :return: The evaluation of this ModelVersionInput.
        :rtype: EvaluationDefinition
        """
        ...
    
    @evaluation.setter
    def evaluation(self, evaluation): # -> None:
        """
        Sets the evaluation of this ModelVersionInput.
        Definition of the evaluation method used for pipeline models

        :param evaluation: The evaluation of this ModelVersionInput.
        :type: EvaluationDefinition
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


