"""
This type stub file was generated by pyright.
"""

class PipelineInput:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=..., description=..., author=..., type=..., runtime_environment=...) -> None:
        """
        PipelineInput - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def name(self): # -> None:
        """
        Gets the name of this PipelineInput.
        Name of the pipeline

        :return: The name of this PipelineInput.
        :rtype: str
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """
        Sets the name of this PipelineInput.
        Name of the pipeline

        :param name: The name of this PipelineInput.
        :type: str
        """
        ...
    
    @property
    def description(self): # -> None:
        """
        Gets the description of this PipelineInput.
        Description of the pipeline

        :return: The description of this PipelineInput.
        :rtype: str
        """
        ...
    
    @description.setter
    def description(self, description): # -> None:
        """
        Sets the description of this PipelineInput.
        Description of the pipeline

        :param description: The description of this PipelineInput.
        :type: str
        """
        ...
    
    @property
    def author(self): # -> None:
        """
        Gets the author of this PipelineInput.
        Author of the pipeline

        :return: The author of this PipelineInput.
        :rtype: ArtifactAuthor
        """
        ...
    
    @author.setter
    def author(self, author): # -> None:
        """
        Sets the author of this PipelineInput.
        Author of the pipeline

        :param author: The author of this PipelineInput.
        :type: ArtifactAuthor
        """
        ...
    
    @property
    def type(self): # -> None:
        """
        Gets the type of this PipelineInput.
        Type of the pipeline

        :return: The type of this PipelineInput.
        :rtype: PipelineType
        """
        ...
    
    @type.setter
    def type(self, type): # -> None:
        """
        Sets the type of this PipelineInput.
        Type of the pipeline

        :param type: The type of this PipelineInput.
        :type: PipelineType
        """
        ...
    
    @property
    def runtime_environment(self): # -> None:
        """
        Gets the runtime_environment of this PipelineInput.
        runtime environment of caller

        :return: The runtime_environment of this PipelineInput.
        :rtype: RuntimeEnvironment
        """
        ...
    
    @runtime_environment.setter
    def runtime_environment(self, runtime_environment): # -> None:
        """
        Sets the runtime_environment of this PipelineInput.
        runtime environment of caller

        :param runtime_environment: The runtime_environment of this PipelineInput.
        :type: RuntimeEnvironment
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


