"""
This type stub file was generated by pyright.
"""

class RuntimeSpecDefinitionInput:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=..., description=..., platform=..., custom_libraries=..., public_libraries=...) -> None:
        """
        RuntimeSpecDefinitionInput - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def name(self): # -> None:
        """
        Gets the name of this RuntimeSpecDefinitionInput.


        :return: The name of this RuntimeSpecDefinitionInput.
        :rtype: str
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """
        Sets the name of this RuntimeSpecDefinitionInput.


        :param name: The name of this RuntimeSpecDefinitionInput.
        :type: str
        """
        ...
    
    @property
    def description(self): # -> None:
        """
        Gets the description of this RuntimeSpecDefinitionInput.


        :return: The description of this RuntimeSpecDefinitionInput.
        :rtype: str
        """
        ...
    
    @description.setter
    def description(self, description): # -> None:
        """
        Sets the description of this RuntimeSpecDefinitionInput.


        :param description: The description of this RuntimeSpecDefinitionInput.
        :type: str
        """
        ...
    
    @property
    def platform(self): # -> None:
        """
        Gets the platform of this RuntimeSpecDefinitionInput.


        :return: The platform of this RuntimeSpecDefinitionInput.
        :rtype: RuntimeSpecDefinitionInputPlatform
        """
        ...
    
    @platform.setter
    def platform(self, platform): # -> None:
        """
        Sets the platform of this RuntimeSpecDefinitionInput.


        :param platform: The platform of this RuntimeSpecDefinitionInput.
        :type: RuntimeSpecDefinitionInputPlatform
        """
        ...
    
    @property
    def custom_libraries(self): # -> None:
        """
        Gets the custom_libraries of this RuntimeSpecDefinitionInput.


        :return: The custom_libraries of this RuntimeSpecDefinitionInput.
        :rtype: RuntimeSpecDefinitionInputCustomLibraries
        """
        ...
    
    @custom_libraries.setter
    def custom_libraries(self, custom_libraries): # -> None:
        """
        Sets the custom_libraries of this RuntimeSpecDefinitionInput.


        :param custom_libraries: The custom_libraries of this RuntimeSpecDefinitionInput.
        :type: RuntimeSpecDefinitionInputCustomLibraries
        """
        ...
    
    @property
    def public_libraries(self): # -> None:
        """
        Gets the public_libraries of this RuntimeSpecDefinitionInput.
        Array of public libraries

        :return: The public_libraries of this RuntimeSpecDefinitionInput.
        :rtype: list[RuntimeSpecDefinitionInputPublicLibraries]
        """
        ...
    
    @public_libraries.setter
    def public_libraries(self, public_libraries): # -> None:
        """
        Sets the public_libraries of this RuntimeSpecDefinitionInput.
        Array of public libraries

        :param public_libraries: The public_libraries of this RuntimeSpecDefinitionInput.
        :type: list[RuntimeSpecDefinitionInputPublicLibraries]
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


