"""
This type stub file was generated by pyright.
"""

class SparkService:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, credentials=..., version=...) -> None:
        """
        SparkService - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def credentials(self): # -> None:
        """
        Gets the credentials of this SparkService.
        Spark service credntials from VCAP

        :return: The credentials of this SparkService.
        :rtype: object
        """
        ...
    
    @credentials.setter
    def credentials(self, credentials): # -> None:
        """
        Sets the credentials of this SparkService.
        Spark service credntials from VCAP

        :param credentials: The credentials of this SparkService.
        :type: object
        """
        ...
    
    @property
    def version(self): # -> None:
        """
        Gets the version of this SparkService.
        The Spark version to be used (default: 2.0)

        :return: The version of this SparkService.
        :rtype: str
        """
        ...
    
    @version.setter
    def version(self, version): # -> None:
        """
        Sets the version of this SparkService.
        The Spark version to be used (default: 2.0)

        :param version: The version of this SparkService.
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


