"""
This type stub file was generated by pyright.
"""

class StreamInputInternal:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, connection=..., source=...) -> None:
        """
        StreamInputInternal - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def connection(self): # -> None:
        """
        Gets the connection of this StreamInputInternal.
        Service credential of input  messagehub

        :return: The connection of this StreamInputInternal.
        :rtype: dict(str, str)
        """
        ...
    
    @connection.setter
    def connection(self, connection): # -> None:
        """
        Sets the connection of this StreamInputInternal.
        Service credential of input  messagehub

        :param connection: The connection of this StreamInputInternal.
        :type: dict(str, str)
        """
        ...
    
    @property
    def source(self): # -> None:
        """
        Gets the source of this StreamInputInternal.
        Additional configuration for the connection object

        :return: The source of this StreamInputInternal.
        :rtype: dict(str, str)
        """
        ...
    
    @source.setter
    def source(self, source): # -> None:
        """
        Sets the source of this StreamInputInternal.
        Additional configuration for the connection object

        :param source: The source of this StreamInputInternal.
        :type: dict(str, str)
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


