"""
This type stub file was generated by pyright.
"""

class StreamOutput:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, metadata=..., entity=...) -> None:
        """
        StreamOutput - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def metadata(self): # -> None:
        """
        Gets the metadata of this StreamOutput.


        :return: The metadata of this StreamOutput.
        :rtype: MetaObjectMetadata
        """
        ...
    
    @metadata.setter
    def metadata(self, metadata): # -> None:
        """
        Sets the metadata of this StreamOutput.


        :param metadata: The metadata of this StreamOutput.
        :type: MetaObjectMetadata
        """
        ...
    
    @property
    def entity(self): # -> None:
        """
        Gets the entity of this StreamOutput.


        :return: The entity of this StreamOutput.
        :rtype: object
        """
        ...
    
    @entity.setter
    def entity(self, entity): # -> None:
        """
        Sets the entity of this StreamOutput.


        :param entity: The entity of this StreamOutput.
        :type: object
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


