"""
This type stub file was generated by pyright.
"""

class TagRepository:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, value=..., description=...) -> None:
        """
        TagRepository - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def value(self): # -> None:
        """
        Gets the value of this TagRepository.


        :return: The value of this TagRepository.
        :rtype: str
        """
        ...
    
    @value.setter
    def value(self, value): # -> None:
        """
        Sets the value of this TagRepository.


        :param value: The value of this TagRepository.
        :type: str
        """
        ...
    
    @property
    def description(self): # -> None:
        """
        Gets the description of this TagRepository.


        :return: The description of this TagRepository.
        :rtype: str
        """
        ...
    
    @description.setter
    def description(self, description): # -> None:
        """
        Sets the description of this TagRepository.


        :param description: The description of this TagRepository.
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


