"""
This type stub file was generated by pyright.
"""

class TrainingModels:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, href=...) -> None:
        """
        TrainingModels - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute href
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute href
                                  and the value is json key in definition.
        """
        ...
    
    @property
    def href(self): # -> None:
        """
        Gets the href of this TrainingModels.


        :return: The href of this TrainingModels.
        :rtype: str
        """
        ...
    
    @href.setter
    def href(self, href): # -> None:
        """
        Sets the href of this TrainingModels.


        :param href: The href of this TrainingModels.
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """
        Returns the model properties as a dict
        """
        ...
    
    def to_str(self): # -> str:
        """
        Returns the string representation of the model
        """
        ...
    
    def __repr__(self): # -> str:
        """
        For `print` and `pprint`
        """
        ...
    
    def __eq__(self, other) -> bool:
        """
        Returns true if both objects are equal
        """
        ...
    
    def __ne__(self, other) -> bool:
        """
        Returns true if both objects are not equal
        """
        ...
    


