"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.libs.repo.mlrepository import ArtifactReader

class ContentReader(ArtifactReader):
    """
    Reader which read content of pipeline/pipeline model from repository using href.

    :param str content_href: href to content, returned by repository api
    :param MLRepositoryApi: repository api object
    """
    def __init__(self, content_href, repository_api, download_href=...) -> None:
        ...
    
    def read(self):
        """
        Returns stream object with content of pipeline/pipeline model.

        :return: binary stream
        :rtype: HTTPResponse (from urllib3)
        """
        ...
    
    def close(self): # -> None:
        """
        Closes stream to content.
        """
        ...
    


