"""
This type stub file was generated by pyright.
"""

logger = ...
class FunctionCollection:
    """
    Client operating on functions in repository service.

    :param str base_path: base url to watsonx.ai instance
    :param MLRepositoryApi repository_api: client connecting to repository rest api
    :param MLRepositoryClient client: high level client used for simplification and argument for constructors
    """
    def __init__(self, base_path, repository_api, client) -> None:
        ...
    
    def all(self, expand=..., runtime_name=..., runtime_id=...): # -> list[Any]:
        """
        Gets info about all functions which belong to this user.

        Not complete information is provided by all(). To get detailed information about function use get().

        :return: info about functions
        :rtype: list[FunctionArtifact]
        """
        ...
    
    def get(self, artifact_id, expand=...): # -> WmlFunctionArtifact:
        """
        Gets detailed information about function.

        :param str artifact_id: uid used to identify function
        :return: returned object has all attributes of FunctionArtifact
        :rtype: FunctionArtifact
        """
        ...
    
    def revisions(self, artifact_id, expand=...): # -> list[type[FunctionArtifact]]:
        """
        Gets all available revisions.

        :param str artifact_id: uid used to identify function
        :return: ???
        :rtype: list[str]
        """
        ...
    
    def revision(self, artifact_id, rev, expand): # -> WmlFunctionArtifact:
        """
        Gets Function revision with given artifact_id and ver
        :param str artifact_id: uid used to identify function
        :param str rev: uid used to identify revision of function
        :return: FunctionArtifact(FunctionLoader) -- returned object has all attributes of FunctionArtifact
        """
        ...
    
    def revision_from_href(self, artifact_revision_href, expand=...): # -> WmlFunctionArtifact:
        """
        Gets function revision from given href

        :param str artifact_revision_href: href identifying artifact and revision
        :return: returned object has all attributes of FunctionArtifact
        :rtype: FunctionArtifact(FunctionLoader)
        """
        ...
    
    def save(self, artifact): # -> WmlFunctionArtifact:
        """
        Saves function in repository service.

        :param FunctionArtifact artifact: artifact to be saved in the repository service
        :return: saved artifact with changed MetaProps
        :rtype: FunctionArtifact
        """
        ...
    
    def patch(self, patch_input, latest_rev_url): # -> WmlFunctionArtifact:
        ...
    
    def remove(self, function_id): # -> None:
        """
        Removes function with given id.

        :param str function_id: uid used to identify function
        """
        ...
    
    @staticmethod
    def prepare_function_patch_input(patch_input): # -> list[Any] | None:
        ...
    


