"""
This type stub file was generated by pyright.
"""

lib_checker = ...
class FunctionAdapter:
   """
    Adapter creating function artifact using output from service.
    """
   def __init__(self, function_output, client) -> None:
      ...
   
   def artifact(self): # -> WmlFunctionArtifact:
      ...
   


