"""
This type stub file was generated by pyright.
"""

logger = ...
class WmlLibrariesAdapter:
    """
    Adapter creating libraries artifact using output from service.
    """
    def __init__(self, library_output, client) -> None:
        ...
    
    def artifact(self): # -> LibrariesArtifact:
        ...
    


