"""
This type stub file was generated by pyright.
"""

import sys
from ibm_watsonx_ai.libs.repo.ml_authorization import MLAuthorization

if sys.version_info < (3, 0):
    ...
else:
    ...
class MLRepositoryClient(MLAuthorization):
    """
    Main class used as client to connect to Repository sevice.

    :param str base_path: base url to watsonx.ai instance
    :param MLApiClient api_client: customized api_client provided by user

    :ivar ModelCollection models: provides client to operate on models

    """
    def __init__(self, base_path=..., api_client=...) -> None:
        ...
    
    def iam_connect(self, wml_vcap): # -> None:
        ...
    
    @staticmethod
    def meta(self): # -> MetaProps:
        """returns meta object

    >>> model_artifact = MLRepositoryArtifact(model, name='test-model-name', training_data=training, meta_props=MetaProps({
    >>> MetaNames.EVALUATION_METRICS: json.dumps([{
    >>>   "name": "accuracy",
    >>>    "value": 0.95,
    >>>    "threshold": 0.9}]) }))
    >>> created_model_artifact = ml_repository_client.models.save(model_artifact)
    >>> created_model_metaprops = created_model_artifact.meta.prop(MetaNames.EVALUATION_METRICS)

        """
        ...
    


def connect(vcap): # -> MLRepositoryClient:
    """
    Authorizes user to connect by providing the vcap

   :param dict vcap: watsonx.ai Credentials with API key or watsonx.ai credentials

   """
    ...

