"""
This type stub file was generated by pyright.
"""

logger = ...
class WmlRuntimesAdapter:
    """
    Adapter creating runtimes artifact using output from service.
    """
    def __init__(self, runtimes_output, client) -> None:
        ...
    
    def artifact(self): # -> RuntimesArtifact:
        ...
    


