"""
This type stub file was generated by pyright.
"""

http = ...
class MLAuthorization:
    """
    Class used to authorize user.

    MLAuthorization shouldn't be used alone. It is created to be used as a base class by MLRepositoryClient.
    """
    def __init__(self, api_client) -> None:
        ...
    
    def iam_authorize(self, vcap): # -> None:
        ...
    
    def get_iam_url(self, base_service_url): # -> str:
        ...
    
    def generate_iam_token(self, base_url, api_key, instance_id): # -> None:
        ...
    
    def authorize(self, user, password): # -> None:
        """
        Authorizes user by username and password

        Both username and password should be credentials taken from watsonx.ai instance.

        :param str user: username taken from watsonx.ai instance
        :param str password: password corresponding with user name taken from watsonx.ai instance

        """
        ...
    
    def authorize_with_token(self, token): # -> None:
        """
        Authorizes user by token.

        :param str token: token

        """
        ...
    


