"""
This type stub file was generated by pyright.
"""

class MetaProps:
    """
    Holder for props used during creation of ML artifacts.

    :param map meta: Map of pair key and value where key is taken from MetaNames.
    """
    def __init__(self, meta) -> None:
        ...
    
    def available_props(self):
        """Return list of strings with names of available props."""
        ...
    
    def prop(self, name):
        """Get prop value by name."""
        ...
    
    def merge(self, other): # -> None:
        """Merge other MetaProp object to first one. Modify first MetaProp object, doesn't return anything."""
        ...
    
    def add(self, name, value): # -> None:
        """
        Add new prop.

        :param str name: Key for value. Should be one of the values from MetaNames.
        :param object value: Any type of object
        """
        ...
    
    def get(self): # -> Any:
        """returns meta prop dict"""
        ...
    


