"""
This type stub file was generated by pyright.
"""

from .artifact import Artifact

class WmlFunctionArtifact(Artifact):
    """
    Class representing function artifact.

    :param str uid: optional, uid which indicate that artifact already exists in repository service
    :param str name: optional, name of artifact
    :param MetaProps meta_props: optional, props used by other services
    """
    def __init__(self, uid, name, meta_props) -> None:
        ...
    


