"""
This type stub file was generated by pyright.
"""

class CompressionUtil:
    @staticmethod
    def create_tar(path, arcname, archive_path): # -> None:
        ...
    
    @staticmethod
    def extract_tar(archive_path, path): # -> None:
        ...
    
    @staticmethod
    def compress_file_gzip(filepath, gzip_filepath): # -> None:
        ...
    
    @staticmethod
    def decompress_file_gzip(gzip_filepath, filepath): # -> None:
        ...
    


