"""
This type stub file was generated by pyright.
"""

class Json2ObjectMapper:
    @staticmethod
    def read(json_holder): # -> dict[Any, Any] | Any:
        ...
    
    @staticmethod
    def to_dict(json_str): # -> Any:
        ...
    
    @staticmethod
    def to_object(json_holder): # -> Any | object:
        ...
    


