"""
This type stub file was generated by pyright.
"""

from ibm_watsonx_ai.libs.repo.base_constants import *

lib_checker = ...
class SparkUtil:
    DEFAULT_LABEL_COL = ...
    @staticmethod
    def get_label_col(spark_artifact): # -> Literal['label']:
        ...
    
    @staticmethod
    def get_label_col_from__stages(stages): # -> Literal['label']:
        ...
    


