"""
This type stub file was generated by pyright.
"""

from typing import Callable, TYPE_CHECKING
from ibm_watsonx_ai.utils.auth.base_auth import RefreshableTokenAuth
from ibm_watsonx_ai import APIClient

if TYPE_CHECKING:
    ...
class TrustedProfileAuth(RefreshableTokenAuth):
    """Trusted profile authentication method class.

    :param api_client: initialized APIClient object with set project or space ID
    :type api_client: APIClient

    :param token: token to be used to generate trusted profile token
    :type token: str, optional

    :param on_token_creation: callback which allows to notify about token creation
    :type on_token_creation: function which takes no params and returns nothing, optional

    :param on_token_refresh: callback which allows to notify about token refresh
    :type on_token_refresh: function which takes no params and returns nothing, optional

    :param on_token_set: callback which allows to notify about token set
    :type on_token_set: function which takes no params and returns nothing, optional
    """
    def __init__(self, api_client: APIClient, token: str | None = ..., on_token_creation: Callable[[], None] | None = ..., on_token_refresh: Callable[[], None] | None = ..., on_token_set: Callable[[], None] | None = ...) -> None:
        ...
    
    def get_token(self) -> str:
        """Returns the trusted profile token. If `api_key` has been passed and the token will be about to expire, it will be refreshed.
        If classic token is set, a new trusted profile token will be generated and set.

        :returns: token to be used with service
        :rtype: str
        """
        ...
    
    def set_token(self, token: str) -> None:
        """Set new token.

        :param token: token to be used to generate trusted profile token
        :type token: str
        """
        ...
    


